user/python-ssh2/template.py

user/python-ssh2: update to 1.1.2

---

main/spiped/template.py

main/spiped: update to 1.6.3

---

main/aerc/template.py

main/aerc: update to 0.20.0

---

main/uv/patches/no-jemalloc.patch
main/uv/template.py

main/uv: update to 0.5.24

---

main/sway/template.py

main/sway: update to 1.10.1

---

user/texlab/template.py

user/texlab: update to 5.22.0

---

main/gmic/patches/ldflags.patch
main/gmic/template.py

main/gmic: update to 3.5.1

---

main/bind/patches/skip-dispatch.patch
main/bind/template.py

main/bind: update to 9.20.5

---

main/gmic/template.py

main/gmic: update to 3.5.2

---

main/haproxy/template.py

main/haproxy: update to 3.1.3

---

user/refine/template.py

Update Refine to 0.4.3
- Add spanish translation
- Add german translation
- Ignore errors when opening the about dialog

user/refine: update to 0.4.3

---

main/sdl2-compat/template.py
main/sdl3/template.py

update sdl3 + sdl2-compat

---

main/openvpn/template.py

main/openvpn: update to 2.6.13

---

user/python-dbus-fast/patches/remove_codspeed.patch
user/python-dbus-fast/patches/remove_pytest_cov.patch
user/python-dbus-fast/template.py

user/python-dbus-fast: update to 2.32.0

---

user/eza/template.py

user/eza: update to 0.20.19

---

main/fzf/template.py

main/fzf: update to 0.59.0

---

main/stress-ng/template.py

main/stress-ng: update to 0.18.10

---

main/uv/template.py

main/uv: update to 0.5.29

---

user/sad/template.py

user/sad: update to 0.4.32

---

user/neocmakelsp/template.py

user/neocmakelsp: update to 0.8.18

---

user/texlab/template.py

user/texlab: update to 5.22.1

---

user/dnscontrol/template.py

user/dnscontrol: update to 4.16.0

---

user/neocmakelsp/template.py

user/neocmakelsp: update to 0.8.19

---

main/python-boto3/template.py
main/python-botocore/template.py

main/python-boto3: update to 1.36.16

---

main/fnott/template.py

main/fnott: update to 1.7.1, adopt

---

user/pastel/template.py

user/pastel: add dependency on zenity

---

user/miniserve/template.py

user/miniserve: update to 0.29.0

---

user/re2c/template.py

user/re2c: new package

---

main/podman/files/podman-restart
main/podman/template.py

see https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/77702

main/podman: fix restart behavior

---

main/freerdp/patches/off_t.patch
main/freerdp/template.py

main/freerdp: update to 3.11.1

---

main/man-pages/template.py

installs a bunch of commands now (sortman, etc.) that apparently help with maintaining manpages, not sure what we want to do with these

main/man-pages: update to 6.10

---

main/luanti/template.py

main/luanti: update to 5.11.0

---

main/uv/template.py

main/uv: update to 0.6.0

---

main/fzf/template.py

main/fzf: update to 0.60.0

---

user/eza/template.py

user/eza: update to 0.20.21

---

user/hcloud/template.py

this pr adds a package that contains the official cli for hetzner - a cloud services provider

user/hcloud: new package

---

user/tlpui/template.py

The Python scripts in this project generate a GTK-UI to change [TLP](https://github.com/linrunner/TLP) configuration files easily. It has the aim to protect users from setting bad configuration and to deliver a basic overview of all the valid configuration values.

user/tlpui: add new package

---

main/obs-pipewire-audio-capture/template.py

main/obs-pipewire-audio-capture: update to 1.2.0

---

user/typstyle/template.py

user/typstyle: update to 0.12.15

---

main/bubblejail/template.py

main/bubblejail: update to 0.9.5

---

user/jaq/template.py

user/jaq: update to 2.1.0

---

user/tig/template.py

user/tig: move from main, update to 2.5.12

---

user/just/template.py

user/just: update to 1.39.0

---

user/oxipng/template.py

user/oxipng: update to 9.1.4

---

user/tlpui/template.py

Update tlpui to 1.8.0
Changelog:
* Add TLP 1.8 release support
* Add Python 3.13 test support
* Update Python dependencies
* Fix markup error in config description

user/tlpui: update to 1.8.0

---

main/docker-cli-buildx/template.py

main/docker-cli-buildx: update to 0.21.0

---

main/mercurial/template.py

main/mercurial: update to 6.9.2

---

main/haproxy/template.py

main/haproxy: update to 3.1.4

---

user/got/template.py

user/got: update to 0.109

---

main/yadm/template.py

main/yadm: update to 3.4.0

---

user/tinymist/template.py
user/tinymist/update.py

user/tinymist: update to 0.12.20

---

user/re2c/template.py

user/re2c: update to 4.1

---

user/eza/template.py

user/eza: update to 0.20.22

---

user/gcli/template.py

user/gcli: new package

---

user/fonts-ibm-plex-serif-otf
user/fonts-ibm-plex-serif-ttf
user/fonts-ibm-plex-serif/template.py
user/fonts-ibm-plex-serif/update.py

Adds a new font package IBM Plex Serif.

user/fonts-ibm-plex-serif: new package

---

user/fonts-ibm-plex-sans-otf
user/fonts-ibm-plex-sans-ttf
user/fonts-ibm-plex-sans/template.py
user/fonts-ibm-plex-sans/update.py

Adds a new font package IBM Plex Sans.

user/fonts-ibm-plex-sans: new package

---

user/go-sendxmpp/template.py

user/go-sendxmpp: new package

---

user/swaysome/template.py

user/swaysome: new package

---

user/refine/template.py

Update Refine to 0.4.5
- Add french translation
- Add Persian translation

user/refine: update to 0.4.5

---

user/neatvnc/template.py

user/neatvnc: update to 0.9.3

---

user/typstyle/template.py

user/typstyle: update to 0.13.0

---

main/haproxy/template.py

main/haproxy: update to 3.1.5

---

user/xournalpp/template.py

user/xournalpp: update to 1.2.6

---

user/rspamd/patches/rbl.patch
user/rspamd/template.py

user/rspamd: add patch to remove nixspam rbl

---

main/swayimg/template.py

main/swayimg: enable cfi, adopt

---

user/xmpp-dns/template.py

user/xmpp-dns: new package

---

main/docker-cli-buildx/template.py

main/docker-cli-buildx: update to 0.21.1

---

main/python-boto3/template.py
main/python-botocore/template.py

main/python-boto3: update to 1.37.1

---

user/uv/template.py

user/uv: update to 0.6.3

---

user/liblsdj-devel
user/liblsdj/patches/system-catch2.patch
user/liblsdj/template.py
user/liblsdj/update.py

a couple of tools for working with save data for the lsdj music tracker

user/liblsdj: new package

---

user/alacritty/template.py

user/alacritty: update to 0.15.1

---

main/docker-compose/template.py

main/docker-compose: update to 2.33.1

---

main/nicotine-plus/template.py

main/nicotine-plus: update to 3.3.8

---

user/typst/template.py

user/typst: update to 0.13.0

---

user/niri/template.py

user/niri: update to 25.02

---

main/qt6-qtwebengine/template.py

main/qt6-qtwebengine: bump security release

---

user/uv/template.py

user/uv: update to 0.6.4

---

main/lua5.4-luasystem/template.py

main/lua5.4-luasystem: update to 0.5.0

---

user/neatvnc/template.py

user/neatvnc: update to 0.9.4

---

user/gajim/template.py
user/python-nbxmpp/template.py

user/gajim: update to 2.0.1

---

user/neocmakelsp/template.py

user/neocmakelsp: update to 0.8.21

---

user/gopls/template.py

user/gopls: update to 0.18.1

---

user/lazygit/template.py

user/lazygit: update to 0.48.0

---

user/syft/template.py

user/syft: update to 1.20.0

---

main/fzf/template.py

main/fzf: update to 0.60.2

---

main/dino/template.py

main/dino: update to 0.4.5

---

user/mu/template.py

user/mu: update to 1.12.9

---

user/rspamd/template.py

user/rspamd: use system fmt

---

user/shfmt/template.py

user/shfmt: update to 3.11.0

---

main/mercurial/template.py

main/mercurial: update to 6.9.3

---

user/bacon/template.py

user/bacon: update to 3.11.0

---

user/gcli/template.py

user/gcli: update to 2.7.0

---

main/tlp/template.py

Update `tlp` to 1.8.0:
* New: bat.d/55-cros-ec, 56-framework, 65-dell

main/tlp: update to 1.8.0

---

user/yazi/patches/bsd-ls.patch
user/yazi/patches/no-jemalloc.patch
user/yazi/template.py

user/yazi: update to 25.3.2

---

main/fcft/template.py

main/fcft: update to 3.2.0

---

user/uv/template.py

user/uv: update to 0.6.5

---

user/jj/patches/git2.patch
user/jj/template.py

user/jj: update to 0.27.0

---

user/refine/template.py

Update Refine to 0.5.4:
- Add Ukrainian translation
- Add Georgian translation

user/refine: update to 0.5.4

---

user/git-absorb/patches/fix-manpage-version.patch
user/git-absorb/template.py

user/git-absorb: update to 0.7.0

---

user/television/template.py

user/television: update to 0.10.7

---

user/typst/template.py

user/typst: update to 0.13.1

---

user/delve/template.py

user/delve: update to 1.24.1

---

user/dnscontrol/template.py

user/dnscontrol: update to 4.17.0

---

user/uv/template.py

user/uv: update to 0.6.6

---

main/sfeed/template.py

main/sfeed: update to 2.2

---

user/hugo/template.py

user/hugo: update to 0.145.0

---

user/gajim/template.py

user/gajim: update to 2.0.2

---

main/python-boto3/template.py
main/python-botocore/template.py

main/python-boto3: update to 1.37.11

---

user/eza/template.py

user/eza: update to 0.20.23

---

user/python-dbus-fast/patches/remove_codspeed.patch
user/python-dbus-fast/template.py

user/python-dbus-fast: update to 2.39.3

---

user/showmethekey/patches/gtk-update-icon-cache.patch
user/showmethekey/template.py

user/showmethekey: new package

---

user/kakoune-lsp/template.py

user/kakoune-lsp: update to 18.1.3

---

user/fish-shell/template.py

user/fish-shell: update to 4.0.1

---

main/python-pyproject-metadata/template.py

main/python-pyproject-metadata: update to 0.9.1

---

user/rustypaste-cli/template.py

user/rustypaste-cli: update to 0.9.3

---

user/eza/template.py

user/eza: update to 0.20.24

---

user/yadm/template.py

user/yadm: move from main, update to 3.5.0

---

user/refine/template.py

user/refine: update to 0.5.5

---

main/gammastep/files/gammastep.user
main/gammastep/template.py

main/gammastep: update to 2.0.10, add user service

---

user/swww/files/swww.user
user/swww/template.py

user/swww: add user service

---

user/dust/template.py

user/dust: update to 1.1.2

---

main/yt-dlp/template.py

main/yt-dlp: update to 2025.03.21

---

main/newsraft/template.py

main/newsraft: update to 0.29

---

user/gajim/template.py

user/gajim: update to 2.0.4

---

user/tealdeer/template.py

user/tealdeer: update to 1.7.2

---

user/rustypaste/template.py

user/rustypaste: update to 0.16.1

---

user/typstyle/template.py

user/typstyle: update to 0.13.1

---

main/haproxy/template.py

main/haproxy: update to 3.1.6

---

user/uv/template.py

user/uv: update to 0.6.9

---

main/certbot/template.py
main/python-acme/template.py

main/certbot main/python-acme: update to 3.3.0

---

main/pipewire/template.py

main/pipewire: update to 1.4.1

---

user/pods/patches/no-clippy.patch
user/pods/template.py

user/pods: update to 2.2.0

---

main/bluez/template.py

main/bluez: update to 5.80

---

main/mercurial/template.py

main/mercurial: update to 6.9.4

---

user/syncthing/files/syncthing.user
user/syncthing/template.py

user/syncthing: update to 1.29.3

---

main/wl-mirror/template.py

main/wl-mirror: update to 0.18.0

---

main/furnace/update.py

was picking up a prerelease tag

main/furnace: fix update check

---

main/swaylock/template.py

main/swaylock: update to 1.8.2

---

user/got/template.py

user/got: update to 0.110

---

user/sworkstyle/template.py

user/sworkstyle: update to 1.3.6

---

main/bcachefs-tools/template.py

main/bcachefs-tools: update to 1.25.0

---

main/mercurial/template.py

main/mercurial: update to 7.0

---

main/stockfish/patches/makefile_cxxflags.patch
main/stockfish/template.py

main/stockfish: update to 17.1

---

main/mako/patches/tangle.patch
main/mako/template.py

Updates mako to 1.10.0! Pretty straightforward, but I had to update the patch to conditionally include tangle headers in `makoctl.c`.

main/mako: update to 1.10.0

---

user/stunnel/update.py

Fix version check with update.py

user/stunnel: add update.py

---

user/agate/template.py

A server for the Gemini Protocol called agate.

user/agate: new package

---

main/sd-tools/patches/uid-range-fix-32-bit.patch
main/sd-tools/template.py

Applies the fix for https://github.com/chimera-linux/sd-tools/issues/1.

main/sd-tools: fix uid range handling on 32-bit platforms

---

main/zlib-ng-compat/patches/armv7-test-fix.patch
main/zlib-ng-compat/patches/work-around-all-armv7-targets.patch

These two patches fix the zlib-ng tests and also ensure that python's zlib tests pass.

main/zlib-ng-compat: fix tests on ARMv7

---

main/openvpn/template.py

main/openvpn: update to 2.6.14

---

main/janet/template.py

main/janet: update to 1.38.0

---

main/tecla/template.py

main/tecla: update to 48.0.2

---

user/refine/template.py

Changelog:
- Update Brazilian Portuguese translation

user/refine: update to 0.5.6

---

user/celluloid/template.py

user/celluloid: update to 0.28

---

user/lego/template.py

user/lego: update to 4.22.2

---

user/jaq/template.py

user/jaq: update to 2.2.1

---

user/just/template.py

user/just: update to 1.40.0

---

main/python-setuptools/template.py

main/python-setuptools: update to 78.1.0

---

main/hidapi/template.py

main/hidapi: enforce minimum cmake version policy

---

main/ldacbt/template.py

main/ldacbt: enforce minimum cmake version policy

---

main/libaom/template.py

Required to build the package on ARMv7.

main/libaom: specify assembler for ARMv7

---

main/libcbor/template.py

main/libcbor: enforce minimum cmake version policy

---

main/ledger/template.py

main/ledger: enforce minimum cmake version policy

---

main/binutils-armv7
main/binutils/template.py

main/binutils: add ARMv7 target

---

main/libcue/template.py

main/libcue: enforce minimum cmake version policy

---

main/libebml/template.py

main/libebml: enforce minimum cmake version policy

---

main/libebur128/template.py

main/libebur128: enforce minimum cmake version policy

---

main/libid3tag/template.py

main/libid3tag: enforce minimum cmake version policy

---

main/libmatroska/template.py

main/libmatroska: enforce minimum cmake version policy

---

main/kyua/patches/add-more-information-to-failed-test.patch

Patch is a cherry-pick from newer release.

main/kyua: fix checks on ARMv7

---

main/libsbsms/template.py

main/libsbsms: enforce minimum cmake version policy

---

main/libsignal-protocol-c/template.py

main/libsignal-protocol-c: enforce minimum cmake version policy

---

main/libvidstab/template.py

main/libvidstab: enforce minimum cmake version policy

---

main/nbfc-linux/template.py

Fails with the same error on 32-bit ARM.

main/nbfc-linux: broken on all 32-bit targets

---

main/brlaser/template.py

main/brlaser: enforce minimum cmake version policy

---

main/neovim/template.py

Bump the version of neovim, as there is an upgrade in the upstream.

main/neovim: update to 0.11.0

---

main/pystring/template.py

main/pystring: enforce minimum cmake version policy

---

main/plog/template.py

main/plog: enforce minimum cmake version policy

---

user/python-desktop-notifier/template.py

user/python-desktop-notifier: update to 6.1.0

---

main/robin-map/template.py

main/robin-map: enforce minimum cmake version policy

---

main/rapidjson/template.py

main/rapidjson: enforce minimum cmake version policy

---

main/snappy/template.py

main/snappy: enforce minimum cmake version policy

---

main/soxr/template.py

main/soxr: enforce minimum cmake version policy

---

main/srt/template.py

main/srt: enforce minimum cmake version policy

---

main/thinkfan/template.py

main/thinkfan: enforce minimum cmake version policy

---

main/unshield/template.py

main/unshield: enforce minimum cmake version policy

---

main/unittest-cpp/template.py

main/unittest-cpp: enforce minimum cmake version policy

---

main/wabt/template.py

Fails with the same error as on loongarch64.

main/wabt: disable checks on ARMv7

---

main/pv/patches/gettext-ver.patch
main/pv/template.py

Same as the other gettext / autotools ones.

main/pv: fix build

---

main/xdg-user-dirs/patches/gettext-ver.patch
main/xdg-user-dirs/template.py

Probably broke with newer autotools or something along those lines.

main/xdg-user-dirs: fix build

---

main/liblangtag/template.py

main/liblangtag: add missing glib-devel dependency

---

main/grass/patches/fix-i64-overflow.patch

Otherwise this would overflow. Patch taken from Alpine.

main/grass: fix checks on ARMv7

---

main/libmediainfo/template.py

main/libmediainfo: enforce minimum cmake version policy

---

user/thrift/template.py

user/thrift: enforce minimum cmake version policy

---

main/lensfun/template.py

main/lensfun: enforce minimum cmake version policy

---

main/exiv2/template.py

main/exiv2: disable checks on 32-bit targets

---

user/rkdeveloptool/template.py

user/rkdeveloptool: enforce minimum cmake version policy

---

main/clucene/template.py

main/clucene: enforce minimum cmake version policy

---

main/mc/template.py

Taken from https://midnight-commander.org/source-code/

main/mc: update source url

---

user/puzzles/template.py

user/puzzles: update to 0_git20250303

---

user/monolith/template.py

user/monolith: update to 2.10.1

---

user/perl-encode-locale/template.py
user/perl-encode-locale/update.py
user/perl-file-basedir/template.py
user/perl-file-basedir/update.py
user/perl-file-desktopentry/template.py
user/perl-file-desktopentry/update.py
user/perl-file-mimeinfo/template.py
user/perl-file-mimeinfo/update.py
user/perl-file-which/template.py
user/perl-file-which/update.py
user/perl-ipc-system-simple/template.py
user/perl-ipc-system-simple/update.py
user/perl-test-pod-coverage/template.py
user/perl-test-pod-coverage/update.py

user/perl-file-mimeinfo: new package

---

user/sblg/patches/make.patch
user/sblg/template.py
user/sblg/update.py

user/sblg: new package

---

user/tlstunnel/files/sysusers.conf
user/tlstunnel/files/tlstunnel
user/tlstunnel/files/tmpfiles.conf
user/tlstunnel/template.py

A TLS reverse proxy.
* Should Makefile be preferred for simple installation? (eg. just copy and generate documentation from scdoc)
* For services, should there be a default configuration example in /etc?

user/tlstunnel: new package

---

main/sbcl/template.py

main/sbcl: update to 2.5.3

---

user/kimchi/files/kimchi
user/kimchi/files/sysusers.conf
user/kimchi/files/tmpfiles.conf
user/kimchi/template.py

user/kimchi: new package

---

main/swayimg/template.py

main/swayimg: update to 3.9

---

user/pounce/patches/fix-configure.patch
user/pounce/template.py

A new package for pounce, an IRC bouncer.

user/pounce: new package

---

main/git/patches/t4201-tr-workaround.patch
main/git/patches/t4301-gsed.patch
main/git/patches/t7422-fix-invalid-printf.patch
main/git/template.py

main/git: fix tests; enable vis, cfi; update to 2.49.0

---

user/wl-kbptr/patches/sh.patch
user/wl-kbptr/template.py

user/wl-kbptr: move from main, update to 0.3.0

---

main/firmware-sof/template.py

main/firmware-sof: update to 2025.01.1

---

main/qrencode/template.py

Old URL is a 404. Bumped pkgrel to ensure nothing broke with the new source.

main/qrencode: fetch from GitHub releases

---

user/fnf/template.py

FNF is a minimal fuzzy finder like FZF.
Addresses #3425

user/fnf: new package

---

user/neomutt/template.py

user/neomutt: update to 2025.04.04

---

main/fuzzel/template.py

main/fuzzel: update to 1.12.0

---

main/copyq/patches/qt69.patch
main/copyq/template.py

main/copyq: update to 10.0.0

---

user/typstyle/template.py

user/typstyle: update to 0.13.3

---

user/eza/template.py

user/eza: update to 0.21.0

---

user/tailspin/template.py

user/tailspin: update to 5.2.1

---

user/python-nbxmpp/template.py

user/python-nbxmpp: update to 6.1.1

---

main/fwupd/patches/libxmlb-version.patch

main/fwupd: fix checks with newer libxmlb

---

user/nuclei/template.py

- [X ] I have built and tested my changes on my machine

user/nuclei: update to 3.4.2

---

user/k6/template.py

user/k6: update to 0.58.0

---

user/bambootracker/template.py

user/bambootracker: enforce minimum cmake version policy

---

main/mt32emu/template.py

main/mt32emu: enforce minimum cmake version policy

---

main/freealut/template.py

main/freealut: enforce minimum cmake version policy

---

user/gajim/template.py

user/gajim: update to 2.1.0

---

user/supertuxkart/patches/cmake-policies.patch
user/supertuxkart/template.py

user/supertuxkart: fix build with CMake 4.0

---

main/mgba/template.py

main/mgba: enforce minimum cmake version policy

---

user/nxengine-evo/template.py

user/nxengine-evo: enforce minimum cmake version policy

---

main/rrdtool/patches/0001-Address-the-case-when-time_t-is-64bits.patch

main/rrdtool: fix checks on 32-bit targets

---

main/mygui/template.py

main/mygui: enforce minimum cmake version policy

---

main/wxwidgets/template.py

main/wxwidgets: enforce minimum cmake version policy

---

main/libgme/template.py

main/libgme: enforce minimum cmake version policy

---

user/opengothic/template.py

user/opengothic: enforce minimum cmake version policy

---

user/uv/template.py

user/uv: update to 0.6.14

---

user/k6/patches/fix-32-bit-targets.patch

user/k6: fix build for 32-bit targets

---

main/x265/patches/fix-cmake-4.0.patch
main/x265/template.py

main/x265: enforce minimum cmake version policy

---

user/supertux2/template.py

SuperTux is an open-source classic 2D jump'n run sidescroller game in a style similar to the original Super Mario games.

user/supertux2: new package

---

main/clucene/template.py

Broken tests, unmaintained project (?).

main/clucene: disable checks on 32-bit targets

---

user/binwalk/template.py

user/binwalk: new package

---

user/blanket/template.py

new package `user/blanket` by rafaelmardojai

user/blanket: new package

---

user/tofi/patches/strtol-fix.patch
user/tofi/template.py

Add a patch to make it build for ARMv7.

user/tofi: fix for ARMv7

---

user/cloc/patches/make.patch
user/cloc/template.py
user/perl-algorithm-diff/template.py
user/perl-algorithm-diff/update.py
user/perl-digest-md5/template.py
user/perl-digest-md5/update.py
user/perl-parallel-forkmanager/template.py
user/perl-parallel-forkmanager/update.py
user/perl-regexp-common/template.py
user/perl-regexp-common/update.py
user/perl-sub-uplevel/template.py
user/perl-sub-uplevel/update.py
user/perl-test-warn/template.py
user/perl-test-warn/update.py

user/cloc: new package

---

user/pdfgrep/template.py

This is a commandline utility to search text in PDF files.
- [ x ] I have read [CONTRIBUTING.md](https://github.com/chimera-linux/cports/blob/master/CONTRIBUTING.md)
- [ x ] I have read [Packaging.md](https://github.com/chimera-linux/cports/blob/master/Packaging.md#quality_requirements)
- [ x ] I have built and tested my changes on my machine
- [ x ] I will take responsibility for my template and keep it up to date

user/pdfgrep: new package

---

user/comrak/template.py

user/comrak: update to 0.38.0

---

user/chezmoi/template.py

user/chezmoi: update to 2.62.2

---

user/gcc-bootstrap/template.py

Tested on ARMv7 and x86_64 to ensure this doesn't break other targets.

user/gcc-bootstrap: add ARMv7 sources

---

user/gleam/patches/js-runtimes-test.patch
user/gleam/template.py

The gleam programming language  
https://gleam.run

user/gleam: new package

---

main/mpd/files/mpd
main/mpd/files/mpd.user
main/mpd/template.py

main/mpd: update to 0.24.3, add user service

---

user/activate-linux/patches/fixinstall.patch
user/activate-linux/patches/makeoverride.patch
user/activate-linux/patches/pkgconf.patch
user/activate-linux/template.py

Activate-linux is a satirical program which creates a watermark displaying the message "Activate Linux, Go to Settings to activate Linux", in the style of the "Activate Windows" watermark present on unactivated versions of windows.
It supports arbitrary customisation of the text displayed, as well as a number of presets for various different platforms (such as BSD, mac and the steam deck, among others).
https://github.com/MrGlockenspiel/activate-linux

user/activate-linux: new package

---

user/poweralertd/files/poweralertd.user
user/poweralertd/patches/tangle.patch
user/poweralertd/template.py

user/poweralertd: move from main, add user service

---

user/caddy/template.py

user/caddy: update to 2.10.0

---

main/foot/template.py

main/foot: update to 1.22.0

---

user/k6/patches/fix-32-bit-targets.patch

user/k6: update patch for 0.58

---

user/gcc/template.py

user/gcc: add ARMv7 support

---

main/fzf/template.py

main/fzf: update to 0.61.2

---

user/fish-shell/template.py

user/fish-shell: update to 4.0.2

---

user/neocmakelsp/template.py

user/neocmakelsp: update to 0.8.22

---

user/broot/template.py

user/broot: update to 1.46.1

---

user/wpaperd/files/wpaperd.user
user/wpaperd/template.py

user/wpaperd: update to 1.2.1, add user service

---

user/re2c/template.py

user/re2c: update to 4.2

---

user/direnv/template.py

user/direnv: update to 2.36.0

---

main/wl-mirror/template.py

main/wl-mirror: update to 0.18.1

---

user/stylua/template.py

user/stylua: update to 2.1.0

---

user/lazygit/template.py

user/lazygit: update to 0.49.0

---

user/hugo/template.py

user/hugo: update to 0.146.7

---

main/perl-image-exiftool/template.py

main/perl-image-exiftool: update to 13.27

---

user/opentofu/template.py

user/opentofu: update to 1.9.1

---

main/haproxy/template.py

main/haproxy: update to 3.1.7

---

user/got/template.py

user/got: update to 0.111

---

user/syft/template.py

user/syft: update to 1.23.1

---

main/foot/template.py

main/foot: update to 1.22.1

---

user/eza/template.py

user/eza: update to 0.21.2

---

user/stunnel/update.py

user/stunnel: ignore beta versions

---

main/doctest/template.py
main/graphite2/template.py
main/json-c/template.py

doctest, graphite2, json-c: enforce minimum cmake version policy

---

main/libmicrohttpd/patches/fix-test-tricky-url.patch

Add patch to fix failing test.

main/libmicrohttpd: patch test to pass on recent curl

---

user/github-cli/template.py

user/github-cli: update to 2.71.2

---

user/typstyle/template.py

user/typstyle: update to 0.13.4

---

user/python-dbus-fast/patches/remove_pytest_cov.patch
user/python-dbus-fast/template.py

user/python-dbus-fast: update to 2.44.1

---

user/gleam/template.py

user/gleam: update to 1.10.0

---

user/python-desktop-notifier/template.py

user/python-desktop-notifier: update to 6.1.1

---

user/jaq/template.py

user/jaq: update to 2.2.0

---

main/neovim/template.py

main/neovim: update to 0.11.1

---

main/sbcl/template.py

main/sbcl: update to 2.5.4

---

user/broot/template.py

user/broot: update to 1.46.3

---

user/pdfcpu/template.py

user/pdfcpu: update to 0.10.2

---

main/python-jinja2/template.py

Update python-jinja2 to 3.1.6 in preparation to submit saltstack

main/python-jinja2: update to 3.1.6

---

main/pdfjs/template.py

main/pdfjs: update to 5.2.133

---

user/delve/template.py

user/delve: update to 1.24.2

---

user/btop/template.py

user/btop: update to 1.4.1

---

user/golangci-lint/template.py

user/golangci-lint: update to 2.1.5

---

user/refine/template.py

Changelog:
* Update Persian translation

user/refine: update to 0.5.8

---

user/oxipng/template.py

user/oxipng: update to 9.1.5

---

main/unbound/template.py

main/unbound: update to 1.23.0

---

user/ani-cli/template.py

user/ani-cli: update to 4.10

---

user/uv/template.py

user/uv: update to 0.7.2

---

main/freeglut/template.py
main/gflags/template.py
main/musl-locales/template.py

musl-locales, freeglut, gflags: enforce minimum cmake version policy

---

user/yazi/patches/no-jemalloc.patch
user/yazi/template.py

user/yazi: update to 25.4.8

---

user/cwm/patches/0001-override-flags-and-install-license.patch
user/cwm/template.py

Package for a port of OpenBSD's cwm: https://github.com/leahneukirchen/cwm

user/cwm: new package

---

user/mmv/template.py

user/mmv: new package

---

user/yggdrasil-keygen/template.py

user/yggdrasil-keygen: new package

---

user/timg/template.py

this was previously open at https://github.com/chimera-linux/cports/pull/3745 but i was working on master branch of my fork and when trying to fix stuff i managed to close the PR. so, opening a new one properly. i am extremely sorry for any issue caused with this.
Add new package `user/timg`.

user/timg: new package

---

main/redland/template.py

main/redland: disable checks on ARMv7

---

main/guile/template.py

main/guile: disable checks on ARMv7

---

main/capstone/template.py

Reported upstream, let's disable this one for now.

main/capstone: skip failing test on ARMv7

---

user/riff/template.py

user/riff: new package

---

user/golangci-lint/template.py

user/golangci-lint: update to 2.1.6

---

user/k6/template.py

user/k6: update to 1.0.0

---

user/gajim/template.py

user/gajim: update to 2.1.1

---

user/trippy/template.py

user/trippy: update to 0.13.0

---

main/wl-mirror/template.py

main/wl-mirror: update to 0.18.2

---

user/satty/template.py

user/satty: update to 0.18.1

---

user/agate/template.py

updated agate to version 3.3.16

user/agate: update to 3.3.16

---

user/refine/template.py

Changelog:
* Add Arabic translation

user/refine: update to 0.5.9

---

user/gofumpt/template.py

user/gofumpt: new package

---

user/fonts-intel-one-mono-otf/template.py

The [Intel One Mono](https://github.com/intel/intel-one-mono) font.

user/fonts-intel-one-mono-otf: new package

---

user/typstyle/template.py

user/typstyle: update to 0.13.6

---

user/eza/template.py

user/eza: update to 0.21.3

---

main/weechat/template.py

main/weechat: update to 4.6.3

---

user/yq/template.py

user/yq: update to 4.45.4

---

main/python-pip/template.py

main/python-pip: update to 25.1.1

---

user/rustypaste-cli/template.py

user/rustypaste-cli: update to 0.9.4

---

user/tailspin/template.py

user/tailspin: update to 5.4.2

---

main/qt6-qtwebengine/template.py

main/qt6-qtwebengine: bump security ver

---

user/dnscontrol/template.py

user/dnscontrol: update to 4.20.0

---

user/neomutt/template.py

user/neomutt: update to 2025.05.10

---

user/syft/template.py

user/syft: update to 1.24.0

---

user/cargo-update/patches/typo.patch
user/cargo-update/template.py

user/cargo-update: new package

---

main/python-docstring-to-markdown/patches/fix_importlib_metadata.patch
main/python-docstring-to-markdown/template.py

main/python-docstring-to-markdown: enable checks, update to 0.17

---

user/satty/template.py

user/satty: update to 0.19.0

---

user/goaccess/template.py

user/goaccess: new package

---

user/selene/patches/update-getrandom.patch
user/selene/template.py

A new package called selene which is a linter for Lua.

user/selene: new package

---

user/wpaperd/template.py

user/wpaperd: update to 1.2.2

---

user/syft/template.py

user/syft: update to 1.25.1

---

user/gajim/template.py
user/python-nbxmpp/template.py

user/gajim: update to 2.2.0

---

main/nerdctl/template.py

main/nerdctl: update to 2.1.1

---

user/typstyle/template.py

user/typstyle: update to 0.13.7

---

main/chafa/template.py

main/chafa: update to 1.16.0

---

main/swayimg/template.py

main/swayimg: update to 4.0

---

user/uv/template.py

user/uv: update to 0.7.6

---

user/celluloid/template.py

user/celluloid: update to 0.29

---

user/neocmakelsp/template.py

user/neocmakelsp: update to 0.8.23

---

user/syft/template.py

user/syft: update to 1.26.0

---

main/less/template.py

main/less: update to 678

---

user/niri/template.py

Full release notes are here https://github.com/YaLTeR/niri/releases/tag/v25.05

user/niri: update to 25.05

---

user/got/template.py

user/got: update to 0.112

---

main/containerd/template.py

main/containerd: update to 2.1.1

---

user/nuclei/template.py

user/nuclei: update to 3.4.4

---

user/hugo/template.py

user/hugo: update to 0.147.5

---

main/nerdctl/template.py

main/nerdctl: update to 2.1.2

---

user/mu/template.py

user/mu: update to 1.12.11

---

main/swaync/template.py

main/swaync: update to 0.11.0

---

main/mpd/template.py

main/mpd: update to 0.24.4

---

main/nss/template.py

main/nss: enable for ARMv7

---

user/tailspin/template.py

user/tailspin: update to 5.4.3

---

user/swww/template.py

user/swww: update to 0.10.0

---

user/tflint/template.py

TFLint is a framework and each feature is provided by plugins, the key features are as 
* Find possible errors (like invalid instance types) for Major Cloud providers (AWS/Azure/GCP).
* Warn about deprecated syntax, unused declarations.
* Enforce best practices, naming conventions.

user/tflint: new package

---

user/showmethekey/template.py

user/showmethekey: update to 1.18.3

---

user/gallery-dl/template.py

user/gallery-dl: update to 1.29.7

---

user/minify/template.py

user/minify: update to 2.23.8

---

user/rclone/template.py

user/rclone: update to 1.69.3

---

user/rspamd/template.py
user/snowball/patches/sharedlib.patch
user/snowball/template.py

user/snowball: update to 3.0.1

---

main/ansible-core/patches/0001-skip-failing-test.patch
main/ansible-core/patches/0002-update-ansible-galaxy-resolvelib-requirement-to-0.5..patch
main/ansible-core/patches/0003-fix-broken-ansible-galaxy-collection-resolvelib-test.patch
main/ansible-core/patches/0004-newer-setuptools.patch
main/ansible-core/patches/setuptools.patch
main/ansible-core/template.py
main/ansible/template.py

- **main/ansible-core: update to 2.18.6**
- **main/ansible: update to 11.6.0**

main/ansible: update to 11.6.0

---

main/stress-ng/template.py

main/stress-ng: update to 0.19.00

---

main/strongswan/template.py

While here, replace libtool by slibtool
Update strongswan to most recent version

main/strongswan: update to 6.0.1

---

main/prosody/template.py

main/prosody: update to 13.0.2

---

user/lego/template.py

user/lego: update to 4.23.1

---

main/haproxy/patches/readiness.patch
main/haproxy/template.py

main/haproxy: update to 3.2.0

---

main/ppp/patches/fix-sigill.patch
main/ppp/template.py

main/ppp: fix sigill

---

user/kakoune-lsp/template.py

user/kakoune-lsp: update to 18.2.0

---

user/bacon/template.py

user/bacon: update to 3.15.0

---

user/lazygit/template.py

user/lazygit: update to 0.51.1

---

user/eza/template.py

user/eza: update to 0.21.4

---

user/github-cli/template.py

user/github-cli: update to 2.74.0

---

main/swayimg/template.py

main/swayimg: update to 4.1

---

main/pdfjs/template.py

main/pdfjs: update to 5.3.31

---

user/links/template.py

Links is a Lynx-like text based browser.

user/links: new package

---

user/swww/template.py

user/swww: update to 0.10.2

---

user/kdlfmt/template.py

user/kdlfmt: new package

---

user/hcloud/template.py

user/hcloud: update to 1.51.0

---

user/uv/template.py

user/uv: update to 0.7.12

---

user/syft/template.py

user/syft: update to 1.26.1

---

user/dnscontrol/template.py

user/dnscontrol: update to 4.21.0

---

user/aspell-fr/template.py
user/aspell-fr/update.py

user/aspell-fr: new package

---

main/wev/template.py

main/wev: update to 1.1.0

---

user/swww/template.py

user/swww: update to 0.10.3

---

user/got/template.py

user/got: update to 0.113

---

user/uv/template.py

user/uv: update to 0.7.13

---

user/github-cli/template.py

user/github-cli: update to 2.74.1

---

user/wlogout/patches/completion.patch
user/wlogout/template.py

user/wlogout: new package

---

user/thrift/patches/big-endian.patch
user/thrift/template.py

user/thrift: update to 0.22.0

---

main/haproxy/template.py

main/haproxy: update to 3.2.1

---

user/tea/template.py

user/tea: update to 0.10.1

---

user/dive/template.py

A tool to explore and analyze layers in Docker images.

user/dive: new package

---

user/ttyper/template.py

user/ttyper: new package

---

user/go-away/template.py
user/go-away/update.py

user/go-away: new package

---

main/certbot/template.py
main/python-acme/template.py

main/certbot main/python-acme: update to 4.1.1

---

main/python-nanobind/patches/fix-test-suite.patch
main/python-nanobind/template.py

Cherry-picked patch + new dependency because of it.

main/python-nanobind: fix tests with latest pytest

---

user/dust/template.py

user/dust: update to 1.2.1

---

main/parallel/template.py

The checksum changed upstream, let's bump pkgrel to rebuild against the new sources.

main/parallel: rebuild after source checksum change

---

user/syncthing/template.py

user/syncthing: run tests with -short on 32-bit targets

---

user/fnf/template.py

Install contrib files that fnf offers.

user/fnf: install contrib scripts

---

user/uv/template.py

user/uv: update to 0.7.14

---

user/bfs/template.py

user/bfs: update to 4.0.8

---

user/typstyle/template.py

user/typstyle: update to 0.13.11

---

user/git-cliff/template.py

user/git-cliff: update to 2.9.1

---

user/texlab/template.py

user/texlab: update to 5.23.0

---

user/ov/template.py

user/ov: new package

---

user/static-web-server/patches/jemalloc.patch
user/static-web-server/patches/shadow-no-git.patch
user/static-web-server/template.py

user/static-web-server: update to 2.37.0

---

main/waycheck/template.py

main/waycheck: update to 1.7.0

---

user/miniserve/template.py

user/miniserve: update to 0.31.0

---

main/python-boto3/template.py
main/python-botocore/template.py
main/python-s3transfer/template.py

main/python-boto3: update to 1.38.43

---

user/texlab/template.py

user/texlab: update to 5.23.1

---

user/bacon/template.py

user/bacon: update to 3.16.0

---

user/syft/template.py

user/syft: update to 1.28.0

---

user/eza/template.py

user/eza: update to 0.21.6

---

user/re2c/template.py

user/re2c: update to 4.3

---

user/got/template.py

user/got: update to 0.115

---

user/direnv/template.py

user/direnv: update to 2.37.0

---

user/uv/template.py

user/uv: update to 0.7.19

---

user/ov/template.py

user/ov: update to 0.42.1

---

user/gajim/template.py

user/gajim: update to 2.3.2

---

main/qbittorrent/template.py

main/qbittorrent: update to 5.1.2

---

main/userspace-rcu/patches/skip_tests.patch
main/userspace-rcu/template.py

also run some tests, skip only the actually problematic ones

main/userspace-rcu: update to 0.15.3

---

main/lynx/template.py

Compile lynx with external command menu which allows users to open URLs with shell commands of their choice.

main/lynx: build with external commands menu support

---

main/grim/template.py

main/grim: update to 1.5

---

user/golangci-lint/template.py

user/golangci-lint: update to 2.2.2

---

user/lego/template.py

user/lego: update to 4.24.0

---

user/fnf/template.py

user/fnf: update to 0.2

---

user/shfmt/template.py

user/shfmt: update to 3.12.0

---

main/fzf/template.py

main/fzf: update to 0.64.0

---

user/jaq/template.py

user/jaq: update to 2.3.0

---

main/wbg/template.py

main/wbg: update to 1.3.0

---

main/fcft/template.py
main/foot/template.py

main/foot,main/fcft: update to 1.23.0 and 3.3.2

---

user/eza/template.py

user/eza: update to 0.23.0

---

user/maven/template.py

user/maven: update to 3.9.11

---

main/unbound/template.py

main/unbound: update to 1.23.1

---

main/borg/patches/msgpack.patch
main/borg/template.py

main/borg: relax msgpack version requirement

---

user/selene/template.py

user/selene: update to 0.29.0

---

user/just/template.py

- generate man page and completions with freshly built binary
- package nushell completions
- stop downloading pre-built artifacts

user/just: update to 1.42.4

---

main/fnott/files/fnott.user
main/fnott/template.py

main/fnott: update to 1.8.0

---

user/dnscontrol/template.py

user/dnscontrol: update to 4.22.0

---

user/direnv/template.py

user/direnv: update to 2.37.1

---

user/uv/template.py

user/uv: update to 0.8.4

---

main/pdfjs/template.py

main/pdfjs: update to 5.4.54

---

user/static-web-server/patches/jemalloc.patch
user/static-web-server/template.py

user/static-web-server: update to 2.38.0

---

user/tinymist/template.py
user/tinymist/update.py

user/tinymist: update to 0.13.18

---

main/swaylock/template.py

main/swaylock: update to 1.8.3

---

user/fnf/template.py

user/fnf: update to 0.3.1

---

user/ydotool/template.py

Generic command-line automation tool (no X!)

user/ydotool: new package

---

user/showmethekey/template.py

user/showmethekey: update to 1.18.4

---

user/typstyle/template.py

user/typstyle: update to 0.13.17

---

main/doasedit/template.py

main/doasedit: update to 1.0.8

---

main/fnott/files/fnott.user
main/fnott/template.py

fnott: make service depend on graphical.target

---

user/dunst/template.py

user/dunst: update to 1.13.0

---

user/python-desktop-notifier/template.py

user/python-desktop-notifier: update to 6.2.0

---

user/zellij/template.py

user/zellij: update to 0.43.1

---

user/tayga/patches/94.patch
user/tayga/template.py

picked from https://github.com/chimera-linux/cports/pull/4473, seems useful to pr on its own

user/tayga: new package

---

main/iio-sensor-proxy/template.py

Well, `glib-devel` is part of the host make dependencies.

main/iio-sensor-proxy: fix cross compilation

---

user/go-task/template.py

user/go-task: update to 3.44.1

---

user/bottom/template.py

user/bottom: update to 0.11.1

---

user/bfs/template.py

user/bfs: update to 4.1

---

user/kind/template.py

user/kind: update to 0.29.0

---

main/wl-mirror/template.py

main/wl-mirror: update to 0.18.3

---

user/dnscontrol/template.py

user/dnscontrol: update to 4.23.0

---

user/xmpp-dns/template.py

user/xmpp-dns: update to 0.5.1

---

user/rbw/template.py

user/rbw: update to 1.14.0

---

user/halloy/template.py

user/halloy: update to 2025.8

---

main/obs-pipewire-audio-capture/template.py

main/obs-pipewire-audio-capture: update to 1.2.1

---

main/haproxy/template.py

main/haproxy: update to 3.2.4

---

user/lf/template.py

user/lf: update to 37

---

user/xwayland-satellite/template.py

just a simple version upgrade.
This version is required for niri integration.

user/xwayland-satellite: upgrade to 0.7

---

main/networkmanager-openvpn/patches/locale.patch
main/networkmanager-openvpn/template.py

main/networkmanager-openvpn: update to 1.12.3

---

user/spotify-player/template.py

user/spotify-player: update to 0.21.0

---

user/opentofu/template.py

user/opentofu: update to 1.10.5

---

user/amdgpu_top/template.py

Update `amdgpu_top` to its last version: 0.11.0

user/amdgpu_top: update to 0.11.0

---

main/aardvark-dns/template.py

main/aardvark-dns: update to 1.16.0

---

user/forgejo/template.py

user/forgejo: update to 12.0.3

---

user/hcloud/template.py

user/hcloud: update to 1.52.0

---

user/syncthing/template.py

user/syncthing: update to 2.0.9

---

main/libvidstab/template.py

Do not remove previously defined configure_args

main/libvidstab: fix build on x86_64

---

user/daq/template.py

- **user/python-cachetools: update to 6.2.0**
- **user/daq: update to 3.0.21**

user/daq: update to 3.0.21

---

user/forgejo/template.py

user/forgejo: update to 12.0.4

---

user/agate/template.py

user/agate: update to 3.3.19

---

main/zathura/template.py

main/zathura: update to 0.5.13

---

user/syncthing/template.py

user/syncthing: update to 2.0.10

---

user/miniserve/template.py

user/miniserve: update to 0.32.0

---

user/curtail/template.py

user/curtail: update to 1.13.0

---

user/newsflash/template.py

user/newsflash: update to 4.1.4

---

main/haproxy/files/haproxy
main/haproxy/files/haproxy.cfg
main/haproxy/patches/readiness.patch
main/haproxy/template.py

updated dinit readiness patch for v3.2.6, updated documentation link

main/haproxy: update to 3.2.6

---

user/tuba/template.py

user/tuba: update to 0.10.2

---

main/certbot/template.py
main/python-acme/template.py

main/certbot main/python-acme: update to 5.0.0

---

main/openvpn/template.py

main/openvpn: update to 2.6.15

---

user/lf/template.py

user/lf: update to 38

---

user/go-task/template.py

user/go-task: update to 3.45.4

---

user/blanket/template.py

user/blanket: update to 0.8.0

---

main/borg/template.py

Added man pages to the borg package.

main/borg: added man pages

---

main/yt-dlp/template.py

main/yt-dlp: update to 2025.09.26

---

user/hcloud/template.py

user/hcloud: update to 1.53.0
