chimera-linux/cports

- cbuild/hooks/do_fetch/00_distfiles.py
I ran into an issue during bootstrapping where some packages hosted on savannah were failing to download. I made this change to help see why they were failing. Here's an example of the output with this small change made (the new part is the warning on line 2):
```
=> acl-2.3.1-r1: fetching distfile 'acl-2.3.1.tar.gz'...
=> WARNING: acl-2.3.1-r1: error fetching 'acl-2.3.1.tar.gz': HTTP Error 403: Forbidden
=> acl-2.3.1-r1: failed to fetch 'acl-2.3.1.tar.gz'
=> A failure has occured!
Traceback (most recent call last):
[snip]
cbuild.core.template.PackageError
```
I eventually solved the issue by changing the `nongnu` entry in `sites.py` to use one of the alternate URL suggested in the footer of the downloads page on Savannah ([for example](http://download.savannah.nongnu.org/releases/acl/)) …
> cbuild: report fetch exceptions

- cbuild/hooks/do_fetch/00_distfiles.py
rstrip remove characters, we need to remote a string.
fix "PYPI_SITE" => "pyp"
> cbuild distfile: fix discard of _SITE

- bootstrap.sh
Fixes https://github.com/chimera-linux/cports/issues/42
tested with x86_64 : bootstrap (stage0) is starting now.
> bootstrap.sh: update to newer x86_64 and aarch64 rootfs

- main/pkgconf/template.py
usual way is that `usr/share/aclocal/pkg.m4` is provided by the "main" pkgconf package.
if not, GNU automake/autoconf will generate configure script with the following errors.
```
....
/builddir/tmux-3.2a/configure: 4957: PKG_PROG_PKG_CONFIG: not found
....
checking for working strtonum... no
checking for working reallocarray... yes
checking for working recallocarray... no
checking for library containing clock_gettime... none required
/builddir/tmux-3.2a/configure: 6015: Syntax error: newline unexpected (expecting ")")
=> A failure has occured!
```
> main/pkgconf: keep pkg.m4 in main package (not in -devel)

- main/fftw/template.py
fix "configure: error: SSE requires single precision".
follow voidlinux's packaging manifest.
> main/fftw: fix sse* support for x86_64

- main/base-cross/template.py
fix this:
```
$ ./cbuild pkg main/base-cross
...
=> base-cross-riscv64-0.1-r0: running post_install hook: 000_handle_modes...
=> base-cross-riscv64-0.1-r0: running post_install hook: 001_hardlinks...
=> base-cross-riscv64-0.1-r0: detecting hardlinks
=> base-cross-riscv64-0.1-r0: running post_install hook: 002_uncompress_manpages...
=> base-cross-riscv64-0.1-r0: running post_install hook: 003_remove_misc...
=> base-cross-riscv64-0.1-r0: running post_install hook: 004_remove_libtool_archives...
=> base-cross-riscv64-0.1-r0: running post_install hook: 005_remove_perl_files...
=> base-cross-riscv64-0.1-r0: running post_install hook: 006_remove_python_bytecode...
=> base-cross-riscv64-0.1-r0: running post_install hook: 007_strip_debug...
=> base-cross-riscv64-0.1-r0: running post_install hook: …
```
> main/base-cross: move brokenlinks into the right subpkgs

- main/pciutils/template.py
without, linting fails : `/usr/man` is not allowed for man pages.
> main/pciutils: fix man page localization

- src/cbuild/core/dependencies.py
I managed to encounter this error branch but there was no output. It turned out that the error output from `apk` was on stdout. This PR prints std output as well if `apk` fails.
> cbuild: include stdout in message if apk call fails

- main/libpulse/libpulse
- main/libsoup/libsoup
- main/lvm2/lvm2.post-upgrade
Encountered while running some `grep -r` from Chimera on this repo:
```
grep: ./main/device-mapper/lvm2.post-upgrade: Symbolic link loop
grep: ./main/device-mapper-devel/lvm2.post-upgrade: Symbolic link loop
grep: ./main/libpulse-devel/libpulse: Symbolic link loop
grep: ./main/libpulse-progs/libpulse: Symbolic link loop
grep: ./main/libpulse/libpulse: Symbolic link loop
grep: ./main/libsoup-devel/libsoup: Symbolic link loop
grep: ./main/libsoup/libsoup: Symbolic link loop
grep: ./main/lvm2/lvm2.post-upgrade: Symbolic link loop
```
> main: Fix symbolic link loops

- src/cbuild/util/cargo.py
I don't think the cargo check method is used in the current ports tree but I ran into this error when creating a Rust package:
```
TypeError: Cargo._invoke() takes 10 positional arguments but 11 were given
```
This PR fixes the call to `Cargo._invoke`.
> cbuild: fix cargo check method

- src/cbuild/hooks/pre_pkg/001_runtime_deps.py
more of a proposal than "this is how it should be"
but I just spend hunting for a bit where a auto-dep came from, so display the path to the symlink itself
> cbuild: show the source of a symlink when creating auto-deps

- src/cbuild/util/meson.py
Fixes the following warning during meson configure stage (which has apparently been [emitted since meson `0.64.0`](https://wiki.archlinux.org/title/Meson_package_guidelines#Using_meson_binary_directly)):
```
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```
> cbuild: meson: explicitly call setup command

- main/console-setup/update.py
- main/cryptsetup-scripts/update.py
- main/initramfs-tools/update.py
- src/cbuild/core/update_check.py
Noticed this while packaging [`minicom`](https://salsa.debian.org/minicom-team/minicom) which I can also confirm this works for out of the box without need for `update.py` overrides :)
> Working update-check for Debian Salsa URLs

- main/ibus/patches/sticky-keys-fix.patch
- main/ibus/template.py
Without this fix, quite a few games will end up with "stuck" controls, e.g. you press W, and the game will act as if you're holding W unless you press W again.
mostly saw it in Apex Legends, but starting playing control and it kept happening there at a way higher frequency (once every 1-2minutes, instead of Apex's once every 30min)
with this fix applied, I just played Control for about ~3-4 hours without any stuck controls
> main/ibus: add fix for keys getting stuck in x11 applications (read: games)

- contrib/autoconf-archive/template.py
- contrib/powertop/template.py
This PR adds powertop and autoconf-archive, which it requires as a build dependency.
These packages were authored and will be maintained by stbk; I am creating the PR for her since she does not have a GitHub account and will do so for future PRs. We hope this is acceptable.
As with my PL PR, this was tested and works on x86. (And this time, it's properly formatted from the get-go...)
> Add powertop (2.15) and dependencies

- contrib/zoxide/template.py
- src/cbuild/util/cargo.py
Adds a package for zoxide.
Since zoxide already had a `.cargo/config.toml` in the project dir, the code for configuring vendoring sources threw an error.
I modified it to append to the file instead, which felt like the right approach and fixes this issue.
> Add zoxide (0.9.1)

- contrib/extra-cmake-modules/template.py
- contrib/prismlauncher/template.py
- contrib/qt6-qt5compat-devel
- contrib/qt6-qt5compat/template.py
- contrib/qt6-qt5compat/update.py
This PR adds PrismLauncher, along with 2 build dependencies it needed (qt6-5compat, extra-cmake-modules).
This is my first PR, so I hope I got the templates right, especially since I wasn't sure of a good way to specify the Java installation for PL.
It builds and runs fine on x86; it should too on ARM and PPC but I was unable to test it due to not having any hardware available.
> Add Prism Launcher (7.0) and dependencies

- main/bluez/files/bluetoothd
- main/bluez/template.py
There was an extra 'o' in the directory name preventing it from starting.
> Fix bluetoothd service file

- main/imagemagick/template.py
The module `.la` files were being removed so none of the imagemagic commands were working.
> main/imagemagick: set keeplibtool on libmagick

- contrib/ripgrep/patches/0001-remove-jemalloc.patch
- contrib/ripgrep/template.py
I patched out some code that used jemalloc on 64-bit musl since the `jemalloc-sys` crate isn't building on Chimera and shouldn't be necessary since we're using Scudo anyway.
> contrib/ripgrep: new package (13.0.0)

- main/xcb-util-wm/template.py
configure says it's missing xcb-macros
and also xcb_ewmh.h is currently empty because of what looks like some redirecting shenanigans bmake doesn't like
> xcb-util-wm: fix empty xcb_ewmh.h by using gmake, add missing dependency

- contrib/fd/template.py
Template for `fd`. I have disabled the default cargo features:
- `use-jemalloc`: fails to build
- `completions`: this is unused
Only zsh completions are included as generating bash and fish completions requires invoking the built binary, which I assume will not work when cross-compiling.
I was a little unsure of the best way to pass `--no-default-features` to cargo. Setting `make_*_args` works for build and check but setting `make_install_args` overwrites the default behavior (of passing `--path .`), so I instead invoke `install` manually to preserve that default behavior.
> contrib/fd: new package (8.7.0)

- contrib/duperemove/template.py
Part 1 of 3 of tools for squishing Btrfs filesystems. I tried the package, and it works for me.
The license file says xxHash support is optional, but that doesn't seem to have been true since 2014.
> contrib/duperemove: new package (0.11.3)

- contrib/fdupes/template.py
Part 2 of 3 of tools for squishing Btrfs filesystems, though this one can be used for other purposes, too. I tried the package, and it works for me.
The license text is part of the README... I checked what other packages in cports do in that situation, and it looks like they just install the whole README to /usr/share/licenses, so I did that too.
> contrib/fdupes: new package (2.2.1)

- contrib/compsize/template.py
Part 3 of 3 of tools for squishing Btrfs filesystems. I tried the package, and it works for me.
Defining `do_install` seemed cleaner to me, but the make install rule could probably be coerced into working.
> contrib/compsize: new package (1.5)

- contrib/fonts-libertinus-otf/template.py
I like to write in Libertinus Serif, so here are the Libertinus fonts. The pkgdesc is taken from Arch Linux because the GitHub short description is just "The Libertinus font family."
> contrib/fonts-libertinus-otf: new package (7.040)

- contrib/duperemove/patches/dont-require-git.patch
- contrib/duperemove/template.py
`-std=gnu2x` is required for `[[maybe_unused]]`. I'll submit the Makefile patch upstream as well.
> contrib/duperemove: update to 0.12

- main/base-cbuild-host/template.py
Without Python as a dependency, the procedure documented in the documentation to install this package to pull in all of cbuild's dependencies is incorrect.
> main/base-cbuild-host: add python to dependencies

- src/cbuild/core/template.py
The existing error message below doesn't make much sense:
```
=> qemu-8.0.3-r0: ERROR: cannot be cross-compiled for True
```
Make it print the architecture of the target instead:
```
=> qemu-8.0.3-r0: ERROR: cannot be cross-compiled for aarch64
```
> cbuild: print arch which pkg can't be cross-compiled for

- contrib/qemu-user/template.py
- contrib/qemu/patches/fix-brk0.patch
This fixes running practically anything on an older musl env like Void Linux aarch64 under x86_64 host; the following is an example test:
```
fetch https://repo-default.voidlinux.org/live/current/void-aarch64-musl-ROOTFS-20230628.tar.xz
mkdir rootfs && tar xf void-aarch64-musl-ROOTFS-20230628.tar.xz -C rootfs && doas chroot rootfs /bin/ls
```
> contrib/qemu-user: page-align initial brk(0)

- contrib/wl-clipboard/template.py
I marked cfi as not enabled as the tool crashes with Illegal instruction when enabled.
Is there a way to capture optional dependencies? Looking through the docs and templates it appears not. `wl-clipboard` is an optional dependency of Neovim. When present it enables yank/paste from the system clipboard. `wl-clipboard` itself has [optional runtime dependencies](https://github.com/bugaevc/wl-clipboard/blob/master/BUILDING.md) on `xdg-utils` and `/etc/mime.types` (doesn't look like we have a package providing that so far).
> contrib/wl-clipboard: new package (2.2.0)

- main/lldb/template.py
16.x removed this upstream and no longer uses it
> main/lldb: remove dep on python-six

- contrib/foot/template.py
https://codeberg.org/dnkl/foot/releases/tag/1.15.0  
https://codeberg.org/dnkl/foot/releases/tag/1.15.1  
https://codeberg.org/dnkl/foot/releases/tag/1.15.2
there's utmp-backend options now, but they're not that relevant
> contrib/foot: update to 1.15.2

- contrib/nicotine-plus/template.py
- contrib/python-semidbm/template.py
semidbm is some ancient thing, but the other alternative is python-gdbm by adding gdbm to python itself (it's technically splittable but iirc the .so still links it so i don't think it's possible with -z now (?))
> contrib/nicotine-plus: new package (3.2.9)

- src/cbuild/util/golang.py
-v prints each module that gets compiled, -x spams the fuck out of the logs with a thousand lines of output for anything
> cbuild: use -v instead of -x for go build

- contrib/cvise/template.py
- contrib/python-pebble/template.py
this links libclang/libllvm, but is actively maintained and is already 17-compatible on master with minor changes, so it doesn't block the toolchain
> contrib/cvise: new package (2.8.0)

- contrib/alacritty-terminfo
- contrib/alacritty/template.py
This is a continuation of #204 I've bumped it to the latest release, slimmed down the dependencies, added man pages and terminfo, and updated it to use `install_completion`.
I'm having trouble with cross-compilation though. I'm getting a lot of errors such as these but I'm not sure what's different with this codebase to other Rust ones I've packaged:
```
error[E0463]: can't find crate for `core`
|
= note: the `aarch64-chimera-linux-musl` target may not be installed
= help: consider downloading the target with `rustup target add aarch64-chimera-linux-musl`
error[E0463]: can't find crate for `compiler_builtins`
For more information about this error, try `rustc --explain E0463`.
error[E0463]: can't find crate for `core`
--> /builddir/alacritty-0.12.2/vendor/lazy_static/src/inline_lazy.rs:8:1 …
```
> contrib/alacritty: new package (0.12.2)

- contrib/intel-gmmlib-devel
- contrib/intel-gmmlib/template.py
- contrib/intel-gmmlib/update.py
- contrib/intel-media-driver-devel
- contrib/intel-media-driver/template.py
- contrib/intel-media-driver/update.py
mostly just pulled from https://github.com/chimera-linux/cports/pull/153, since this is needed for vaapi decode, the rest is for the "encode" capabilities
> contrib/intel-media-driver: new package (23.3.1)

- contrib/zoxide/patches/remove-gnu-ls-arg.patch
- contrib/zoxide/template.py
Update to the new release https://github.com/ajeetdsouza/zoxide/releases/tag/v0.9.2
I also fixed the interactive preview. It was passing an unsupported argument to `ls` resulting in the following in the preview window:
```
│ ┌───────────────────────────────────────────────────────────────────────────────────────────────────┐│
│ │ ls: unrecognized option: group-directories-first                                                  ││
│ │ usage: ls [-ABCFGHILPRSTabcdfghiklmnpqrstuvwxy1,] [--color=when] [-D format] [file ...]           ││
│ │                                                                                                   ││
│ └───────────────────────────────────────────────────────────────────────────────────────────────────┘│
```
> contrib/zoxide: update to 0.9.2

- contrib/fonts-tex-gyre-otf/template.py
- contrib/fonts-tex-gyre-otf/update.py
This collection of fonts provides well designed alternatives to some common proprietary fonts/base PostScript fonts such as Helvetica, Palatino, Times, and Century Schoolbook.
~~Had to disable the update check, don't think there's a way to automate it.~~
> contrib/fonts-tex-gyre-otf: new package (2.501)

- main/python-trove-classifiers/template.py
https://github.com/pypa/trove-classifiers/commit/5aca2a11c27623ff3a7b2de4e53daf3aaedfc61d
> main/python-trove-classifiers: update to 2023.8.7

- contrib/qbittorrent/template.py
- contrib/qbittorrent/update.py
what doesn't work (daemon, not here anymore):
- daemon doesn't actually start:
`alert : Could not create required directory '/.cache/qBittorrent'`
the working-dir chroots to /var/lib/qbittorrent and i assume something goes wrong here with the mkdir from the daemon itself after (it uses cwd as home)..
- the group is on the wrong package
the _qbittorrent user/group should only be on -nox, but it doesn't work to put it there with self.system_users, and you get `chown: _qbittorrent: illegal group name`
> contrib/qbittorrent: new package (4.5.4)

- contrib/notmuch/template.py
> contrib/notmuch: disable cfi

- main/vala/template.py
https://gitlab.gnome.org/GNOME/vala/-/blob/2a0ae432b97f6594f859b6fb5b859565457388a7/NEWS
> main/vala: update to 0.56.12

- main/pipewire/template.py
https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.78
> main/pipewire: update to 0.3.78

- main/gtk4/update.py
Confirmed working (as far as I can tell) with `pkgver = "4.0"`:
```
main/gtk4: 4.0 -> 4.6.9
main/gtk4: 4.0 -> 4.8.3
main/gtk4: 4.0 -> 4.10.0
main/gtk4: 4.0 -> 4.10.1
main/gtk4: 4.0 -> 4.10.2
main/gtk4: 4.0 -> 4.10.3
main/gtk4: 4.0 -> 4.10.4
main/gtk4: 4.0 -> 4.10.5
main/gtk4: 4.0 -> 4.12.0
```
Void also does something similar but in reverse (matching `pattern` instead of `ignore`): https://github.com/void-linux/void-packages/blob/master/srcpkgs/gtk4/update
> main/gtk4: make ignore pattern more concise and future-proof

- contrib/rust-analyzer/template.py
rust-analyzer wasn't working for me with Neovim or Helix. It would start but nearly immediately exit with no reason. Eventually I was able to capture it in the debugger:
```
* thread #10, name = 'Worker', stop reason = signal SIGABRT
* frame #0: 0x00007f00cb69a137 ld-musl-x86_64.so.1`__restore_sigs [inlined] __syscall4(n=14, a1=2, a2=139641312158528, a3=0, a4=8) at syscall_arch.h:38:2
frame #1: 0x00007f00cb69a123 ld-musl-x86_64.so.1`__restore_sigs(set=0x00007f00c6cea340) at block.c:43:2
frame #2: 0x00007f00cb69a2d3 ld-musl-x86_64.so.1`raise(sig=6) at raise.c:11:2
frame #3: 0x00007f00cb65823e ld-musl-x86_64.so.1`abort at abort.c:11:2
frame #4: 0x000055a0d0719e27 rust-analyzer`panic_abort::__rust_start_panic::abort::hf5ec61c6639c7f8d (.llvm.2600056918071265335) + 7
frame #5: …
```
> contrib/rust-analyzer: use unwind panic strategy

- contrib/ncdu/template.py
It is required to make the `--exclude-kernfs` argument available:
```
$ ncdu --exclude-kernfs
The --exclude-kernfs flag is currently only supported on Linux.
```
> contrib/ncdu: build against linux-headers

- main/vala/template.py
https://gitlab.gnome.org/GNOME/vala/-/blob/66dd0937d8b9f29c801c9e7340a404ae4bbfdd1f/NEWS
> main/vala: update to 0.56.13

- main/glib/template.py
https://gitlab.gnome.org/GNOME/glib/-/blob/2218ee6f7e043c605bcc7ab95378e92ad48564f4/NEWS
> main/glib: update to 2.76.5

- contrib/benchmark/template.py
https://github.com/google/benchmark/releases/tag/v1.8.3
> contrib/benchmark: update to 1.8.3

- main/at-spi2-core/template.py
https://gitlab.gnome.org/GNOME/at-spi2-core/-/blob/ebfda3a63fc351f977d5428b1e7e1979c8edb5c5/NEWS
> main/at-spi2-core: update to 2.48.4

- contrib/go/template.py
https://go.dev/doc/devel/release#go1.21.minor
> contrib/go: update to 1.21.1

- main/glibmm/template.py
https://gitlab.gnome.org/GNOME/glibmm/-/blob/9c376086c1921dcdd99445aef5e7334c652cc77d/NEWS
> main/glibmm: update to 2.78.0

- main/graphviz/template.py
- main/imagemagick/template.py
- main/vala/template.py
https://gitlab.com/graphviz/graphviz/-/blob/e0548e996d38d1f4e20aa73c8bf83fc852d973fb/CHANGELOG.md  
like in 8 theres a bunch of breaking changes but no soname bumps, even though symbols are removed
> main/graphviz: update to 9.0.0

- main/python-urllib3/template.py
https://github.com/urllib3/urllib3/releases/tag/v2.0.5
> main/python-urllib3: update to 2.0.5

- main/python-typing_extensions/template.py
https://github.com/python/typing_extensions/releases/tag/4.8.0
> main/python-typing_extensions: update to 4.8.0

- main/python-trove-classifiers/template.py
https://github.com/pypa/trove-classifiers/releases/tag/2023.9.19
> main/python-trove-classifiers: update to 2023.9.19

- contrib/python-cryptography/template.py
https://github.com/pyca/cryptography/blob/fc11bce6930e591ce26a2317b31b9ce2b3e25512/CHANGELOG.rst
> contrib/python-cryptography: update to 41.0.4

- src/cbuild/apk/cli.py
when /etc/apk/interactive is touched on the host, every apk call by cbuild prompts the user, but for cbuild specifically we don't want apk to give interactive prompts
> cbuild: explicitly disable apk interactivity

- main/python-charset-normalizer/template.py
https://github.com/Ousret/charset_normalizer/releases/tag/3.3.0
> main/python-charset-normalizer: update to 3.3.0

- main/enchant/template.py
https://github.com/AbiWord/enchant/releases/tag/v2.6.0  
https://github.com/AbiWord/enchant/releases/tag/v2.6.1
> main/enchant: update to 2.6.1

- contrib/wlsunset/template.py
> contrib/wlsunset: disable int

- contrib/solaar/template.py
To use the program as non-root user it needs udev rules which were already installed but in a "useless" location from distro perspective.
> contrib/solaar: update to 1.1.10, properly install udev rules

- main/python-urllib3/template.py
https://github.com/urllib3/urllib3/releases/tag/2.0.6
> main/python-urllib3: update to 2.0.6

- main/gettext/template.py
https://savannah.gnu.org/news/?id=10520
> main/gettext: update to 0.22.3

- main/pipewire/template.py
https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.81
> main/pipewire: update to 0.3.81

- contrib/hyperfine/template.py
https://github.com/sharkdp/hyperfine/releases/tag/v1.18.0
> contrib/hyperfine: update to 1.18.0

- main/linux-headers/template.py
this allows using new defines for software that makes use of them. one example is https://codeberg.org/dnkl/foot/commit/61eb56dfda605427156b52d019be4bf5ce84c3aa ; compiling with 6.3+ headers would allow it to be set, but is still backwards compatible because unknown flags are just ignored.
in general, the headers are backwards compatible. having older headers doesn't improve compatibility with older kernels; it only prevents applications from using newer features/defines, without benefit to people using the older LTS series (it works either way), and with a negative to people using latest stable (loss of potential feature).
> main/linux-headers: update to 6.5.5

- contrib/qt6ct/template.py
Using qt6ct to theme qt programs results fails to apply themes with this error
`qt6ct: qt6ct is compiled against incompatible Qt version (6.5.3).`
Rebuilding against qt 6.6 fixes this.
> contrib/qt6ct: rebuild for qt6 6.6

- main/shared-mime-info/patches/sep.patch
- main/shared-mime-info/template.py
https://gitlab.freedesktop.org/xdg/shared-mime-info/-/releases/2.3
> main/shared-mime-info: update to 2.3

- main/libnotify/template.py
https://gitlab.gnome.org/GNOME/libnotify/-/blob/3f2882d1b49996748cf1b0a8f7862b2592d8042d/NEWS
> main/libnotify: update to 0.8.3

- main/xdg-desktop-portal/files/portals.conf
- main/xdg-desktop-portal/template.py
see https://github.com/void-linux/void-packages/commit/b4c404aac0af3ced08671a8840cd261198689cef  
this is a default fallback for when ${XDG_CURRENT_DESKTOP}-portals.conf doesn't exist, so it's a fallback so at least something works until further configured later
> main/xdg-desktop-portal: add a default portal configuration

- contrib/android-tools/template.py
- contrib/android-udev-rules/template.py
Brings in `adb`, `fastboot` and friends normally required for dealing with development and flashing of Android devices.
> Android tools + dependencies

- contrib/tailscale/files/tailscaled
- contrib/tailscale/template.py
- src/cbuild/core/profile.py
- src/cbuild/util/golang.py
and more golang flag stuff, similar to [what other distros do](https://shibumi.dev/posts/hardening-executables/) — actually ideally we'd also handle annoying go ldflags thing to be able to pass both `linkmode=external` and per-package stuff like those `-X` defines; not sure what the right way to do it would be though. or maybe I shouldn't touch any of that stuff…
> contrib/tailscale: new package (1.50.1)

- main/libheif/template.py
also builds the gdk-pixbuf loader
> main/libheif: update to 1.17.0

- main/python-trove-classifiers/template.py
https://github.com/pypa/trove-classifiers/releases/tag/2023.10.17  
https://github.com/pypa/trove-classifiers/releases/tag/2023.10.18
> main/python-trove-classifiers: update to 2023.10.18

- contrib/qt6-qt5compat/template.py
Additionally drop `/usr/tests` which was [already present in the package](https://pkgs.chimera-linux.org/contents?path=/usr/tests/*&repo=contrib).
> contrib/qt6-qt5compat: ship Qt5Compat.GraphicalEffects QML module

- main/ostree/template.py
https://github.com/ostreedev/ostree/releases/tag/v2023.7
> main/ostree: update to 2023.7

- contrib/greetd/files/greetd
- contrib/greetd/files/greetd.pam
- contrib/greetd/greetd.post-deinstall
- contrib/greetd/greetd.post-install
- contrib/greetd/patches/config.patch
- contrib/greetd/template.py
- contrib/tuigreet/template.py
This is my first time attempting to upstream a package, hopefully I get this right.
This MR also provides a contrib/tuigreet package, which can be used as a greeter for greetd. I also don't know if I got the dinit service right, but it works locally.
Both packages have been tested, and built on x86_64, as it is the only hardware I have. All tier 1 and tier 3 architectures cross compile successfully.
> contrib/greetd: new package (0.9.0)

- main/ruby/template.py
ruby's optional (runtime-manually-enabled) fancy new yjit support, which it seems is not very hard to build, and doesn't even need cargo..
this probably adds another issue for fixing `!cross`, but aside from that doesn't seem too bad to have
on x86_64, this is 30->32mb
> main/ruby: add yjit support

- main/xdg-desktop-portal-gtk/template.py
versioning scheme changed in https://discourse.gnome.org/t/xdg-desktop-portal-gtk-versioning-scheme-change/17698/1  
https://github.com/flatpak/xdg-desktop-portal-gtk/releases/tag/1.15.0
> main/xdg-desktop-portal-gtk: update to 1.15.0

- main/nghttp2/template.py
https://github.com/nghttp2/nghttp2/releases/tag/v1.58.0
> main/nghttp2: update to 1.58.0

- main/python-charset-normalizer/template.py
https://github.com/Ousret/charset_normalizer/releases/tag/3.3.1
> main/python-charset-normalizer: update to 3.3.1

- main/opusfile/template.py
crashes in deadbeef when loading a .ogg  
---
```
(lldb) bt
* thread #1, name = 'deadbeef-main', stop reason = signal SIGILL: illegal instruction operand
* frame #0: 0x00007fffe73f5a13 libopusfile.so.0`op_test_callbacks [inlined] op_open1(_of=0x00007fffe6106f30, _stream=0x00007fffecc0a840, _cb=0x00007fffe7985de0, _initial_data=0x0000000000000000, _initial_bytes=0) at opusfile.c:0
frame #1: 0x00007fffe73f5a11 libopusfile.so.0`op_test_callbacks(_stream=0x00007fffecc0a840, _cb=0x00007fffe7985de0, _initial_data=0x0000000000000000, _initial_bytes=0, _error=0x00007fffffff5360) at opusfile.c:1608:9
frame #2: 0x00007fffe73f5c2f libopusfile.so.0`op_open_callbacks(_stream=<unavailable>, _cb=<unavailable>, _initial_data=<unavailable>, _initial_bytes=<unavailable>, _error=<unavailable>) at …
```
> main/opusfile: disable cfi

- contrib/audacity/patches/opusfile.patch
- contrib/audacity/template.py
- contrib/rapidjson/patches/disable-bad-flags.patch
- contrib/rapidjson/patches/no-vendor-gtest.patch
- contrib/rapidjson/template.py
the new opus import/export doesn't actually work and just fails to load mod-opus with ENOTTY. strace doesn't say anything interesting because every single module load does ioctl TIOCGWINSZ on the cfg file fd which fails with that, but only mod-opus fails to load..
> contrib/audacity: update to 3.4.0

- main/chrony/template.py
There seems to be a new upstream URL with the old one (https://download.tuxfamily.org/chrony/) currently having an expired cert.
> main/chrony: fix update-check

- main/iso-codes/template.py
This brings in the missing `.json` (such as `iso_3166-1.json`) and locale files which [`ki18n`](https://github.com/JamiKettunen/cports/blob/plasma6/contrib/ki18n/template.py) tests depend on for example.
Additionally there I needed `iso-codes-locale` instead of just `iso-codes` as otherwise I saw the following (but I suppose that's ok perhaps?)
```
FAIL!  : KCountrySubdivisionTest::testLookup() Compared values are not the same
Actual   (s.name())                : "Wien"
Expected (QStringLiteral("Vienne")): "Vienne"
Loc: [../autotests/kcountrysubdivisiontest.cpp(50)]
```
Fixes https://github.com/chimera-linux/cports/issues/667.
> main/iso-codes: rebuild with gmake

- main/gtkmm/update.py
Will also ignore e.g. future unstable 4.21 release. Seeing bff9df418 reminded me of #413:
```
Checking for updates: gtkmm=4.0
Found update.py, using overrides...
Adding 'https://gitlab.gnome.org/GNOME/gtkmm/-/tags' for version check...
Fetching 'https://gitlab.gnome.org/GNOME/gtkmm/-/tags' for version checks...
Checking found version: 3.24.5
Checking found version: 3.24.6
Checking found version: 3.24.7
Checking found version: 3.24.8
Checking found version: 4.0.2
Checking found version: 4.2.0
Checking found version: 4.4.0
Checking found version: 4.6.0
Checking found version: 4.6.1
Checking found version: 4.7.1
Ignoring version '4.7.1' (due to '4.*[13579].*')
Checking found version: 4.8.0
Checking found version: 4.9.1
Ignoring version '4.9.1' (due to '4.*[13579].*')
Checking found version: …
```
> main/gtkmm: sync ignore pattern with gtk4

- contrib/netavark/template.py
the project makefile install rule puts it in LIBEXECPODMAN; this is where other tools that utilise this like buildah expect to find it too.
> contrib/netavark: install to usr/libexec/podman instead

- main/lcms2/update.py
Not sure what happened here but perhaps the recently tagged 2.16 release candidate broke it? There's also an incorrectly named [`lcm2.16rc1`](https://github.com/mm2/Little-CMS/releases/tag/lcm2.16rc1) tag as well on top of [`lcms2.16rc1`](https://github.com/mm2/Little-CMS/releases/tag/lcms2.16rc1)
Either way this seems to work but I'm not sure it's the best solution:
```
Checking for updates: lcms2=2.15
Found update.py, using overrides...
Adding 'https://littlecms.com' for version check...
Adding 'https://github.com/mm2/Little-CMS/releases/download/lcms2.15/' for version check...
Fetching 'https://littlecms.com' for version checks...
Fetching 'https://github.com/mm2/Little-CMS/tags' for version checks...
Checking found version: 2.13
Checking found version: 2.13.1
Checking found version: …
```
> main/lcms2: fix update-check

- main/ucode-intel/template.py
https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20231114
> main/ucode-intel: update to 20231114

- main/libheif/template.py
https://github.com/strukturag/libheif/releases/tag/v1.17.5  
https://github.com/strukturag/libheif/releases/tag/v1.17.4
> main/libheif: update to 1.17.5

- Usage.md
Still has the patched musl SONAME presumably which prevents using it for bootstrapping atm.
https://pkgs.alpinelinux.org/package/edge/main/x86_64/libc++-dev (and https://pkgs.alpinelinux.org/package/v3.18/main/x86_64/libc++-dev on current stable)
> usage: alpine repos now have libc++ for bootstrapping

- main/python-trove-classifiers/template.py
https://github.com/pypa/trove-classifiers/releases/tag/2023.11.22
> main/python-trove-classifiers: update to 2023.11.22

- contrib/sbctl/patches/use-llvm-objcopy.patch
- contrib/sbctl/template.py
I use this tool to manage my Secure Boot setup.
Default path for keys and database files is `/usr/share/secureboot`, some distros change this to `/etc/secureboot`.
> contrib/sbctl: new package (0.12)

- contrib/go/template.py
https://go.dev/doc/devel/release#go1.21.minor
> contrib/go: update to 1.21.4

- contrib/webp-pixbuf-loader/patches/update-webp-dependency-constraint.patch
- contrib/webp-pixbuf-loader/template.py
0.2.5 has been tagged with one commit over 0.2.4 https://github.com/aruiz/webp-pixbuf-loader/commit/f7253133ba0902afbe65bd2482f3b9e1a84b58fb (for the webp CVE) but it's broken. It requires webp **>** 1.3.2 when it should be **>=**. It [has been fixed](https://github.com/aruiz/webp-pixbuf-loader/commit/834657c8) on the main branch. I set it to ignore 0.2.5 for now
> contrib/webp-pixbuf-loader: new package (0.2.5)

- main/ostree/template.py
The Fedora flatpak repository at least appears to need support for parsing tar files directly.
> main/ostree: build with libarchive support

- contrib/scc/template.py
- src/cbuild/core/profile.py
Updates scc and drops `-mod=readonly` as discussed in #999.
Fixes #999
> contrib/scc: update to 3.2.0

- contrib/mako/template.py
jq is used for `makoctl menu` and `makoctl mode`. However, makoctl checks for the presence of jq. Should I remove jq from dependencies?
> contrib/mako: new package (1.8.0)

- contrib/fonts-noto-emoji-ttf/files/66-noto-color-emoji.conf
- contrib/fonts-noto-emoji-ttf/template.py
The fontconfig is taken from [Arch](https://gitlab.archlinux.org/archlinux/packaging/packages/noto-fonts-emoji/-/blob/main/66-noto-color-emoji.conf?ref_type=heads)
> contrib/fonts-noto-emoji-ttf: new package (2.042)

- main/readline/update.py
This has been broken for over a week now with the website seemingly having some issues with the cert:
```
$ curl -v https://tiswww.cwru.edu/php/chet/readline/rltop.html
*   Trying 129.22.12.56:443...
* Connected to tiswww.cwru.edu (129.22.12.56) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html
curl failed to verify the legitimacy of …
```
> main/readline: fix update-check

- main/glib/template.py
https://gitlab.gnome.org/GNOME/glib/-/releases/2.78.2  
https://gitlab.gnome.org/GNOME/glib/-/releases/2.78.3
> main/glib: update to 2.78.3

- main/ostree/template.py
https://github.com/ostreedev/ostree/releases/tag/v2023.8
> main/ostree: update to 2023.8

- contrib/android-udev-rules/template.py
https://github.com/M0Rf30/android-udev-rules/releases/tag/20231207
> contrib/android-udev-rules: update to 20231207

- contrib/python-cryptography/template.py
https://github.com/pyca/cryptography/blob/4054596afc6f2b6cfcc54f56c35c34e0e429cb66/CHANGELOG.rst
> contrib/python-cryptography: update to 41.0.7

- contrib/python-pyclip-wayland
- contrib/python-pyclip-x11
- contrib/python-pyclip/template.py
- contrib/xclip/template.py
If someone has an idea about the failing tests for `python-pyclip` here's the log: https://paste.c-net.org/4xpexgjmyico
I would've liked to make `python-pyclip-(wayland|x11)` only install if you had some Wayland desktop / Xorg or Xwayland but I don't think that's really feasible and doesn't really matter anyway. If someone doesn't want one they can e.g. `apk add '!python-pyclip-x11'` or whatever
> xclip & pyclip

- main/nss/template.py
https://firefox-source-docs.mozilla.org/security/nss/releases/nss_3_95.html
> main/nss: update to 3.95

- contrib/netavark/template.py
https://github.com/containers/netavark/releases/tag/v1.9.0
> contrib/netavark: update to 1.9.0

- contrib/fonts-noto-sans-cjk-extra
- contrib/fonts-noto-sans-cjk-extra-otf
- contrib/fonts-noto-sans-cjk-extra-ttf
- contrib/fonts-noto-sans-cjk-otf
- contrib/fonts-noto-sans-cjk-ttf
- contrib/fonts-noto-sans-cjk/files/70-noto-sans-cjk.conf
- contrib/fonts-noto-sans-cjk/template.py
- contrib/fonts-noto-sans-cjk/update.py
Sans version
- Same subpackaging as #1006 
- fontconfig from Arch
> contrib/fonts-noto-sans-cjk: new package (2.004)

- contrib/fonts-noto-serif-cjk-extra
- contrib/fonts-noto-serif-cjk-extra-otf
- contrib/fonts-noto-serif-cjk-extra-ttf
- contrib/fonts-noto-serif-cjk-otf
- contrib/fonts-noto-serif-cjk-ttf
- contrib/fonts-noto-serif-cjk/files/70-noto-serif-cjk.conf
- contrib/fonts-noto-serif-cjk/template.py
- contrib/fonts-noto-serif-cjk/update.py
Serif version
- Same subpackaging as #1006 
- fontconfig from Arch
- (Sans version on #1007)
> contrib/fonts-noto-serif-cjk: new package (2.002)

- contrib/go/template.py
https://go.dev/doc/devel/release#go1.21.minor
> contrib/go: update to 1.21.5

- contrib/spice-vdagent/files/spice-vdagentd
- contrib/spice-vdagent/template.py
Tools to make interacting with Chimera Linux QEMU/KVM guests more integrated such as a shared bi-directional clipboard, drag & drop from host to guest etc.
GDM integration was dropped due to breaking launch of `spice-vdagent` user side daemon (via XDG autostart); should be looked into but imo nothing too major. A `spice-vdagent` user service may be added later after missing graphical support for user services is addressed.
Configuring `--with-session-info=systemd` allows for multi-user `spice-vdagent` to work at the cost of `elogind` dependency; without it (which is the state of this PR currently) only a single instance of the user side daemon can run / work with `spice-vdagentd` system service.
> contrib/spice-vdagent: new package (0.22.1)

- contrib/gnome-system-monitor/template.py
This is technically a core app however it would require bumping `gtkmm3.0` to main but I'm not sure if it's worth it (personally I'm against it as the next version will be gtk4 (ETA GNOME 46))
> contrib/gnome-system-monitor: new package (45.0.2)

- main/xdg-desktop-portal-gtk/template.py
xdg-desktop-portal-gtk crashes at runtime if this dependency is missing.
> main/xdg-desktop-portal-gtk: add missing depends

- main/evolution-data-server/template.py
- main/gnome-bluetooth/template.py
- main/gnome-control-center/patches/disable-broken-test.patch
- main/gnome-control-center/template.py
- main/gnome-disk-utility/template.py
- main/gnome-shell-extensions/template.py
- main/gnome-shell/template.py
- main/gnome-software/template.py
- main/mutter/template.py
- main/nautilus/template.py
- main/python-dbusmock/template.py
- main/webkitgtk/template.py
- main/webkitgtk4/template.py
- main/xdg-desktop-portal-gnome/template.py
https://gitlab.gnome.org/GNOME/gnome-bluetooth/-/blob/97ce880be9da545477162db10984d93989c39d25/NEWS  
https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/blob/66e2fa40a9f23fb1f653fac917c72e37e546289c/NEWS  
https://gitlab.gnome.org/GNOME/gnome-control-center/-/blob/88b0ab9204f30b78fbe9e15bfc3651d5842ca986/NEWS  
https://gitlab.gnome.org/GNOME/gnome-disk-utility/-/blob/5208914fa4f6deebfd502353b51eef3aee65d3ba/NEWS  
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/9c4a5897ab1a2d374e3e3de7fb195d47d4c422a6/NEWS  
https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/blob/b02e43d84cf7a1956d2d8cc77079a64cddef4d40/NEWS  
https://gitlab.gnome.org/GNOME/gnome-software/-/blob/7b9593d79958bcf0f1323f44fe72d11f6f4bdd06/NEWS  
https://gitlab.gnome.org/GNOME/mutter/-/blob/bedf8df88f41c34c9824dc …
> gnome bumps

- contrib/spice-vdagent/template.py
Both the daemon and client can crash each other upon exit when built with CFI: https://paste.c-net.org/519lq1pmlhda
> contrib/spice-vdagent: disable cfi

- contrib/weechat/patches/ruby-3.3.patch
- contrib/weechat/template.py
- main/ruby/template.py
https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/
> main/ruby: update to 3.3.0

- main/iputils/iputils.post-install
- main/iputils/iputils.post-upgrade
- main/iputils/template.py
https://github.com/iputils/iputils/releases/tag/20231222  
this also fixes EPERM on clockdiff because it needs +ep and not just +p (same as upstream script). the sys_nice isn't required it seems (works regardless) but it's what the upstream script does, so eh
> main/iputils: update to 20231222

- contrib/libhangul-devel
- contrib/libhangul-progs
- contrib/libhangul/patches/0001-Update-gettext-version.patch
- contrib/libhangul/template.py
- contrib/seogi/template.py
I need a wayland IME to test my compositor and this seemed like the easiest one to build/package :)
> contrib/seogi: new package (1.1.4)

- contrib/swww/template.py
The `swww-daemon` binary wasn't being installed when it needed to be
> contrib/swww: install needed binary

- contrib/git-branchless/template.py
- src/cbuild/util/cargo.py
--release removes debug assertions (making tests overall worse), and makes the test binaries built with lto, which takes longer even though --release can reuse ~some build artifacts instead of rebuilding the full graph
> cbuild: don't pass release to cargo test

- contrib/regreet/files/regreet.conf
- contrib/regreet/files/regreet.toml
- contrib/regreet/template.py
Adds an actual graphical greeter for greetd. Upstream provides a systemd-tmpfiles config, but it requires patching, so using our own seems more sane. regreet.toml is for elogind.
This would require wlroots compositor as well as some manual config. I didn't provide any of the upstream example configs nor did I add a compositor to depends. Should I?
> contrib/regreet: new package (1.1.1)

- contrib/frawk/patches/update-ahash.patch
- contrib/frawk/patches/update-crossbeam-channel.patch
- contrib/frawk/patches/update-libc.patch
- contrib/frawk/template.py
Although the package conditionally enables architecture-specific code, it always has a generic fallback, so I did not add the `archs` line.
> contrib/frawk: new package (0.4.7)

- main/power-profiles-daemon/template.py
powerprofilesctl needs this installed to work
> main/power-profiles-daemon: add python-gobject dependency

- contrib/cliphist/template.py
- contrib/gopass/template.py
I have stopped using Chimera Linux as I'm not very comfortable with the project relying on Github for code hosting (especially given the recent sourcehut outage), and Github being proprietary and all.
No hard feelings though and I hope Chimera Linux keeps going well.
So this just orphans my packages.
> Orphan packages

- contrib/senpai/patches/0001-Handle-empty-message-properly.patch
- contrib/senpai/template.py
this fixes a crash caused by a user attempting to send a message only containing a single space
> contrib/senpai: backport 1ad07b59 from upstream

- contrib/python-pytest-timeout/template.py
Package: https://github.com/pytest-dev/pytest-timeout
> contrib/python-pytest-timeout: new package (2.2.0)

- contrib/gnome-shell-extension-gsconnect/template.py
`gsconnect:components / ClipboardComponent` test fails with this error:
```
stderr:
(gjs:55): Gdk-CRITICAL **: 20:04:04.485: gdk_seat_get_keyboard: assertion 'GDK_IS_SEAT (seat)' failed
(test program exited with status code -5)
TAP parsing error: Too few tests run (expected 2, got 0)
```
Not quite sure how to fix it.
> contrib/gnome-shell-extension-gsconnect: new package (56)

- contrib/openjdk17/template.py
https://mail.openjdk.org/pipermail/jdk-updates-dev/2024-January/029089.html
> contrib/openjdk17: update to 17.0.10_p7

- contrib/chromium/patches/disable-dns_config_service.patch
- contrib/chromium/template.py
[ci skip]
https://chromereleases.googleblog.com/2024/01/stable-channel-update-for-desktop_16.html
> contrib/chromium: update to 120.0.6099.224

- contrib/python-blinker/template.py
Package: https://github.com/pallets-eco/blinker/
The last dependency before we can package a Flask.
> contrib/python-blinker: new package (1.7.0)

- contrib/android-tools/template.py
- contrib/mosh/template.py
- contrib/protobuf-c/template.py
- contrib/protobuf/template.py
Also make `mosh` use `gmake` due to strange build errors even on current `master` of cports without any of this, not sure if it's a `bmake` bug or what as it used to build previously.
> Protobuf 25.2

- contrib/htop/template.py
Also enable hardening. Didn't drop `configure_gen = []` as I couldn't figure out what caused:
```
/builddir/htop-3.3.0/configure: 11567: Syntax error: end of file unexpected (expecting "fi")
```
> contrib/htop: update to 3.3.0

- contrib/fish-shell/patches/0001-fix-mktemp-in-tests.patch
- contrib/fish-shell/template.py
fish has its own test target that should be used instead of just using ctest alone (see https://github.com/fish-shell/fish-shell/blob/3.7.0/cmake/Tests.cmake#L18)
Also removed `!int` hardening option as I wasn't able to reproduce the mentioned test failure.
> contrib/fish-shell: use correct check target

- contrib/pam_wrapper-devel
- contrib/pam_wrapper/template.py
Packaged this for `fprintd` tests, but couldn't get those working. `libsecret` 0.21.3 will use this package though for testing the PAM module added in the release, so might as well submit a PR.
> contrib/pam_wrapper: new package (1.1.5)

- contrib/mosh/template.py
- contrib/protobuf/template.py
- main/abseil-cpp/template.py
- main/webrtc-audio-processing/template.py
weirdly, both webrtc-audio-processing and libreoffice don't actually get a needed on libabsl anywhere (probably header-only use?). i skipped the libreoffice rebuild for that reason
> main/abseil-cpp: update to 20240116.0

- contrib/megatools/template.py
- contrib/megatools/update.py
Man pages aren't currently built as docbook2x is required and looks like a lot of work to package. I don't have plans to package it myself at the moment but thought I'd open this PR anyways in case it's acceptable to merge without man pages and to avoid duplicated effort if anyone else looks into packaging this software.
> contrib/megatools: new package (1.11.1)

- main/gnome-disk-utility/template.py
Fixes https://github.com/chimera-linux/cports/issues/1415.
> main/gnome-disk-utility: disable `vis` to fix changing LUKS passphrase

- contrib/yggdrasil/files/yggdrasil
- contrib/yggdrasil/files/yggdrasil.wrapper
- contrib/yggdrasil/template.py
- building and running this natively on aarch64
- building this natively on x86_64
- logs are stored by dinit properly
- detection whether config file exists and falling back to `-autoconf` works
- cross compiling from x86_64 to aarch64
```
=> yggdrasil-0.5.5-r0: running post_install hook: 007_strip_debug...
objcopy: error: SHT_STRTAB string table section [index 11] is non-null terminated
=> yggdrasil-0.5.5-r0: ERROR: failed to attach debug link to usr/bin/yggdrasilctl
```
> contrib/yggdrasil: new package (0.5.5)

- src/cbuild/build_style/waf.py
as seen [here](https://gitlab.com/ita1024/waf/-/blob/master/waflib/Tools/c_config.py#L211-214), waf reads `PKGCONFIG` from the environment instead of what cbuild sets, which is `PKG_CONFIG`
> cbuild: pass the right pkg-config path to waf

- main/cryptsetup/template.py
https://mirrors.edge.kernel.org/pub/linux/utils/cryptsetup/v2.7/v2.7.0-ReleaseNotes  
notably we don't have `CONFIG_BLK_SED_OPAL` enabled
> main/cryptsetup: update to 2.7.0

- main/musl-cross/template.py
- main/musl-mallocng/template.py
- main/musl/template.py
main/musl main/musl-mallocng main/musl-cross: use https instead of http for musl source
> `main/musl` `main/musl-mallocng` `main/musl-cross`: use https instead of http for musl source

- main/sane-backends/template.py
LTO causes segfaults and USB scanner detection issues.
> main/sane-backends: disable lto

- main/gnome-control-center/template.py
- main/python-pycups/template.py
- main/system-config-printer/patches/Makefile-python.patch
- main/system-config-printer/template.py
- **main/python-pycups: new package (2.0.1)**
- **main/system-config-printer: new package (1.5.18)**
- **main/gnome-control-center: add depenency on system-config-printer**
> Fix adding printers in GNOME control center

- main/docbook-xsl/template.py
some things use `xmlcatalog` to look up if the xsl exists seemingly, so just pull it in
> main/docbook-xsl: depend on libxml2-progs 

- contrib/granite/template.py
- contrib/granite/update.py
- contrib/swaync/files/swaync.user
- contrib/swaync/template.py
the full name is huge so every distro names this swaync usually
also has the user service that doesn't work by default because of the display thing, but works to manually start after like fnott, kanshi etc
> contrib/swaync: new package (0.10.0)

- contrib/nautilus-python/template.py
Required e.g. for [nautilus-taildrop](https://github.com/bahorn/nautilus-taildrop)
(explicit commit due to [tiny build patch right after the 4.0 tag](https://gitlab.gnome.org/GNOME/nautilus-python/-/commit/9a74cae1024aa279d2d70af2bf298cd1b57c1997))
> contrib/nautilus-python: new package (4.0)

- contrib/ccid/template.py
- contrib/ccid/update.py
- contrib/openpgp-card-ssh-agent/files/openpgp-card-ssh-agent.user
- contrib/openpgp-card-ssh-agent/template.py
- contrib/openpgp-card-ssh-agent/update.py
- contrib/openpgp-card-tools/template.py
- contrib/openpgp-card-tools/update.py
- **contrib/pcsc-ccid: new package (1.5.5)**: Needed for using the two tools below
- **contrib/openpgp-card-tools: new package (0.10.0)**: Tool for managing openpgp smart cards
- **contrib/openpgp-card-ssh-agent: new package (0.2.3)**: SSH agent for OpenPGP authentication subkeys on OpenPGP smart cards.
> OpenPGP card tooling

- contrib/wlroots0.16/template.py
- contrib/wlroots0.17/template.py
- main/xcb-util-errors-devel
- main/xcb-util-errors/template.py
I needed this package for my own wayland compositor development purposes so I thought I might as well enable it for the packaged wlroots versions as well to give developers better error messages in possible bug reports.
> contrib/wlroots0.17: add xcb-util-errors dep

- contrib/delta/template.py
Upstream does not guarantee updating the vendored completion when tagging releases, and recommends generating them from the binary https://dandavison.github.io/delta/tips-and-tricks/shell-completion.html
> contrib/delta: generate completions

- src/cbuild/core/chroot.py
- src/cbuild/core/pkg.py
- src/cbuild/core/template.py
- src/cbuild/hooks/post_install/006_protected_paths.py
- src/cbuild/hooks/pre_pkg/003_pc_provides.py
- src/cbuild/step/install.py
- src/cbuild/util/patch.py
- src/runner.py
```
$ ruff check src
src/cbuild/core/chroot.py:65:20: F821 Undefined name `stat`
src/cbuild/core/pkg.py:7:20: F821 Undefined name `stat`
src/cbuild/core/template.py:310:33: F821 Undefined name `stat`
src/cbuild/hooks/post_install/006_protected_paths.py:22:20: E713 [*] Test for membership should be `not in`
src/cbuild/hooks/post_install/006_protected_paths.py:23:46: F821 Undefined name `path`
src/cbuild/hooks/post_install/006_protected_paths.py:25:46: F821 Undefined name `path`
src/cbuild/hooks/pre_pkg/003_pc_provides.py:20:53: F821 Undefined name `soname`
src/cbuild/step/install.py:7:5: F821 Undefined name `os`
src/cbuild/step/install.py:7:20: F821 Undefined name `stat`
src/cbuild/util/patch.py:50:18: F821 Undefined name `shlex`
src/runner.py:1836:15: F821 Undefined name `errors` …
```
> cbuild: fix a bunch of linter warnings

- src/cbuild/core/update_check.py
What used to be a literal double quote is now `&quot;`, but the `.tar.gz`
alone should be enough for the regex's purposes anyway so there's no need
to match the double quote.
> cbuild: fix gitlab update check regex

- contrib/dbus-test-runner-devel
- contrib/dbus-test-runner/patches/ignore-test-output.patch
- contrib/dbus-test-runner/patches/no-dbus-glib.patch
- contrib/dbus-test-runner/template.py
Required by https://github.com/chimera-linux/cports/pull/1385
I disabled checks for now, because i can't really figure out, why does it fail
Here is the log with results https://pastebin.com/ZWk3pGCQ
> contrib/dbus-test-runner: new package (19.04.0)

- contrib/xwayland-run/template.py
```
root@cbuild: /builddir/kwindowsystem-6.0.0/build$ QT_QPA_PLATFORM=xcb xwfb-run -e /dev/stdout -- ctest -E 'kwindowinfox11test|threadtest|kwindowsystem(x11test|-kwindoweffectstest)' --output-on-failure
Date: 2024-03-25 UTC
[10:46:22.570] weston 13.0.0
https://wayland.freedesktop.org
Bug reports to: https://gitlab.freedesktop.org/wayland/weston/issues/
Build: 13.0.0
[10:46:22.570] Command line: weston --no-config --backend headless --socket wayland-1276
[10:46:22.570] OS: Linux, 6.7.10_1, #1 SMP PREEMPT_DYNAMIC Fri Mar 15 23:56:15 UTC 2024, x86_64
[10:46:22.570] Flight recorder: enabled
[10:46:22.570] Starting with no config file.
[10:46:22.570] Output repaint window is 7 ms maximum.
[10:46:22.570] Loading module '/usr/lib/libweston-13/headless-backend.so'
[10:46:22.571] Registered …
```
> contrib/xwayland-run: add missing xwayland dep

- main/gnome-font-viewer/template.py
Remove vis and cfi TODO because cfi probably isn't happening with glib.
> main/gnome-font-viewer: update to 46.0

- contrib/perf/template.py
this is a single usr/share/doc/perf-tip/tips.txt file that perf displays tips from in `perf report` (or tells you to please install perf otherwise lol), there's no point to separating it
> contrib/perf: don't split doc

- main/libspelling/template.py
- main/libspelling/update.py
libspelling moved to the GNOME namespace
> main/libspelling: update repo url

- contrib/suil/update.py
- main/lilv/update.py
- main/serd/update.py
- main/sord/update.py
- main/sratom/update.py
I've checked https://repo.chimera-linux.org/cports-updates/cports-updates.txt to see what packages I need to update and decided to fix a bunch of the `CAUTION: no version found for '<package>'` warnings in there.
The only thing we're still missing is libreoffice, but I really couldn't find a good url for fetching that.
> fix drobilla.net update checks

- main/freetype/template.py
Fix build by adding freetype-bootstrap to makedepends.  While here, sort makedepends and configure_args items
> main/freetype: fix build

- main/klibc-kinit-standalone/patches/drop-linear.patch
- main/klibc-kinit-standalone/template.py
Fix build after md-linear was dropped from kernel and also install proper license file
> main/klibc-kinit-standalone: fix build

- main/cargo/template.py
Without sqlite-devel it fails with this error:
note: ld: error: unable to find library -lsqlite3
> main/cargo: fix build

- contrib/nodejs/template.py
Fixes CVE-2024-27983 and CVE-2024-27982.
> contrib/nodejs: update to 21.7.2

- main/libbs2b/patches/fix-build.patch
- main/libbs2b/template.py
Without this change it fails like:
```/builddir/libbs2b-3.1.0/src/bs2bconvert.c:156:11: error: format string is not a string literal (potentially insecure) [-Werror,-Wformat-security]
156 |                 printf( sf_strerror( NULL ) );
|                         ^~~~~~~~~~~~~~~~~~~
/builddir/libbs2b-3.1.0/src/bs2bconvert.c:156:11: note: treat the string as an argument to avoid this
156 |                 printf( sf_strerror( NULL ) );
|                         ^
|                         "%s",```
> main/libbs2b: fix -Werror=format-security

- contrib/intel-undervolt/files/intel-undervolt
- contrib/intel-undervolt/files/intel-undervolt-loop
- contrib/intel-undervolt/patches/configure-gsed.patch
- contrib/intel-undervolt/patches/fix_include.patch
- contrib/intel-undervolt/patches/fix_install.patch
- contrib/intel-undervolt/template.py
Confirmed tested and working as on arch linux. Did not test the -loop service but it should work the same. Tested by the following means:
- set a large compile with make -j9
- apply undervolt config
- notice thermal throttling to be reduced
- revert config
- throttling is back
- apply config again and reboot, then use `intel-undervolt read` to check if config is applied on boot
> contrib/intel-undervolt: new package

- contrib/nbfc-linux/files/nbfc
...yeah
typo prevents boot and requires manual intervention
> contrib/nbfc-linux fixup: fix typo in service

- contrib/inkscape/template.py
- contrib/libreoffice-lang_hy
- contrib/libreoffice/patches/fsword_t.patch
- contrib/libreoffice/template.py
- main/poppler/template.py
`libtommath-devel` is only needed when embedded firebird is used, but we pass `--disable-firebird-sdbc` to configure and so firebird is disabled altogether.
[ci skip]
> main/poppler: update and run tests; contrib/libreoffice: update

- Packaging.md
- main/python/template.py
- src/cbuild/core/profile.py
- src/cbuild/core/template.py
[ci skip]
closes #1604  
---
this is the most naive implementation:  
- does this matter only for stage>0? (shouldn't make a meaningful difference)
- do we want the `-m` arg on every arch? (clang accepts it everywhere, but i don't know outside-of-x86_64 caveats)
after this, and rebuilding musl with it for a test on a simple program, `perf record -F100 -g ...` (`-g` implicit `--call-graph=fp`) works normally.
> cbuild: enable keeping frame pointers by default

- main/linux-stable-zfs-bin/template.py
The linked ticket was resolved in zfs 2.2.3.
> main/linux-stable-zfs-bin: remove broken on riscv64

- main/cryptsetup/template.py
The configure script is ignoring those and using openssl's argon2 anyway.
> main/cryptsetup: remove argon2 dep and configure arg

- contrib/fzf/template.py
Does this still need `options = ["!strip"]`? @q66 added it in 1896da1 but I'm not sure what the reason was. As far as I can tell it builds and runs ok without it.
> contrib/fzf: update to 0.50.0

- contrib/mate-polkit/template.py
Somebody asked for a polkit agent that could be used outside of gnome and reminded me that I was missing one myself
> contrib/mate-polkit: new package (1.28.1)

- src/cbuild/hooks/do_pkg/000_gen_apk.py
`pkg.so_requires` isn't used anywhere else anyway.
> cbuild: remove redundant sort

- main/dtc/update.py
- main/f2fs-tools/update.py
- main/firmware-linux/update.py
- main/libtraceevent/update.py
- main/libtracefs/update.py
- main/pahole/update.py
All of these had `no version` found in https://repo.chimera-linux.org/cports-updates/cports-updates.txt
> main/*: fix git.kernel.org update-check

- src/cbuild/util/cmake.py
- src/cbuild/util/meson.py
this bit me when setting up armhf
> cbuild: disambiguate unknown architecture error between cmake and meson

- src/cbuild/core/template.py
bash and zsh completions are already included so there's no reason not to include fish ones as well
doesn't actually affect anything at the moment so no relbumps required
> cbuild: take fish completion dirs with `take_progs`/`default_progs`

- main/libadwaita-demo
- main/libadwaita/patches/bsd-date.patch
- main/libadwaita/template.py
This commit makes the `libadwaita` demo application available via a subpackage of `libadwaita`.
A packaged demo application is a useful companion when developing against `libadwaita`, especially when combined with the GTK inspector.
> main/libadwaita-demo: new package (1.5.0)

- main/wasi-libc/template.py
- main/wasi-sdk/template.py
matches latest 'release' sdk-22 https://github.com/WebAssembly/wasi-libc/releases/tag/wasi-sdk-22
> main/wasi-libc: update to 0.20240412

- contrib/corrosion/template.py
- user/taskwarrior/patches/new-corrosion.patch
Is it okay to put the taskwarrior patch in here?
See https://github.com/corrosion-rs/corrosion/blob/master/RELEASES.md#breaking-changes-1
> contrib/corrosion: update to 0.5.0

- contrib/hugo/template.py
I no longer use hugo, so I don't plan on updating this package any more. I thought I might as well do one last update along with the orphan commit though.
> contrib/hugo: update to 0.126.1, orphan

- contrib/bpftool/update.py
- contrib/comrak/template.py
- contrib/comrak/update.py
- contrib/perf/update.py
- main/cpupower/update.py
- main/protobuf/update.py
`no version found` as seen in https://repo.chimera-linux.org/cports-updates/cports-updates.txt and verified locally
> Fix some update-checks

- contrib/xfce4-settings/patches/defaults.patch
- contrib/xfce4-settings/template.py
The latter has weird icon colors sometimes, e.g. the speaker icon shown on the volume notification when changing audio volume.
> contrib/xfce4-settings: default to `Papirus-Light` instead of `Papirus`

- main/xorriso/template.py
Seems to generate a Chimera GNOME ISO just fine.
> main/xorriso: re-enable cfi

- main/mandoc/patches/signed-overflow.patch
- main/mandoc/template.py
The motivation for moving `mandoc-apropos`'s contents (save the trigger) to the main package is to allow people to do `apk add !mandoc-apropos` but still be able to run `makewhatis`, e.g. in a cron job, instead of using the apk trigger (because the command can take quite a bit).
> main/mandoc: move apropos stuff to main pkg, enable int+lto+vis+cfi

- main/protobuf-c/template.py
These were bringing in `protoc`/`protobuf-devel` into `base-desktop` (through `libshumate`/`gnome-maps`).
I'm aware this probably isn't the right solution but I just wanted this issue to be seen. It also frees up ~23 MiB
```
(1/9) Upgrading protobuf-c (1.5.0-r8 -> 1.5.0-r9)
(2/9) Purging protoc (26.1-r1)
(3/9) Purging protobuf-devel (26.1-r1)
(4/9) Purging protobuf (26.1-r1)
(5/9) Purging protobuf-lite (26.1-r1)
(6/9) Purging abseil-cpp-devel (20240116.2-r1)
(7/9) Purging abseil-cpp-testing (20240116.2-r1)
(8/9) Purging abseil-cpp (20240116.2-r1)
(9/9) Purging gtest (1.14.0-r0)
```
> main/protobuf-c: move binaries into -devel subpkg

- contrib/aria2/template.py
- contrib/aria2/update.py
I believe aria2 has a library that could be built too, but I haven't figured out how to achieve this with a subpackage yet or if it should be -devel or -libs.
> contrib/aria2: new package

- contrib/php8.3/patches/ab2c69884b474a81ce26a51d6ba0deeb1a14587a.patch
I didn't bump `pkgrel` since this change will not affect final package so it doesn't need to rebuild and people don't need to upgrade it
> contrib/php8.3: fix tests with curl 8.8.0

- contrib/kwidgetsaddons/template.py
Seems to crash in https://invent.kde.org/frameworks/kwidgetsaddons/-/blob/v6.2.2/src/kmessagedialog.cpp#L496 fwiw, I don't really feel like fixing it (at least right now) since I've had to `!cfi` what feels like every other kde package to stop random stuff from dying
> contrib/kwidgetsaddons: update to 6.2.2, disable cfi

- contrib/qt6-qtsensors-devel
- contrib/qt6-qtsensors/patches/no-cmake-tests.patch
- contrib/qt6-qtsensors/template.py
- contrib/qt6-qtsensors/update.py
`kscreen` and `kwin` will build with this for future https://gitlab.freedesktop.org/hadess/iio-sensor-proxy enablement on devices with accelerometer for auto-rotation etc.
> contrib/qt6-qtsensors: new package (6.7.1)

- contrib/just/template.py
`python` added to `checkdepends` for this test:
https://github.com/casey/just/blob/cf3141306e407342dd3cfa563ac66fd86b5ffdc8/tests/backticks.rs#L10
> contrib/just: update to 1.27.0

- contrib/xfce4-settings/patches/defaults.patch
- contrib/xfce4-settings/template.py
This reverts commit 5a1300dcb12592f1741386076e3ae6a1a7680960.
See https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/2896#issuecomment-985442354; since the Xfce panel is dark by default with our theme of choice, we should be defaulting to `Papirus` and not `Papirus-Light`. I'll ask upstream later about the original color issues that prompted me to erroneously switch the default to `Papirus-Light`.
> Revert "contrib/xfce4-settings: default to `Papirus-Light` instead of `Papirus`"

- contrib/exo/template.py
- contrib/garcon/template.py
- contrib/gigolo/template.py
- contrib/libxfce4ui/template.py
- contrib/libxfce4util/template.py
- contrib/libxklavier/template.py
- contrib/mousepad/template.py
- contrib/orage/template.py
- contrib/thunar-volman/template.py
- contrib/thunar/template.py
- contrib/tumbler/template.py
- contrib/xfburn/template.py
- contrib/xfce4-appfinder/template.py
- contrib/xfce4-dev-tools/template.py
- contrib/xfce4-dict/template.py
- contrib/xfce4-mixer/template.py
- contrib/xfce4-notifyd/template.py
- contrib/xfce4-panel/template.py
- contrib/xfce4-power-manager/template.py
- contrib/xfce4-screensaver/template.py
- contrib/xfce4-session/template.py
- contrib/xfce4-settings/template.py
- contrib/xfce4-taskmanager/template.py
- contrib/xfce4-terminal/template.py
- contrib/xfce4-volumed-pulse/template.py
- contrib/xfconf/template.py
- contrib/xfwm4/template.py
- **contrib/*: use make_dir = "." for all xfce templates**
- **contrib/garcon: enable introspection**
- **contrib/xfconf: enable introspection**
- **contrib/xfce4-panel: build with introspection**
- **contrib/xfce4-screensaver: don't accidentally set url twice**
- **contrib/libxklavier: build with introspection**
- **contrib/libxfce4ui: enable introspection, build with libgudev, pass vendor info**
- **contrib/xfce4-notifyd: don't install systemd service**
- **contrib/libxfce4util: enable introspection**
- **contrib/thunar: enable introspection, don't install systemd service**
- **contrib/tumbler: don't install systemd service**
> contrib/*: improve xfce templates

- main/heif-thumbnailer
- main/libheif/template.py
thumbnailer file was previously in the main libheif package, while the
heif-thumbnailer binary and manpage were both in libheif-progs
> main/libheif: move thumbnailer into subpackage

- contrib/nginx/files/nginx
- contrib/nginx/files/sysusers.conf
- contrib/nginx/template.py
fixes a typo where the system user would otherwise be installed as `_nignx`
i also used that opportunity to unalign the service and run it as said user.
> contrib/nginx: use system user in service

- main/cbindgen/template.py
- main/mesa/template.py
not released obviously, for whoever wants to test it early  
new in this:  
- xe is default enabled for intel
- nvk (vulkan-drivers=nouveau), needs rust
- nouveau (gallium) needs rust now too
> main/mesa: update to 24.1.0

- contrib/networkmanager-openconnect/files/sysusers.conf
- contrib/networkmanager-openconnect/patches/rename_system_user.patch
- contrib/networkmanager-openconnect/template.py
- contrib/networkmanager-openconnect/update.py
- contrib/openconnect-devel
- contrib/openconnect/template.py
- contrib/vpnc-scripts/template.py
- contrib/vpnc-scripts/update.py
patching the gcr 3 dep to 4 requires yanking a widget that was entirely removed, as far as i can tell with no replacement. i assume its fine because its just displaying a cert with no interactivity. some tests are also completely broken, i may investigate later
>  contrib/networkmanager-openconnect: new package (1.2.10)

- contrib/dnsmasq/patches/conf.patch
- contrib/dnsmasq/patches/user.patch
- contrib/dnsmasq/template.py
noticed this file was missing when setting up libvirt
> contrib/dnsmasq: install config file

- contrib/glycin-loaders/patches/cargo-auditable.patch
- contrib/glycin-loaders/patches/meson-cargo.patch
- contrib/glycin-loaders/template.py
turns out the original comment regarding tests needing system-installed loaders was not true at all; for tests, the buildsystem installs the loaders into a separate location in the build directory and then the tests use these loaders
> contrib/glycin-loaders: build with cargo-auditable, run checks

- main/gnutls/template.py
host `trousers-devel` seems to be needed
> main/gnutls: fix cross

- main/elfutils/template.py
otherwise errors for armhf with
```
In file included from ../../backends/m68k_corenote.c:72:
../../backends/linux-core-note.c:99:27: error: field pr_utime within 'struct m68k_prstatus' is less aligned than 'struct m68k_timeval' and is usually due to 'struct m68k_prstatus' being packed, which can lead to unaligned accesses [-Werror,-Wunaligned-access]
99 |   struct EBLHOOK(timeval) pr_utime;
|                           ^
../../backends/linux-core-note.c:100:27: error: field pr_stime within 'struct m68k_prstatus' is less aligned than 'struct m68k_timeval' and is usually due to 'struct m68k_prstatus' being packed, which can lead to unaligned accesses [-Werror,-Wunaligned-access]
100 |   struct EBLHOOK(timeval) pr_stime;
|                           ^
../../backends/linux-core-note.c:101:27: …
```
> main/elfutils: silence unaligned access warning

- main/dbus/files/dbus
- main/dbus/files/dbus.user
- main/dbus/template.py
e.g. so that yakuake, when added to kde's autostarted apps, starts in $HOME and not in /etc/dinit.d/user
> main/dbus: start user service in $HOME and system service in /

- main/base-kernel/files/sysctl.d/sysctl.conf
- main/base-kernel/template.py
some discussion in https://lists.archlinux.org/archives/list/arch-dev-public@lists.archlinux.org/thread/5GU7ZUFI25T2IRXIQ62YYERQKIPE3U6E/  
final news https://archlinux.org/news/increasing-the-default-vmmax_map_count-value/  
malloc-ng is also affected- for instance when doing a thinlto link of firefox on an altra machine with 80 cores it would get a bad alloc error at some point raised from llvm, but the cause of it is just running out of maps (since it's very map hungry). doesn't affect our default allocator though
fedora/ubuntu apparently ship this same thing too
> main/base-kernel: raise vm.max_map_count by default

- contrib/plasma-workspace/patches/locales.patch
- contrib/plasma-workspace/template.py
fixes system settings warning "Could not find the system's available locales" when changing language
waiting on https://github.com/chimera-linux/cports/pull/2027
> contrib/plasma-workspace: correct system locales path

- contrib/fossil/template.py
the configure option wasnt actually doing anything since the final package never ends up depending on the sqlite3 so. also when forcibly patching the included amalgamation out, some symbols are missing:
```
ld: error: undefined symbol: sqlite3_shell
>>> referenced by sqlcmd.c:426 (../src/sqlcmd.c:426)
>>>               bld/fossil.lto.sqlcmd.o:(cmd_sqlite3)
ld: error: undefined symbol: deduceDatabaseType
>>> referenced by main.c:661 (../src/main.c:661)
>>>               bld/fossil.lto.main.o:(fossil_main)
ld: error: undefined symbol: sqlite3_shathree_init
>>> referenced by login.c:891 (../src/login.c:891)
>>>               bld/fossil.lto.login.o:(login_resetpw_suffix)
ld: error: undefined symbol: sqlite3_appendvfs_init
>>> referenced by db.c:2107 (../src/db.c:2107)
>>> …
```
> contrib/fossil: don't try to use system sqlite

- contrib/kinfocenter/template.py
- contrib/qdbus
- contrib/qt6-qttools/template.py
Add missing `libpulse-progs` for `pactl` which the audio tab can optionally show and save ~140 MiB of on-disk space by splitting `qdbus` away separate from `qt6-qttools` since that's the only thing `kinfocenter` needs to run `/usr/lib/qt6/bin/qdbus org.kde.KWin /KWin supportInformation` for `Window Manager` tab.
Fwiw `usr/bin/qdoc6` & `usr/lib/qt6/bin/{lupdate,qdoc}` are the ones that were pulling in  `clang{,-cpp}-libs`. Funnily enough `qt6-qttools` was also bringing in Qt Designer but it doesn't have a `.desktop` entry, though that's a separate matter :p
> KInfoCenter fixes

- main/editorconfig/template.py
- main/editorconfig/update.py
tested with gnome-text-editor, and confirmed that all revdeps build fine
> main/editorconfig: run tests, enable vis+cfi

- contrib/python-tomli/template.py
not used by anything in main anymore
> contrib/python-tomli: move from main, enable tests

- src/cbuild/core/update_check.py
not every project has a releases page, but tags should reflect all the versions too
> cbuild: make codeberg use /tags instead of /releases

- main/libbytesize/template.py
depends on the python bindings
> main/libbytesize: move bscalc to python subpackage

- contrib/just/template.py
- Project has stopped including the completions and man page in the repo, requiring running the binary to generate them. I did what I did for other packages and fish them out of one of the published binary tarballs.
- Some tests fail to run due to [assuming running from a git repo](https://github.com/casey/just/blob/ef6a813dd178f43d112cf87b2bd09b79f60e5454/tests/completions/just.bash#L24), skip these.
> contrib/just: update to 1.29.1

- contrib/konqueror/template.py
usr/lib/libkwebenginepart.so is not a symlink but cbuild moves it to
-devel anyway, so the parent package ends up depending on -devel, move
the shared library to the parent package instead
> contrib/konqueror: remove accidental dependency on -devel subpackage

- src/cbuild/util/strip.py
strip --strip-debug keeps .strtab/.symtab/.comment  
---
- maybe just `--strip-unneeded --keep-section=.gnu_debuginfo` is better?
- i'm not sure if the objcopy to itself is valid
> cbuild: actually strip bins in strip

- main/python/template.py
Attempting to build `main/python` resulted in this error prior to this change:
```
=> python-3.12.4-r0: ERROR: path 'usr/lib/python3.12/lib2to3/tests' does not match anything
=> Stack trace:
=>   /home/wmoore/cports/src/cbuild/core/build.py:24: in function 'build'
=>   /home/wmoore/cports/src/cbuild/core/build.py:161: in function '_build'
=>   /home/wmoore/cports/src/cbuild/core/dependencies.py:445: in function 'install'
=>   /home/wmoore/cports/src/cbuild/core/build.py:24: in function 'build'
=>   /home/wmoore/cports/src/cbuild/core/build.py:225: in function '_build'
=>   /home/wmoore/cports/src/cbuild/step/install.py:46: in function 'invoke'
=>   /home/wmoore/cports/src/cbuild/core/template.py:1410: in function 'run_step'
=>   /home/wmoore/cports/src/cbuild/core/template.py:227: in …
```
> main/python: fix build

- main/grub/template.py
otherwise, when parsing the template for an unsupported arch, the subpackage flag refers to an _archs variable that was never set up
the error in question is
```
=> A failure has occurred!
=> Stack trace:
=>   /home/me/cports/src/cbuild/core/template.py:2508: in function 'read_mod'
=>   <frozen importlib._bootstrap_external>:995: in function 'exec_module'
=>   <frozen importlib._bootstrap>:488: in function '_call_with_frames_removed'
=>   /home/me/cports/main/grub/template.py:228: in function '<module>'
=>   /home/me/cports/main/grub/template.py:197: in function '_genplatform'
=> Raised exception:
=>   NameError: name '_archs' is not defined
```
> main/grub: fix parsing for broken archs

- main/libkcapi/template.py
failure is
```
bmake: "/builddir/libkcapi-1.5.0/build/Makefile" line 2021: warning: duplicate script for target "lib/doc/bin/docproc" ignored
bmake: "Makefile" line 995: warning: using previous script for "lib/doc/bin/docproc" defined here
/bin/sh ./libtool  --tag=CC    --mode=link riscv64-chimera-linux-musl-clang  -fstack-protector-strong -ffile-prefix-map=/builddir/libkcapi-1.5.0=. -Wformat -Werror=format-security -ftrivial-auto-var-init=zero -fno-omit-frame-pointer -fsanitize=signed-integer-overflow,integer-divide-by-zero -fsanitize-trap=signed-integer-overflow,integer-divide-by-zero -fno-sanitize-recover -O2 -g2 -fpie -fPIE -DPIE   -Wl,-z,pack-relative-relocs -Wl,-O2 -fno-omit-frame-pointer -fsanitize=signed-integer-overflow,integer-divide-by-zero …
```
> main/libkcapi: fix cross

- .gitignore
Here neovim users who opted in for the exrc option can put some custom project-specific filetype definitions, user commands etc.
> gitignore: ignore neovim exrc files

- user/hyfetch/patches/add-chimera.patch
- user/hyfetch/patches/remove-typing_extensions-dependency.patch
- user/hyfetch/template.py
Sadly it does not support chimera yet but users can configure to their liking.
> user/hyfetch: new package (1.4.11)

- main/openrc-settingsd/patches/0001-adjust-files-to-match-Chimera-s-setup.patch
- main/openrc-settingsd/template.py
I think `openrc-settingsd` is mistakenly being appended twice. `meson.build` sets `PKGDATADIR` to `/usr/share/openrc-settingsd` and installs `kbd-model-map` there. Then localed looks for `kbd-model-map` in `PKGDATADIR "/openrc-settingsd"` which obviously it doesn't find. This looks like it might be an upstream issue too, but I couldn't say that for certain.
> main/openrc-settingsd: fixed localed reading kbd-model map from wrong location

- contrib/helix/template.py
cc @wezm
Feels like the dir itself should be `/usr/lib/helix/runtime` since there is no binary there anymore, but I didn't want to do preemptive changes.
> contrib/helix: specify runtime installation dir explicitly

- main/zlib-ng-compat/patches/armv7.patch
Previously it incorrectly assumed arch as x86_64 which obviously made it fail immediatly
> main/zlib-ng-compat: fix armv7 cross

- Packaging.md
- contrib/minijinja-cli/template.py
- contrib/nushell/patches/0001-implement-autoloading-13217.patch
- contrib/nushell/patches/0002-Switch-from-dirs_next-2.0-to-dirs-5.0-13384.patch
- contrib/nushell/patches/0003-Use-proper-directories-for-autoloading.patch
- contrib/nushell/patches/autoload.patch
- contrib/nushell/template.py
- src/cbuild/core/template.py
- **contrib/nushell: new package (0.95.0)**: There's a patch in here for autoloading. The patch is upstream, but not yet released. I've tested it locally, it seems to work fine as far as I can tell.
- **cbuild: split nucomp**: I've done this based on 0744645a09d3b4aff93fda6665db9e248f8ef993 and 8536d97eb4bc1eaad7c6af9a33e5b329856896d5, and while I think I understand what's happening there for the most part, I'd appreciate another look from someone else here.
- **contrib/minijinja-cli: update to 2.0.3**: Only included as an example of a tool that I know has nushell completions, allowing to try this out easily.
> contrib/nushell: new package (0.95.0)

- main/btrfs-progs/template.py
for armhf:
```
In file included from constants.c:4:
In file included from ./btrfsutilpy.h:27:
In file included from /usr/include/python3.12/Python.h:38:
/usr/include/python3.12/pyport.h:586:2: error: "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
586 | #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
|  ^
1 error generated.
```
> main/btrfs-progs: prevent cross build

- contrib/aerc/template.py
- contrib/age/template.py
- contrib/bluetuith/template.py
- contrib/buildkit/template.py
- contrib/chezmoi/template.py
- contrib/cliphist/template.py
- contrib/cni-plugins/template.py
- contrib/containerd/template.py
- contrib/croc/template.py
- contrib/docker-cli/template.py
- contrib/docker-compose/template.py
- contrib/fzf/template.py
- contrib/go-md2man/template.py
- contrib/goawk/template.py
- contrib/gopass/template.py
- contrib/gopls/template.py
- contrib/hut/template.py
- contrib/nerdctl/template.py
- contrib/podman/template.py
- contrib/restic/template.py
- contrib/rootlesskit/template.py
- contrib/runc/template.py
- contrib/scc/template.py
- contrib/senpai/template.py
- contrib/shfmt/template.py
- contrib/tailscale/template.py
- contrib/yj/template.py
objcopy failing on ppc64le is not an issue anymore
can also just postpone this to the next go bump global rebuild if you want @nekopsykose
> */*: re-enable debug for go packages

- contrib/emptty/files/dinit-service
- contrib/emptty/template.py
[emptty](https://github.com/tvrzna/emptty) is CLI display manager on TTY, that supports Xorg and Wayland desktops. 
- `ppc64le` - ok
- `aarch64` - ok
- `x86_64` - ok
- `ppc64` - unknown to Golang (after adding into `etc/build_profiles/ppc64.ini` it fails on "-buildmode=pie not supported on linux/ppc64")
- `riscv664` - ok
`armhf`, `armv7`, `ppc` - `libx11` cannot be crosscompiled (`emptty` supports `noxlib` tag, it is theoretically possible to make it work)
> contrib/emptty: new package (0.12.1)

- contrib/ddclient/patches/disable_automake_warnings_as_errors.patch
- contrib/ddclient/template.py
Not sure when this broke, but packaging ddclient started giving
```
automake: warnings are treated as errors
Makefile.am:20: warning: escaping \# comment markers is not portable
autoreconf: error: automake failed with exit status: 1
```
> contrib/ddclient: disable automake treating warnings as error

- contrib/containers-common/template.py
It is not used since 7bc50781a3d992709c70fe3392cae83fa7b12286
> contrib/containers-common: clean up unused skopeo source

- contrib/podman/template.py
- contrib/skopeo/template.py
With the current package go versions this is the default.
No version bump as there is no change in how build happens.
> contrib/*: drop `-mod vendor` from build args

- contrib/skopeo/template.py
This is to be on the same page as other container tools from the
same family: buildah and podman. There does not seem to exist
a behavioural change in my (and probably any typical) use.
It seems Debian does it this way too, but Arch does not, so
it is strictly a matter of builder's preference.
> contrib/skopeo: link against system libsqlite3

- contrib/buildah/template.py
Align with podman. The devel dependency was already there.
> contrib/buildah: enable seccomp support

- main/clang-rt-crt-cross/template.py
not sure how that would end up missing? a transitive dependency that got changed?
> main/clang-rt-crt-cross: add missing gmake dependency

- src/cbuild/core/scanelf.py
the original condition evaluates to false for empty strings because they are falsy in python
> cbuild: correct check for empty soname in scanelf

- main/libsasl/template.py
kmail needs these for imap auth, or else it dies with:
SASL(-4): no mechanism available: No worthy mechs found
> main/libsasl: don't uninstall plugins

- main/python-lxml/template.py
also add pkgconf to hostmakedepends; it can use that instead of
the -config scripts to find libxml2 and libxslt
> main/python-lxml: !cross

- Packaging.md
Decorated functions must be named a single underscore, which is enforced by cbuild.
> packaging: use _ for decorated functions

- src/cbuild/core/chroot.py
does it in one :)  
---
this isn't strictly identical; `--update-cache` defaults to a 1 minute cache age so repeated calls for a minute will just no-op. it can be made identical by passing `0` to it to always update just like update does, and then the behaviour should be actually the same
but maybe it's not super relevant to miss a minute?
> cbuild: skip apk update before upgrade call

- src/runner.py
(note that this does not print any hostdepends for cross, since `Template.get_build_deps` doesn't include those)
> cbuild: make print-build-graph aware of -a

- contrib/tinyxml2-devel
- contrib/tinyxml2/template.py
- user/cppcheck-gui
- user/cppcheck/patches/feenableexcept.patch
- user/cppcheck/patches/translation-files.patch
- user/cppcheck/template.py
`HAVE_RULES` (I believe this let you define your own rules and cppcheck will check for you) require pcre, so it's not enabled. And `feenableexcept.patch` is copied from [alpine](https://git.alpinelinux.org/aports/tree/community/cppcheck/feenableexcept.patch).
> user/cppcheck: new package

- contrib/merkuro/patches/fix-contact_plugin-load.patch
- contrib/merkuro/template.py
`merkuro-calendar` was failing to launch with:
```
QQmlApplicationEngine failed to load component
qrc:/main.qml:328:19: Type MainDrawer unavailable
qrc:/MainDrawer.qml:341:9: Type CheckableCollectionNavigationView unavailable
qrc:/CheckableCollectionNavigationView.qml:11:1: Failed to extract plugin meta data from '/usr/lib/qt6/qml/org/kde/merkuro/contact/libmerkuro_contact_pluginplugin.so': '/usr/lib/qt6/qml/org/kde/merkuro/contact/libmerkuro_contact_pluginplugin.so' is not a Qt plugin (metadata not found)
```
> contrib/merkuro: fix launching merkuro-calendar

- contrib/tiramisu/template.py
This is a port of https://github.com/Sweets/tiramisu a simple headless notification daemon.
> contrib/tiramisu: new package

- contrib/python-websockets/template.py
I just needed this locally for something, I'm not sure what yt-dlp uses it for but it's the only thing that depends on it, so I haven't tested that beyond just checking yt-dlp still runs.
> contrib/python-websockets: update to 0.13

- src/cbuild/util/meson.py
fixes cross builds for meson packages that have `rust` as a language passed to `project`:
meson.build:1:0: ERROR: 'rust' compiler binary not defined in cross file [binaries] section
> cbuild: add rust to binaries section in meson crossfile

- main/lldb/patches/fix-python-api.patch
- main/lldb/template.py
fixes:
```
Python 3.12.5 (main, Aug 23 2024, 00:07:38) [Clang 18.1.8] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lldb
Fatal Python error: PyImport_AppendInittab: PyImport_AppendInittab() may not be called after Py_Initialize()
Python runtime state: initialized
Current thread 0x000070d3919922c8 (most recent call first):
File "/usr/lib/python3.12/site-packages/lldb/__init__.py", line 4394 in Initialize
File "/usr/lib/python3.12/site-packages/lldb/__init__.py", line 16172 in <module>
File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
File "<frozen importlib._bootstrap_external>", line 995 in exec_module
File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
File "<frozen importlib._bootstrap>", line 1331 in …
```
> main/lldb: backport python api fix

- user/niri/template.py
Whenever running Niri within a virtual machine with OpenGL capabilities (virgl) or a host with an OpenGL-supported CPU Smithay tries to load `libEGL.so` to provide support for OpenGL functionality. LibEGL is also listed as a runtime dependency in most of niri's official packages. Trying to run it within that context just crashes the program, thus it would be nice to have this as a requirement for the package
> user/niri: add libEGL as runtime-dependency

- user/wpaperd/template.py
Wpaperd is a wayland-only daemon for managing wallpapers in wayland compositors through wlr_layer_shell. This package should work fine, the wpaperd and wpaperctl binaries seem to be fine, I just dont currently know how to add the scdoc-generated documentation, what could I do here?
> user/wpaperd: new package

- contrib/tcsh/template.py
This PR adds the TCSH shell to Chimera! It seems to be building completely fine and running fine, the only issue is the test suite that requires all the locales and tcsh to be installed (not possible due to /usr/* being ro during check step)
> contrib/tcsh: new package

- user/wpaperd/template.py
[As @triallax mentioned](https://github.com/chimera-linux/cports/pull/2815#issuecomment-2319953690), there are no installed completions in the initial wpaperd package version, this fixes it!
> user/wpaperd: add completions for bash/zsh/fish

- user/transmission-daemon
- user/transmission-devel
- user/transmission-devel-static
- user/transmission-gtk
- user/transmission-progs
- user/transmission-qt
- user/transmission/files/sysusers.conf
- user/transmission/files/tmpfiles.conf
- user/transmission/files/transmission-daemon
- user/transmission/patches/miniupnpc.patch
- user/transmission/template.py
The 4.0.6 version does not have any of the `third-party` submodules fetched, and I was fetching from the wrong tarball when I was trying to build this. It shouldve mostly built but the build process gets halted right at the end due to [this issue](https://bugs.gentoo.org/915804). Also ideally maybe separating the libs, daemon, cli, gtk and qt versions into subpackages seems nice, I havent done that since I havent gotten a proper build yet
> user/transmission: new package (4.0.6)

- user/fragments/patches/meson.patch
- user/fragments/template.py
The Fragments GTK4 Bittorrent Client! Had to use a workaround to make the vendoring work with the weird cargo/meson hybrid system but everything seems to be working fine. This requires transmission-daemon, which is not yet packaged, so: WIP!
> user/fragments: new package (3.0.1)

- user/newsflash/patches/meson-cargo.patch
- user/newsflash/template.py
- user/newsflash/update.py
Had to do a workaround because the last part of the build tried to copy a non-existent file over to usr/bin, making a stub then installing it properly seems to work fine!
> user/newsflash: new package (3.3.4)

- contrib/swtpm/files/tmpfiles.conf
- contrib/swtpm/template.py
When creating vm with tpm with libvirt `/var/lib/swtpm-localca` is created with root ownership, this modifies the directory and files in it to have propper permissions.
> contrib/swtpm: create state dir with propper permissions

- contrib/amberol/template.py
- contrib/bcachefs-tools/template.py
- contrib/flare/template.py
- contrib/glycin-loaders/template.py
- contrib/helvum/template.py
- contrib/kdepim-addons/template.py
- contrib/key-rack/template.py
- contrib/loupe/template.py
- contrib/python-maturin/template.py
- contrib/ruff/template.py
- contrib/uv/template.py
- main/cargo-auditable-bootstrap/template.py
- main/cargo-auditable/patches/0001-Fix-detection-of-riscv64-linux-android-target-featur.patch
- main/cargo-auditable/template.py
- main/gnome-tour/template.py
- main/snapshot/template.py
- src/cbuild/util/cargo.py
- src/cbuild/wrappers/cargo.sh
- **main/cargo-auditable: fix usage on riscv64**: This problem came up in https://github.com/chimera-linux/cports/pull/2879. The patch is already merged upstream, but we're picking it here because it's not clear yet when a new release will be cut.
- **cbuild: reenable cargo-auditable on riscv64**: With the problem fixed above, it should be possible to reenable cargo-auditable on riscv64.
- **cbuild: use wrapper to enable cargo-auditable**: As suggested in https://github.com/chimera-linux/cports/pull/2879#issuecomment-2336414310, using a wrapper improves this more because we don't have to patch meson builds to get auditable builds.
> cargo auditable wrapper and riscv64 fix

- main/openssh/template.py
Enables the GSSAPI with krb5 using Heimdal.
> main/openssh: enable kerberos5 support

- user/topgrade/template.py
As discussed on [this](https://github.com/chimera-linux/cports/pull/2936#discussion_r1760371719), this package also generates completions using host binary
> user/topgrade: restrict cross compilation

- main/libdbi/template.py
Disable docs building since it requires openjade.  While here, add
automake and libtool dependencies and remove empty configure_gen.
> main/libdbi: disable docs and fix build

- user/openttd-locale
- user/openttd/patches/musl-random.patch
- user/openttd/patches/no-sse4.patch
- user/openttd/patches/redefs-fix.patch
- user/openttd/template.py
- user/openttd/update.py
i've disabled cross-compilation for this package because binaries that are compiled are used later in the build process and i don't see a way to do this (or do this sensibly at least) in cbuild with the upstream solution (https://github.com/OpenTTD/OpenTTD/pull/8350)
please correct me if i'm wrong though
> user/openttd: new package

- user/opentabletdriver-udev/patches/git.patch
- user/opentabletdriver-udev/patches/uinput.patch
- user/opentabletdriver-udev/template.py
This adds some Udev rules so that the flatpak version of OpenTabletDriver works fine, just needed to create a group to share the rules to any user, but thats all
> user/opentabletdriver-udev: new package

- user/calcurse/template.py
cfi breaks 37 out of 77 tests; disabling it for now
> user/calcurse: new package

- user/xournalpp/patches/no-sig.patch
- user/xournalpp/patches/noexecinfo.patch
- user/xournalpp/template.py
Building Xournal++ requires the C++ binding for libportaudio, so I modified the current portaudio template as well.
> user/xournalpp: new package

- main/ansible-core/template.py
- main/python-bcrypt/template.py
- main/python-passlib/template.py
- main/python-passlib/update.py
Packages python-passlib and makes ansible-core depend on it. While ansible-core does somewhat work without passlib, most things around hashing don't work without it.
> main/ansible-core: depend on python-passlib

- user/libgbinder-progs
- user/libgbinder/template.py
These may be of use for debugging Waydroid issues for example via the likes of:
```sh
mkdir /etc/gbinder.d
cat <<'EOF' > /etc/gbinder.d/waydroid-a11.conf
[General]
ApiLevel = 30
[Protocol]
/dev/anbox-binder = aidl3
/dev/anbox-vndbinder = aidl3
/dev/anbox-hwbinder = hidl
[ServiceManager]
/dev/anbox-binder = aidl3
/dev/anbox-vndbinder = aidl3
/dev/anbox-hwbinder = hidl
EOF
binder-list -d /dev/anbox-hwbinder -v
```
> user/libgbinder: also build test progs

- main/cryptsetup-scripts/patches/0001-general-portability-fixes-for-chimera-busyboxless-in.patch
Restore patch hook accidentally removed at dad7d80bc probably because
cryptsetup file is listed at project's .gitignore
[update skip]
> main/cryptsetup-scripts: restore patch hook

- main/nyagetty/files/agetty-service.sh
- main/nyagetty/template.py
When starting a serial getty by specifying it in `/etc/default/agetty` or running `dinitctl start agetty-service@ttyS0`, the service would crash because of a syntax error in the helper script `/usr/lib/agetty-service`.
> main/nyagetty: fix syntax error in agetty-service.sh

- main/libppd/patches/fix-overflow.patch
- main/libppd/template.py
Fix buffer overflow in ppdLoadAttributes().
A few days ago I noticed that all my print jobs were failing:
D [06/Nov/2024:07:34:56 +0100] [Job 18] ppdFilterLoadPPD: Color profile qualifier determined from job and PPD data 'RGB.Plain.'
D [06/Nov/2024:07:34:56 +0100] [Job 18] ppdFilterLoadPPD: No ICC profiles specified in PPD
D [06/Nov/2024:07:34:56 +0100] [Job 18] ppdFilterLoadPPD: Searching for profile "-/Plain"...
D [06/Nov/2024:07:34:56 +0100] [Job 18] prnt/hpcups/HPCupsFilter.cpp 592: cupsRasterOpen failed, fd = 0
D [06/Nov/2024:07:34:56 +0100] [Job 18] PID 20446 (/usr/lib/cups/filter/universal) crashed on signal 4.
D [06/Nov/2024:07:34:56 +0100] [Job 18] Hint: Try setting the LogLevel to "debug" to find out more.
> main/libppd: fix buffer overflow

- src/cbuild/core/chroot.py
Otherwise `-D`/`--dirty-build` doesn't work for cross-builds as the build deps are always removed on reruns. Test:
```
./cbuild -a aarch64 patch main/openssl
./cbuild -a aarch64 -D configure main/openssl
```
> cbuild: only clear world before cross sysroot setup in non-dirty builds

- main/sddm/template.py
`/usr/lib/sddm/sddm.conf.d/10-breeze-theme.conf/10-breeze-theme.conf` used to exist which was obviously broken, though I still wasn't able to test this successfully on an already booted install where I saw the fallback theme already once despite e.g. `dinitctl stop sddm && rm -r /var/lib/sddm/{.{cache,config,local},state.conf} && dinitctl start sddm` so this may need further confirmation it actually fixes the issue..
> main/sddm: fix broken 10-breeze-theme.conf location

- main/linux-rpi/patches/home-assistant-yellow.patch
I've cross built this after commenting out the `broken = [...]` section, and have set `device_tree=bcm2711-rpi-cm4-ha-yellow.dtb` in my `config.txt`. With those in place, the zigbee radio works in home-assistant, without further adjustments of the `config.txt`. I have reverted the rest to be like what `base-rpi` ships.
> main/linux-rpi: add Home Assistant Yellow device trees

- user/zellij/template.py
cc @denisstrizhkin
Re: dropped manpage, upstream has declared it outdated and doesn't want to maintain it.
> user/zellij: update to 0.41.2

- user/incus/template.py
gtar is necessary for incus to launch containers but not included as a dependency, and not installed in the base install.
> user/incus: Add gtar as dependency

- user/zrepl/files/tmpfiles.conf
- user/zrepl/files/zrepl
- user/zrepl/template.py
This is an enhanced fork of the original zrepl ZFS snapshot and replication daemon.
The package builds and works as expected on x86_64 and it contains everything that is needed to properly use on Chimera.
> user/zrepl-dsh2dsh: new package

- main/amdgpu_top/template.py
- main/perl-image-exiftool/template.py
- main/rust-analyzer/template.py
- main/tio/template.py
- main/wasm-component-ld/template.py
After @nekopsykose left the Chimera Linux project, I decided to update some orphaned packages. I chose these 5 packages randomly. I will not adopt those packages.
Updated packages:
* main/amdgpu_top (0.10.0)
* main/perl-image-exiftool (13.04)
* main/rust-analyzer (2024.12.02)
* main/tio (3.8)
* main/wasm-component-ld (0.5.11)
> Update amdgpu_top, perl-image-exiftool, rust-analyzer, tio, wasm-component-ld

- main/oksh/template.py
~~While this update builds and runs fine, a (hacky) change of build_wrksrc was required
due to what seems like a faulty tarball generation script adding unecessary symlinks
to stuff... weird~~
tarball was changed silently fixing the issue
> main/oksh: update to 7.6

- user/openttd/update.py
the original update check matched the last version in the file, regardless of what channel it was
the updated pattern only matches if the version is stable
i'm not sure whether i need to bump the pkgrel for a change like this, if yes please let me know and i'll do
> user/openttd: make update check only match stable versions

- main/lowdown/template.py
Also drops cfi since it contains a static library.
see: https://github.com/chimera-linux/cports/pull/3337
> main/lowdown: update to 1.4.0

- main/corrosion/template.py
Bump corrosion to 0.5.1. I have built all packages depending on corrosion with the new version, seems to still work.
> main/corrosion: update to 0.5.1

- main/foot/template.py
- main/utf8proc/patches/nostatic.patch
- main/utf8proc/template.py
as part of the ut8proc update also disables the build/install of the static library
since the whole library is built with cfi.
the patch could be reverted in favor of disabling cfi, but it remains unclear which option is better.
> main/foot: update to 1.20.0

- main/openpgp-card-tool-git/patches/0001-Update-stderr-of-test-case-to-match-new-expected-out.patch
- main/openpgp-card-tool-git/template.py
Bump oct-git to 0.1.5. The patch was discussed with upstream, this is caused by an update of a dep and updating the test case was missed.
> main/openpgp-card-tool-git: update to 0.1.5

- user/vgrep/template.py
acts as a pager for any stream in the grep result format.  the readme emphasizes
the fzf integration and the code checks for ripgrep before falling back on
git-grep or bare grep, so both were added as deps.
> user/vgrep: new package

- user/python-dbus-fast/patches/remove_codspeed.patch
- user/python-dbus-fast/patches/remove_pytest_cov.patch
- user/python-dbus-fast/template.py
I tried packaging codspeed too, but that would have required packaging:
python-codspeed -> python-rich -> python-markdown-it -> python-pytest-cov
and having tried to package pytest-cov before I know that I'm not going to get it working :/
> user/python-dbus-fast: update to 2.28.0

- user/b43-fwcutter/template.py
this package adds a tool that extracts firmware for broadcomm 43xx from proprietary drivers (notably needed to get wifi working on some powerpc macs)
i haven't packaged the firmware itself as there's no license so it probably can't be legally redistributed by itself
> user/b43-fwcutter: new package

- main/easyeffects/template.py
fixes `Error relocating /usr/bin/easyeffects: _ZN3fmt3v116detail10locale_refC1INSt3__16localeETnNS4_9enable_ifIXneszsrT_7collateLi0EEiE4typeELi0EEERKS7_: symbol not found`
> main/easyeffects: rebuild for fmt

- user/go-task/template.py
Cool tool, much like a modernized version of Makefiles with a focus towards running commands rather than compiling software.
The naming is not very consistent though; the project itself seems to call it `task` most of the time, but in other places, `go-task` is used more often. This is of course because it is such a generic name. To avoid conflict, it seemed wise to name the package go-task. What do you think of this?
> user/go-task: new package

- main/python-referencing/patches/python-3.12-support.patch
- main/python-referencing/template.py
The current `python-referencing` package uses a Python 3.13 feature, this patch is needed until we upgrade Python.
> main/python-referencing: make compatible with python3.12

- user/python-hjson/template.py
Adds https://github.com/hjson/hjson-py, needed for QMK keyboard firmware build tool
> user/python-hjson: new package

- user/python-pyusb/template.py
Add `pyusb` https://pypi.org/project/pyusb/ needed for qmk-cli keyboard firmware build tool
> user/python-pyusb: new package

- user/listenbrainz-mpd/template.py
This adds a new package called listenbrainz-mpd, which submits songs played by mpd to ListenBrainz for the user to track what songs they have listened to. This is my first contribution, so if I have made any errors, please let me know so that I can fix them ASAP.
Before submitting, I tested that the package built properly, that it worked in a Chimera Linux VM (ie it submitted songs using a working config file), and I formatted the template.py file with Black.
> user/listenbrainz-mpd: new package

- user/dmg2img/patches/openssl-1-1.patch
- user/dmg2img/template.py
this pr adds the dmg2img utility which is used to convert dmg files to standard disk image files (img)
> user/dmg2img: new package

- user/refine/patches/0001-keep-using-last-blueprint-compiler-version-available.patch
- user/refine/template.py
Update Refine package to the last version. Needs to patch `meson.build` to use `blueprint-compiler` v0.16.0 instead of the 0.14.0. According to the Refine main dev, Refine needs at least the v0.14.0.
> user/refine: update to 0.4.2

- main/python-numpy/template.py
> main/python-numpy: make tests depend on parent + checkdepends

- user/duperemove/patches/atomic-globals.patch
- user/duperemove/patches/delete-duplicate-definition.patch
- user/duperemove/patches/fix-cfi.patch
- user/duperemove/patches/remove-libbsd-dependency.patch
- user/duperemove/template.py
I've updated duperemove to v0.15, and I've moved it to the user repository as q66 asked on IRC.
It fails to build with clang if `delete-duplicate-definition.patch` isn't applied, but it somehow builds successfully with gcc. I don't know what's going on with this code, if the TODO was left undone by accident or what, but the patched version seems to work fine in practice. There's an issue in the upstream repository: https://github.com/markfasheh/duperemove/issues/367
> user/duperemove: move from main and update to 0.15

- main/ispc/template.py
- main/openimagedenoise/template.py
this update _might_ remove support for armv7, but [i'm not entirely certain](https://github.com/ispc/ispc/releases/tag/v1.26.0):
>- The `--arch=arm` flag, which previously mapped to ARMv7 (32-bit), now maps to ARMv8 (32-bit). There are no changes to `--arch=aarch64`, which continues to map to ARMv8 (64-bit).
>- The CPU definitions for the ARMv7 architecture have been removed: `cortex-a9` and `cortex-a15`.
>- New CPU definitions have been introduced, including `cortex-a55`, `cortex-a78`, `cortex-a510`, and `cortex-a520`, along with support for new Apple devices.
> main/ispc: update to 1.26.0

- user/opencc/template.py
- user/tclap/patches/fix-tests-shebang.patch
- user/tclap/template.py
This PR updates opencc to use system library (instead of bundled ones in repository), and enable tests for "check" phase. Another package "tclap" was also added with tests enabled.
> user/opencc: enable tests

- user/incus/template.py
Update to v6.9.0, required for compatibility with qemu 9.2.
- [ X] I have read [CONTRIBUTING.md](https://github.com/chimera-linux/cports/blob/master/CONTRIBUTING.md)
- [ X] I have read [Packaging.md](https://github.com/chimera-linux/cports/blob/master/Packaging.md#quality_requirements)
- [ X] I have built and tested my changes on my machine
Pkg builds and executes without issue on x86_64.
Note, cross build `./cbuild -a aarch64 pkg user/incus` fails with:
```
0:00:12.369 => incus-6.7.0-r4: golang: go build -p 8 -v -trimpath -tags libsqlite3 -o /builddir/incus-6.7.0/build/ ./cmd/...
package github.com/lxc/incus/v6/cmd/incusd
imports github.com/lxc/incus/v6/internal/server/db/warningtype: build constraints exclude all Go files in …
```
> user/incus: update to 6.9.0.

- user/forgejo/template.py
9.0.3 panics on go 1.24 with concurrent map read/write
> user/forgejo: update to 10.0.1

- user/pipectl/template.py
pipectl is a tool to create and manage short-lived named pipes.
This opens up a program's stdin to getting some commands for IPC
purposes, also optional dependency of wl-mirror.
> user/pipectl: new package

- user/python-hid/template.py
Adds the `hidapi` python wrapper, needed for qmk-cli keyboard firmware build tool
> user/python-hid: new package

- user/fonts-ibm-plex-mono-otf
- user/fonts-ibm-plex-mono-ttf
- user/fonts-ibm-plex-mono/template.py
- user/fonts-ibm-plex-mono/update.py
Adds a new font package IBM Plex Mono.
> user/fonts-ibm-plex-mono: new package

- user/neomutt/template.py
- user/neomutt/update.py
Seems to work fine with cfi except at quit when the cleanup code generates a SIGILL.
Pending a proper patch for that code, before (if no other issues pop up) a merge.
> user/neomutt: new package

- main/wlsunset/template.py
I somehow stumbled across the fact that wlsunset package's cross compilation is broken. Fix that with a trivial dependency fix.
> main/wlsunset: fix cross compilation

- user/sl/template.py
From the project's README:
> SL (Steam Locomotive) runs across your terminal when you type "sl" as you meant to type "ls". It's just a joke command, and not useful at all.
https://github.com/eyJhb/sl
> user/sl: new package

- user/i3status/patches/0001-Remove-failing-test.patch
- user/i3status/template.py
Although i3status-rust exists in main, i3status uses different configuration and has different features which users may prefer.
> user/i3status: new package

- user/fcitx5-rime/template.py
- user/leveldb-devel
- user/leveldb/patches/unbundle-gtest-and-benchmark.patch
- user/leveldb/template.py
- user/librime-data/template.py
- user/librime-data/update.py
- user/librime-devel
- user/librime-progs
- user/librime/template.py
This PR adds four packages to user repo. It adds rime Chinese input method library and fcitx5-rime for its use in fcitx5 input method frontend.
This is my first contribution to cports, so please tell if something is not handled properly. Here are things I have done:
1. Verify the package content (only list of filenames) against the alpine packages, and the result matches in general.
2. Install on my local machine and verify that these package work properly. 
3. Format with black code formatter.
4. Enabled "vis" and "cfi" hardening options by trial-and-error.
Among these four packages, the most controversial one is probably "rime-data".  This package contains the input method schema data for rime. But there is no official release for it, as it contains multiple git repositories, and each …
> user/fcitx5-rime: new package

- main/llvm-bootstrap/template.py
The mappings for armhf and armv7 were missing.
> main/llvm-bootstrap: add architecture mappings for 32-bit ARM

- main/boost/patches/fix-armv7-inline-assembly.patch
Boost uses inline assembly syntax that is rejected by LLVM for ARMv7. `%progbits` works on all targets and should be used here instead.
> main/boost: fix build for ARMv7

- main/fortify-headers/patches/ppoll-test-guards.patch
`ppoll` is not re-defined when `_REDIR_TIME64` is set, so the `ppoll` tests should be skipped in that case.
> main/fortify-headers: fix tests on 32-bit targets with _REDIR_TIME64

- main/doxygen/patches/xmllint-expected-xml.patch
- main/doxygen/template.py
doxygen's testsuite uses `xmllint`, which changed its behaviour in libxml2 2.14. To avoid breakage of the tests like this, let's run `xmllint` over the expected output files as well. This fixes all erroring tests except 1, which is because `xmllint` refuses to properly indent a closing tag. I disabled that test because I couldn't come up with an appropriate fix.
> main/doxygen: work around checks with libxml2-progs 2.14

- main/python-pexpect/template.py
This test currently times out on ARMv7, see the linked issue for details.
> main/python-pexpect: disable performance test on ARMv7

- main/wayland-protocols/template.py
Fails with missing symbols in pedantic tests just like riscv64 and loongarch64:
```
Summary of Failures:
76/156 test-build-pedantic-staging_cursor_shape_cursor_shape_v1_xml                                               FAIL            0.20s   exit status 127
80/156 test-build-pedantic-staging_ext_image_capture_source_ext_image_capture_source_v1_xml                       FAIL            0.17s   exit status 127
91/156 test-build-pedantic-staging_ext_image_copy_capture_ext_image_copy_capture_v1_xml                           FAIL            0.25s   exit status 127
105/156 test-build-pedantic-staging_xdg_dialog_xdg_dialog_v1_xml                                                   FAIL            0.21s   exit status 127
106/156 test-build-pedantic-staging_xdg_toplevel_drag_xdg_toplevel_drag_v1_xml …
```
> main/wayland-protocols: !check for armv7

- main/libucontext/patches/arm-hardfloat.patch
- main/libucontext/patches/arm-llvm.patch
The first patch fixes hardfloat support, the second patch fixes the assembly syntax. Since hardfloat was only disabled when using the Makefile, not when using Meson, we need that patch to pass the testsuite.
> main/libucontext: fix on ARMv7

- main/prosody/template.py
- main/prosody/update.py
also shadows the pkgver due to seemingly incorrect version tagging by upstream.
simply upgrading to version 13.0.0 will cause a regression in the next release cycle
forcing people to use --available/--prune to ignore the downgrade
> main/prosody: update to 0.13.0

- user/minijinja-cli/template.py
Update, and drop broken on 32-bit flag, as that was fixed upstream: https://github.com/mitsuhiko/minijinja/pull/755 (tested with ppc and armv7 cross-builds)
> user/minijinja-cli: update to 2.9.0

- main/http-parser/patches/dont-test-http_parser-size.patch
Testing for the size of the struct is not portable due to different alignments. This fixes tests on 32-bit ARM.
> main/http-parser: Patch out non-portable test

- main/chez-scheme/template.py
Tests take an eternity and then fail very cryptically on 32-bit ARM. Other distros don't run tests at all or only for aarch64 and x86_64, so this isn't too unreasonable.
> main/chez-scheme: disable checks on 32-bit ARM

- main/openexr/template.py
Test fails with bus error on ARMv7, same on Alpine so this is somewhat (?) expected. Remaining tests pass fine, so let's only disable this one.
> main/openexr: disable failing test on ARMv7

- main/libde265/patches/fix-arm-include-paths.patch
- main/libde265/patches/remove-.func-.endfunc-usage.patch
Patches should be self-explanatory. This fixes the include paths and removes unnecessary syntax not understood by the integrated assembler in clang.
> main/libde265: fix build for ARMv7

- main/libtpms/patches/10-fix-nvram_offsets-32bit-test.patch
This patch fixes tests on 32-bit targets like ARMv7.
> main/libtpms: fix checks on 32-bit targets

- main/python-munkres/patches/fix-32-bit-tests.patch
`sys.maxsize` differs between 32-bit and 64-bit targets, causing the test failure.
> main/python-munkres: fix tests on 32-bit targets

- main/snappy/patches/neon-only-64-bit.patch
Cherry-pick a fix that only enables NEON for 64-bit ARM since incompatible intrinsics are used.
> main/snappy: fix build for ARMv7

- user/hashcat/patches/check-hardware-crc-arm.patch
- user/hashcat/patches/check-hardware-sha-arm.patch
Currently they are force enabled, even if the target doesn't support them. The compiler sets defines for these, just make use of them.
> user/hashcat: fix ARM hardware feature checks

- main/gdk-pixbuf/template.py
They apparently fail on a bunch of 32-bit targets so it's fair to assume they fail on all.
> main/gdk-pixbuf: disable checks on 32-bit targets

- main/qemu-user/template.py
Trivial fix, `armv7` is `arm` in QEMU naming.
> main/qemu-user: fix installing binfmt configs for ARMv7

- main/ruby/patches/align-builtin-binaries-ibf_header.patch
The `builtin_binary` buffers are cast to `ibf_header` later, but may not be aligned to the necessary boundaries (in this case, 4 bytes). On ARMv7, they are unaligned, resulting in Ruby crashing. See https://godbolt.org/z/ss8WeE88c
> main/ruby: fix on ARMv7

- src/cbuild/hooks/pkg/001_runtime_deps.py
Fix mispelled `pkg_provies_svc`
> cbuild: fix mispelled invocation

- main/prosody/template.py
- main/prosody/update.py
it looks like the  earlier versioning tag change was not a fluke.
Thus version shadowing has also been dropped.
> main/prosody: update to 13.0.1

- main/gpgme/patches/time_t-is-64-bit.patch
This test assume 32-bit time_t behaviour.
> main/gpgme: don't assume 32-bit time in tests

- main/lagrange/neon-only-64-bit.patch
The code guarded by `#ifdef STBIR_NEON` uses 64-bit NEON intrinsics, so the conditions for enabling it are wrong. Just disable NEON outright on 32-bit targets.
> main/lagrange: fix build on ARMv7

- user/calcurse/patches/0001-Change-arg_print_date-argument-to-time_t.patch
- user/calcurse/patches/0002-gcc14-32-bit.patch
There was a bunch of misuse of `long` instead of `time_t` here, resulting in pointers to 64-bit integers crafted from 32-bit ones and therefore UB.
> user/calcurse: fix checks for 32-bit targets

- main/milkytracker/patches/cmake-fix.patch
This policy was removed in CMake 4.0.
> main/milkytracker: fix build with CMake 4.0

- user/micro/template.py
the editor was built without syntax highlighting files. to generate them, one needs to additionally run `go generate ./runtime` during build (their Makefile takes care of it but we don't use it)
- [n/a] I will take responsibility for my template and keep it up to date
---
<sup><sub>i copied the commit message [from alpine](https://git.alpinelinux.org/aports/commit/?id=20d1a8722b5600f9d3d6d341484ca4c135b284ce). hope nobody will be mad (ó﹏ò｡)</sub></sup>
> user/micro: generate syntax highlighting files

- main/mandoc/patches/no-reset-gzip.patch
- main/mandoc/template.py
setting curp->gzip to 0 disregarding the current value causes gzipped man pages to be shown without gunzipping them first, essentially printing garbage to stdout
> main/mandoc: don't reset gzip in mparse_reset

- main/mc/patches/ncurses-mouse.patch
- main/mc/template.py
Fix mouse-key garbage output on ncurses and modern terminals
Fix mouse-key input with ncurses6 in terminals without basic X10 mouse support, at the cost of breaking it with ncurses5. See discussion in:
https://github.com/MidnightCommander/mc/issues/4144
https://bugs.gentoo.org/753578
> main/mc: fix mouse-key garbage output on ncurses and modern terminals

- main/qemu/patches/fix-shutdown.patch
- main/qemu/template.py
dinit's shutdown binary doesn't take time and wall message parameters.
Adjust qemu-guest-agent call to make it to work fine on Chimera.
> main/qemu: adjust shutdown parameters

- main/rpi-boot/template.py
the kernel was bumped to 6.12.22 upstream which matches chimera's current kernel version for rpi
> main/rpi-boot: update to 1.20250407

- main/networkmanager/patches/pygobject-3.52.patch
Otherwise it'd error like this:
```
FAILED: src/libnm-client-impl/nm-settings-docs-gir-nmcli.xml
/usr/bin/env GI_TYPELIB_PATH=/builddir/networkmanager-1.52.0/build/src/libnm-client-impl LD_LIBRARY_PATH=/builddir/networkmanager-1.52.0/build/src/libnm-client-impl /usr/bin/python3 /builddir/networkmanager-1.52.0/tools/generate-docs-nm-settings-docs-gir.py --lib-path /builddir/networkmanager-1.52.0/build/src/libnm-client-impl --gir src/libnm-client-impl/NM-1.0.gir --output src/libnm-client-impl/nm-settings-docs-gir-nmcli.xml --target nmcli
Traceback (most recent call last):
File "/builddir/networkmanager-1.52.0/tools/generate-docs-nm-settings-docs-gir.py", line 13, in <module>
gi.require_version("GIRepository", "2.0")
~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> main/networkmanager: fix build with pygobject 3.52

- main/debianutils/template.py
5.21 has disappeared from the source.
> main/debianutils: update to 5.22

- main/wasi-libc/patches/no-double-build.patch
- main/wasi-libc/template.py
After the LLVM 20 update this failed to build.
> main/wasi-libc: update for llvm 20

- main/capnproto/template.py
We can still run the other tests, better than disabling them all.
> main/capnproto: skip failing test on ARMv7

- main/zxing-cpp-progs
- main/zxing-cpp/template.py
It was disabled in 100dcb6fe4e3e9e253c53f18b4273939ca20a8d8 commit.
Debian and Alpine both provide those programs.
* https://packages.debian.org/sid/amd64/zxing-cpp-tools/filelist
* https://pkgs.alpinelinux.org/contents?name=zxing&repo=community&branch=edge&arch=x86_64
> main/zxing-cpp: Build reader and write programs

- user/widle/template.py
`widle(1)` is a program that runs a command when a user has idled. This functionality is useful for screenlocking with a program like `wlock(1)` .
> user/widle: new package

- user/libyang/template.py
Without it, libyang.pc is not installed and FRR will not find it
Basically what commit message says.  I'm working on FRR cport and it needs libyang.pc to find and use it.
> user/libyang: add pkgconf dependency

- user/maim/template.py
CFI hardening caused SIGILL when trying to take a screenshot, so I removed it. CMake 4.0+ removed compatibility with CMake <3.5, so minimum version was also bumped to fix the build
> user/maim: fix SIGILL and CMake error

- main/chromium/template.py
Test-built on `aarch64` (X1E laptop) and runs on my end:
```
5:09:43.682 => chromium-137.0.7151.55-r0: finished phase 'build'
```
[ci skip]
> main/chromium: drop unneeded extra flags for modern LLVM

- main/ffmpeg/patches/vapoursynth-script.patch
- main/ffmpeg/template.py
otherwise using vapoursynth scripts with ffmpeg requires vapoursynth-devel installed
i was initially going to move the unversioned .so from `vapoursynth-devel` to `vapoursynth` but then i thought that fixing this in ffmpeg is maybe a better idea
> main/ffmpeg: don't use unversioned libvapoursynth-script.so

- main/python-hypothesis/template.py
Updates python-hypothesis. This fixes the test cases failing with later pytest versions.
> main/python-hypothesis: update to 6.135.14

- main/mingw-w64-crt/template.py
- main/mingw-w64-headers/template.py
- main/mingw-w64-winpthreads/template.py
Unset CPP environment variable for mingw-w64-crt to fix the following error.
clang-cpp: error: unsupported option '-mfpu=' for target 'x86_64-chimera-linux-musl'
> main/mingw-w64-*: update to 13.0.0

- main/rust/template.py
Edition 2024 prohibits extern blocks without unsafe.
> main/rust: fix bootstrapping with 1.87

- user/selene/template.py
Otherwise we would see
```
thread 'validate_config::tests::validate_config_tests' panicked at /usr/lib/rustlib/src/rust/library/core/src/panicking.rs:218:5:
unsafe precondition(s) violated: ptr::copy_nonoverlapping requires that both pointer arguments are aligned and non-null and the specified memory ranges do not overlap
This indicates a bug in the program. This Undefined Behavior check is optional, and cannot be relied on for safety.
```
in tests and probably any invocation.
> user/selene: fix crash on 32-bit targets

- user/agate/files/sysusers.conf
- user/agate/files/tmpfiles.conf
- user/agate/template.py
updated agate to 3.3.17
added sysusers.conf and tmpfiles.conf for the agate service
a dinit service file was not added because agate needs some user defined state (hostname, a content directory) to get started
> user/agate: update to 3.3.17

- user/rgbds/template.py
New package: rgbds
This is an assembler and linker for gameboy and gameboy color
- [X ] I have read [CONTRIBUTING.md](https://github.com/chimera-linux/cports/blob/master/CONTRIBUTING.md)
- [X ] I have read [Packaging.md](https://github.com/chimera-linux/cports/blob/master/Packaging.md#quality_requirements)
- [X ] I have built and tested my changes on my machine
> New package: rgbds

- main/git/template.py
updated git to 2.50.1, disabled some tests that are failing, the bash-completion file is now installed using the Makefile provided by the package
> main/git: update to 2.50.1

- user/xh/template.py
- add missing `xhs` symlink
- use openssl instead of rustls
> user/xh: add xhs link, use openssl

- user/gdu/template.py
updated gdu to `5.31.0`, skip additional tests that fail, add version information, avoid installing unnecessary `build.go` file in `make_dir`
> user/gdu: update to 5.31.0

- main/libinput/patches/atou64-fix.patch
- main/libinput/patches/duplicate-sizeof.patch
- main/libinput/patches/litest-constants-32bit.patch
- main/libinput/template.py
Fixes all test failures on ARMv7. Two patches are cherry-picked from upstream, one is mine that I cannot submit upstream because freedesktop.org is I guess too restrictive about my account age (?).
> main/libinput: Fix tests on 32-bit targets

- user/zellij/template.py
The new web client feature uses rustls and builds aws-libcrypto, just as a heads-up if we want to disable it.
> user/zellij: update to 0.43.0

- user/darkman/files/darkman.user
- user/darkman/template.py
[`darkman`](https://gitlab.com/WhyNotHugo/darkman) runs user-defined scripts at sunrise and sunset (based on your location derived via `geoclue` or manually specified coordinates), to automatically toggle "light mode" and "dark mode"
> user/darkman: new package

- user/nushell-plugin-formats
- user/nushell-plugin-gstat
- user/nushell-plugin-inc
- user/nushell-plugin-polars
- user/nushell-plugin-query
- user/nushell/template.py
- Update nushell to 0.106.1
- Package [core plugins](https://www.nushell.sh/book/plugins.html#core-plugins) as subpackages.
- Automatically load plugins if they are installed
Changes are based on #4587
> user/nushell: update to 0.106.1 and include core plugins as subpackages

- user/gotosocial/template.py
updated gotosocial to 0.19.2
The source URL was changed to codeberg because the project home page points to it and releases are made first on Codeberg and then on GitHub.
> user/gotosocial: update to 0.19.2

- user/bettercap/template.py
bettercap is a Swiss Army knife for WiFi, Bluetooth Low Energy, wireless HID hijacking, CAN-bus and IPv4 and IPv6 networks reconnaissance and MITM attacks.
> user/bettercap: new package

- main/rabbitmq-c/template.py
cfi conflicts with static libraries, and they are needed for tests
> main/rabbitmq-c: fix build by disabling cfi
