main/grub/template.py
main/klibc/template.py

with these, I was able to fully rebuild `main/base-full`, `main/linux` and `main/grub`.

fixes on main/kblibc and main/grub

---

Usage.md

Just a few small things I thought would be nice :)

Fixup Usage.md document

---

contrib/wlsunset/template.py

A redshift alternative for Wayland.
Super easy and straightforward to package. :+1:

contrib/wlsunset: new package (0.3.0)

---

contrib/tree/template.py

Another screwy Makefile, please check if there's a better way of handling this one. :)

contrib/tree: new package (2.1.1)

---

src/runner.py

Closes https://github.com/chimera-linux/cports/issues/220.

cbuild: fix CBUILD_BWRAP_PATH typo

---

contrib/catgirl/template.py
contrib/libretls-devel
contrib/libretls/template.py

not sure how to best extract the header licence if really needed

contrib/catgirl: new package (2.2)

---

contrib/sshfs/patches/no-lnr.patch
contrib/sshfs/template.py

technically this is archived now, but nobody else has picked it up yet. there's no other tools to use ssh fuse like this that i know of and it still works for now..

contrib/sshfs: new package (3.7.3)

---

contrib/foot/template.py

https://codeberg.org/dnkl/foot/releases/tag/1.15.3

contrib/foot: update to 1.15.3

---

main/musl/template.py

this actually works fine on itself and was fixed by 1.2.4

main/musl: don't block relr

---

main/less/template.py

https://greenwoodsoftware.com/less/news.643.html

main/less: update to 643

---

contrib/pipx/template.py
contrib/python-argcomplete/template.py
contrib/python-colorama/template.py
contrib/python-userpath/template.py

would be nice to have the SETUPTOOLS_SCM pretention be a global env when python

contrib/pipx: new package (1.2.0)

---

src/cbuild/spdx/README.md
src/cbuild/spdx/exceptions.json
src/cbuild/spdx/licenses.json

cbuild: update spdx licences to 3.21

---

main/util-linux/template.py

https://marc.info/?l=util-linux-ng&m=169226436109352&w=2

main/util-linux: update to 2.39.2

---

main/libsndfile/template.py

https://github.com/libsndfile/libsndfile/releases/tag/1.2.1  
https://github.com/libsndfile/libsndfile/releases/tag/1.2.2

main/libsndfile: update to 1.2.2

---

main/kbd/template.py

https://github.com/legionus/kbd/releases/tag/v2.6.2

main/kbd: update to 2.6.2

---

main/python-wheel/template.py

https://github.com/pypa/wheel/blob/2bf5bb07eed8a5844cee5d5ceef55934146b6981/docs/news.rst

main/python-wheel: update to 0.41.1

---

main/python-setuptools/template.py

https://github.com/pypa/setuptools/blob/71b355ba8fcbb9341364699375ee786100b3cf75/NEWS.rst

main/python-setuptools: update to 68.1.0

---

main/libxcb/template.py
main/xcbproto/template.py

https://lists.x.org/archives/xorg-announce/2023-August/003415.html  
https://lists.x.org/archives/xorg-announce/2023-August/003414.html

main/libxcb: update to 1.16

---

main/fuse/template.py

https://github.com/libfuse/libfuse/releases/tag/fuse-3.16.1

main/fuse: update to 3.16.1

---

main/xdg-dbus-proxy/template.py

https://github.com/flatpak/xdg-dbus-proxy/releases/tag/0.1.5

main/xdg-dbus-proxy: update to 0.1.5

---

main/perl-authen-sasl/template.py

https://metacpan.org/release/EHUELS/Authen-SASL-2.1700/source/Changes

main/perl-authen-sasl: update to 2.1700

---

main/libxmlb/template.py

https://github.com/hughsie/libxmlb/releases/tag/0.3.12

main/libxmlb: update to 0.3.12

---

contrib/weechat/template.py

https://github.com/weechat/weechat/releases/tag/v4.0.3

contrib/weechat: update to 4.0.3

---

main/vala/template.py

https://gitlab.gnome.org/GNOME/vala/-/blob/0a4a679270bdb413b4f7d3e759e129ec65597d29/NEWS

main/vala: update to 0.56.11

---

main/zenity/template.py

https://gitlab.gnome.org/GNOME/zenity/-/blob/e9a591aa1d182e220013d9ab50dcc7607734d7b1/NEWS

main/zenity: update to 3.44.2

---

contrib/gtkmm3.0/template.py

https://gitlab.gnome.org/GNOME/gtkmm/-/blob/0d17c5fd0bde56eff6258d5a3aa966ca64d0b90c/NEWS

contrib/gtkmm3.0: update to 3.24.8

---

main/gnome-bluetooth/template.py

https://gitlab.gnome.org/GNOME/gnome-bluetooth/-/blob/3c20e804b86775c26f0a9be370605aac5bfa230b/NEWS

main/gnome-bluetooth: update to 42.6

---

main/gnome-console/template.py

https://gitlab.gnome.org/GNOME/console/-/blob/48d913ed91690531c0ea307fa6700799cd2383d5/NEWS

main/gnome-console: update to 44.4

---

main/python-setuptools/template.py

https://github.com/pypa/setuptools/blob/fdfe7118c0b41ebabf807d5869171f374c66afeb/NEWS.rst

main/python-setuptools: update to 68.1.2

---

main/libxmlb/template.py

https://github.com/hughsie/libxmlb/releases/tag/0.3.13

main/libxmlb: update to 0.3.13

---

main/imlib2/template.py

https://git.enlightenment.org/old/legacy-imlib2/src/commit/5300f19575f10047e7cd038bfc7d612304be23b1/ChangeLog

main/imlib2: update to 1.12.0

---

main/pkgconf/template.py

https://github.com/pkgconf/pkgconf/blob/eaa4bb44a00e65be8014a3f532bf91c5b7898c81/NEWS

main/pkgconf: update to 2.0.2

---

main/zlib/template.py

https://github.com/madler/zlib/releases/tag/v1.3

main/zlib: update to 1.3

---

main/python-click/template.py

https://click.palletsprojects.com/en/8.1.x/changes/#version-8-1-7

main/python-click: update to 8.1.7

---

main/python-pygments/template.py

https://github.com/pygments/pygments/releases/tag/2.16.0  
https://github.com/pygments/pygments/releases/tag/2.16.1

main/python-pygments: update to 2.16.1

---

main/python-fonttools/template.py

https://github.com/fonttools/fonttools/releases/tag/4.42.1

main/python-fonttools: update to 4.42.1

---

contrib/buildkit/files/buildkitd
contrib/buildkit/template.py

depends on https://github.com/chimera-linux/cports/pull/274

contrib/buildkit: new package (0.12.1)

---

contrib/qemu-user/template.py
contrib/qemu/template.py

https://wiki.qemu.org/ChangeLog/8.1

contrib/qemu: update to 8.1.0

---

contrib/weechat/template.py

https://github.com/weechat/weechat/releases/tag/v4.0.4

contrib/weechat: update to 4.0.4

---

main/libdrm/template.py

https://lists.x.org/archives/xorg-announce/2023-August/003416.html

main/libdrm: update to 2.4.116

---

main/appstream/template.py

https://github.com/ximion/appstream/blob/fdba45478fdcf38d128bc927ee0016079d72120f/NEWS

main/appstream: update to 0.16.3

---

main/python-wheel/template.py

https://github.com/pypa/wheel/blob/e76040b0d970a0fe6211c31888fc929078ba02d9/docs/news.rst

main/python-wheel: update to 0.41.2

---

main/perl-uri/template.py

https://metacpan.org/release/OALDERS/URI-5.21/source/Changes

main/perl-uri: update to 5.21

---

main/sqlite/template.py

main/sqlite: update to 3.43.0

---

main/libinput/template.py

https://lists.freedesktop.org/archives/wayland-devel/2023-August/042967.html

main/libinput: update to 1.24.0

---

main/xserver-xorg-input-libinput/template.py

https://lists.x.org/archives/xorg-announce/2023-August/003417.html

main/xserver-xorg-input-libinput: update to 1.4.0

---

main/libxmlb/template.py

https://github.com/hughsie/libxmlb/releases/tag/0.3.14

main/libxmlb: update to 0.3.14

---

contrib/python-setuptools-rust/patches/no-typing-ext.patch
contrib/python-setuptools-rust/template.py

https://github.com/PyO3/setuptools-rust/releases/tag/v1.7.0

contrib/python-setuptools-rust: update to 1.7.0

---

contrib/colordiff/template.py

contrib/colordiff: new package (1.0.21)

---

main/ccache/template.py

https://ccache.dev/releasenotes.html#_ccache_4_8_3

main/ccache: update to 4.8.3

---

main/freetype-bootstrap/template.py
main/freetype/template.py

https://gitlab.freedesktop.org/freetype/freetype/-/blob/VER-2-13-2/docs/CHANGES

main/freetype: update to 2.13.2

---

main/python-pluggy/template.py

https://github.com/pytest-dev/pluggy/blob/0b41c9766508a46ae666cf281684df3164b3e2a9/CHANGELOG.rst

main/python-pluggy: update to 1.3.0

---

main/nss/template.py

https://firefox-source-docs.mozilla.org/security/nss/releases/nss_3_93.html

main/nss: update to 3.93

---

main/nuspell/template.py

https://github.com/nuspell/nuspell/releases/tag/v5.1.3

main/nuspell: update to 5.1.3

---

main/libwacom/template.py

https://github.com/linuxwacom/libwacom/releases/tag/libwacom-2.8.0

main/libwacom: update to 2.8.0

---

main/sdl/template.py

https://github.com/libsdl-org/SDL/releases/tag/release-2.28.3

main/sdl: update to 2.28.3

---

main/libaom/template.py

https://aomedia.googlesource.com/aom/+/029c5669aa437367a1e75b418b2c12b586bb246e/CHANGELOG

main/libaom: update to 3.7.0

---

main/procps/patches/musl.patch
main/procps/template.py

https://gitlab.com/procps-ng/procps/-/blob/4ddcef2fd843170c8e2d59a83042978f41037a2b/NEWS

main/procps: update to 4.0.4

---

main/dhcpcd/template.py

main/dhcpcd: set !vis to fix udev.so plugin

---

main/pkgconf/template.py

https://github.com/pkgconf/pkgconf/blob/a6fb59a0ed86cfe302a2916cf93e9b032b95c8c5/NEWS

main/pkgconf: update to 2.0.3

---

main/libblockdev/template.py

https://github.com/storaged-project/libblockdev/blob/38378931d285b91333ff2e2a391b1fe91072f9bb/NEWS.rst

main/libblockdev: update to 3.0.3

---

main/python-build/template.py

https://github.com/pypa/build/releases/tag/1.0.0

main/python-build: update to 1.0.0

---

main/python-pytest/template.py

https://docs.pytest.org/en/latest/changelog.html#pytest-7-4-1-2023-09-02

main/python-pytest: update to 7.4.1

---

main/dbus/template.py

https://gitlab.freedesktop.org/dbus/dbus/-/blob/c4aebcdfa6458c3bb85bc4b01aa76a28c7e45d7f/NEWS

main/dbus: update to 1.14.10

---

main/strace/template.py

https://github.com/strace/strace/releases/tag/v6.5

main/strace: update to 6.5

---

main/unbound/template.py

https://nlnetlabs.nl/projects/unbound/download/#unbound-1-18-0

main/unbound: update to 1.18.0

---

main/doxygen/template.py

https://www.doxygen.nl/manual/changelog.html#log_1_9_8

main/doxygen: update to 1.9.8

---

contrib/nodejs/template.py

https://github.com/nodejs/node/releases/tag/v20.6.0

contrib/nodejs: update to 20.6.0

---

main/libsecret/template.py

https://gitlab.gnome.org/GNOME/libsecret/-/blob/8bbdfa36448036579f46b2f4464fd4cd47eaab2f/NEWS

main/libsecret: update to 0.21.0

---

main/libadwaita/template.py

https://gitlab.gnome.org/GNOME/libadwaita/-/blob/e006737320804ddeba28eb00228fe2c25d545a6a/NEWS

main/libadwaita: update to 1.3.5

---

main/libarchive/template.py

since we rename (not symlink) the bins
could also symlink these i guess

main/libarchive: also rename bsdcpio/bsdtar mans

---

main/btrfs-progs/template.py
main/btrfs-progs/update.py

https://github.com/kdave/btrfs-progs/releases/tag/v6.5

main/btrfs-progs: update to 6.5

---

main/libportal/template.py

https://github.com/flatpak/libportal/releases/tag/0.7

main/libportal: update to 0.7

---

main/iproute2/template.py

https://marc.info/?l=linux-netdev&m=169401822317373&w=2

main/iproute2: update to 6.5.0

---

main/libcloudproviders/template.py

https://gitlab.gnome.org/World/libcloudproviders/-/blob/141fb072cc5080a8c547b8a536a45c0f9cf65691/CHANGELOG

main/libcloudproviders: update to 0.3.4

---

main/python-build/template.py

https://github.com/pypa/build/releases/tag/1.0.3

main/python-build: update to 1.0.3

---

main/python-pyelftools/template.py

https://github.com/eliben/pyelftools/blob/f0f99814a564d9aa2dca7e8d145d180fa29160cc/CHANGES

main/python-pyelftools: update to 0.30

---

main/udisks/template.py

https://github.com/storaged-project/udisks/blob/udisks-2.10.1/NEWS

main/udisks: update to 2.10.1

---

main/font-util/template.py

https://lists.x.org/archives/xorg-announce/2023-September/003418.html

main/font-util: update to 1.4.1

---

contrib/nodejs/template.py

https://github.com/nodejs/node/releases/tag/v20.6.1

contrib/nodejs: update to 20.6.1

---

main/python-pytest/template.py

https://github.com/pytest-dev/pytest/releases/tag/7.4.2

main/python-pytest: update to 7.4.2

---

main/python-black/template.py

https://github.com/psf/black/releases/tag/23.9.0

main/python-black: update to 23.9.0

---

main/python-setuptools/template.py

https://github.com/pypa/setuptools/blob/0120605db966af66207d996b82320ee676fabbf1/NEWS.rst

main/python-setuptools: update to 68.2.1

---

main/sqlite/template.py

https://www.sqlite.org/releaselog/3_43_1.html

main/sqlite: update to 3.43.1

---

main/libarchive/template.py

https://github.com/libarchive/libarchive/releases/tag/v3.7.2

main/libarchive: update to 3.7.2

---

main/libportal/template.py

https://github.com/flatpak/libportal/releases/tag/0.7.1

main/libportal: update to 0.7.1

---

main/python-gobject/template.py

https://gitlab.gnome.org/GNOME/pygobject/-/blob/a46b22160c1924f93b033a91bc3417083a9fa0a8/NEWS

main/python-gobject: update to 3.46.0

---

main/curl/template.py

https://curl.se/changes.html#8_3_0

main/curl: update to 8.3.0

---

main/ghostscript/template.py

https://ghostscript.readthedocs.io/en/gs10.02.0/News.html

main/ghostscript: update to 10.02.0

---

main/libtiff/template.py

https://gitlab.com/libtiff/libtiff/-/releases/v4.6.0

main/libtiff: update to 4.6.0

---

main/librsvg/template.py

https://gitlab.gnome.org/GNOME/librsvg/-/blob/79d44da2e1b45b483a41af89f28ec98daf13ab19/NEWS

main/librsvg: update to 2.56.4

---

main/font-unifont-bdf/template.py

https://lists.gnu.org/archive/html/info-gnu/2023-09/msg00001.html

main/font-unifont-bdf: update to 15.1.01

---

main/geoclue/template.py

https://gitlab.freedesktop.org/geoclue/geoclue/-/blob/8a24f60969d4c235d9918796c38a6a9c42e10131/NEWS

main/geoclue: update to 2.7.1

---

contrib/bolt/template.py

https://gitlab.freedesktop.org/bolt/bolt/-/blob/f03c50b22ae3fda26711ddabd91e2c5dd8103478/CHANGELOG.md

contrib/bolt: update to 0.9.6

---

main/libwebp/template.py

https://github.com/webmproject/libwebp/blob/ca332209cb5567c9b249c86788cb2dbf8847e760/NEWS

main/libwebp: update to 1.3.2

---

main/libva-bootstrap/template.py
main/libva-utils/template.py
main/libva/template.py

https://github.com/intel/libva/blob/6b784c73f96680c92b93470484b7cbd9bd6318c7/NEWS  
https://github.com/intel/libva-utils/blob/81eed6e0045657a723ad8f84d4fe4c91b08db7b1/NEWS

main/libva-bootstrap: upgrade to 2.20.0

---

contrib/libmediainfo/template.py
contrib/mediainfo/template.py

https://github.com/MediaArea/MediaInfoLib/releases/tag/v23.09

contrib/mediainfo: upgrade to 23.09

---

main/gettext/template.py

https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob;f=NEWS;h=7d21b1d10cfca44bb4783ad072f272a4f28391a1;hb=ed9c5b76780b0fa8aa30d5fc665ce35d0df78f24

main/gettext: update to 0.22.2

---

main/python-setuptools_scm/patches/no-rich.patch
main/python-setuptools_scm/template.py

https://github.com/pypa/setuptools_scm/releases/tag/v8.0.0  
https://github.com/pypa/setuptools_scm/releases/tag/v8.0.1

main/python-setuptools_scm: update to 8.0.1

---

main/python-pillow/template.py

https://github.com/python-pillow/Pillow/releases/tag/10.0.1

main/python-pillow: update to 10.0.1

---

main/json-glib/template.py

https://gitlab.gnome.org/GNOME/json-glib/-/blob/52f7bdcd9ce9fc7e05bb185e418666e0685293d5/NEWS

main/json-glib: update to 1.8.0

---

main/mesa/template.py

https://lists.freedesktop.org/archives/mesa-announce/2023-September/000730.html

main/mesa: update to 23.1.8

---

main/kbd/template.py

https://github.com/legionus/kbd/releases/tag/v2.6.3

main/kbd: update to 2.6.3

---

main/gobject-introspection/template.py

https://gitlab.gnome.org/GNOME/gobject-introspection/-/blob/a0e8c17fcf58c6ea79f2887fa7d9f2b180f152b1/NEWS

main/gobject-introspection: update to 1.78.1

---

main/xwayland/template.py

https://lists.x.org/archives/xorg-announce/2023-September/003420.html

main/xwayland: update to 23.2.1

---

main/libsoup/template.py

https://gitlab.gnome.org/GNOME/libsoup/-/blob/007f59ff142e2781cd169a49925e54b9a5aa91da/NEWS

main/libsoup: update to 3.4.3

---

main/gst-libav/template.py
main/gst-plugins-bad/template.py
main/gst-plugins-base/template.py
main/gst-plugins-good/template.py
main/gstreamer/template.py

https://lists.freedesktop.org/archives/gstreamer-announce/2023-September/000548.html

main/gstreamer: upgrade to 1.22.6

---

main/harfbuzz/template.py

https://github.com/harfbuzz/harfbuzz/releases/tag/8.2.1

main/harfbuzz: update to 8.2.1

---

main/libuninameslist/template.py

https://github.com/fontforge/libuninameslist/releases/tag/20230916

main/libuninameslist: update to 20230916

---

contrib/cbindgen/template.py

https://github.com/mozilla/cbindgen/releases/tag/0.26.0

contrib/cbindgen: update to 0.26.0

---

contrib/nodejs/template.py

https://github.com/nodejs/node/releases/tag/v20.7.0

contrib/nodejs: update to 20.7.0

---

main/cups/template.py

https://github.com/OpenPrinting/cups/releases/tag/v2.4.7

main/cups: update to 2.4.7

---

main/gtk4/template.py

https://gitlab.gnome.org/GNOME/gtk/-/blob/f814b2f636c111fb79d00290b08366973122ca80/NEWS

main/gtk4: update to 4.12.2

---

contrib/thunderbird/template.py

https://www.thunderbird.net/en-US/thunderbird/115.2.3/releasenotes/

contrib/thunderbird: update to 115.2.3

---

main/python-setuptools_scm/patches/no-rich.patch
main/python-setuptools_scm/template.py

https://github.com/pypa/setuptools_scm/releases/tag/v8.0.2  
https://github.com/pypa/setuptools_scm/releases/tag/v8.0.3

main/python-setuptools_scm: update to 8.0.3

---

main/bc-gh/template.py

https://github.com/gavinhoward/bc/releases/tag/6.6.1

main/bc-gh: update to 6.6.1

---

main/imlib2/template.py

https://git.enlightenment.org/old/legacy-imlib2/commit/9198db25369f04db069ce61a661c3c47b2622655

main/imlib2: update to 1.12.1

---

contrib/qemu-user/template.py
contrib/qemu/template.py

https://lists.gnu.org/archive/html/qemu-devel/2023-09/msg05695.html

contrib/qemu: upgrade to 8.1.1

---

contrib/nodejs/template.py

https://github.com/nodejs/node/releases/tag/v20.8.0

contrib/nodejs: update to 20.8.0

---

contrib/qt6-qt5compat/template.py
contrib/qt6-qtbase/template.py
contrib/qt6-qtdeclarative/template.py
contrib/qt6-qtshadertools/template.py
contrib/qt6-qtsvg/template.py
contrib/qt6-qttools/template.py
contrib/qt6-qtwayland/template.py

https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.5.3/release-note.md

contrib/qt6-*: update to 6.5.3

---

main/sdl/template.py

https://github.com/libsdl-org/SDL/releases/tag/release-2.28.4

main/sdl: update to 2.28.4

---

contrib/yt-dlp/patches/pip-check.patch
contrib/yt-dlp/template.py

https://github.com/yt-dlp/yt-dlp/releases/tag/2023.09.24

contrib/yt-dlp: update to 2023.09.24

---

main/bluez-headers/template.py
main/bluez/template.py

https://github.com/bluez/bluez/releases/tag/5.70

main/bluez: update to 5.70

---

main/fluidsynth/template.py

https://github.com/FluidSynth/fluidsynth/releases/tag/v2.3.4

main/fluidsynth: update to 2.3.4

---

main/meson/template.py

https://github.com/mesonbuild/meson/compare/1.2.1...1.2.2

main/meson: update to 1.2.2

---

main/gtk4/template.py

https://gitlab.gnome.org/GNOME/gtk/-/blob/02a94c94628fae1363fd1b3e862493c5f3225319/NEWS

main/gtk4: update to 4.12.3

---

main/ffmpeg/template.py
main/libplacebo/template.py
main/mpv/template.py

https://github.com/haasn/libplacebo/releases/tag/v6.338.0

main/libplacebo: update to 6.338.0

---

contrib/weechat/template.py

https://github.com/weechat/weechat/releases/tag/v4.0.5

contrib/weechat: update to 4.0.5

---

main/cairomm/template.py

https://gitlab.freedesktop.org/cairo/cairomm/-/blob/e0bad547705348657d09db4c9375833d8890cf54/NEWS

main/cairomm: update to 1.18.0

---

contrib/cairomm1.0/template.py

https://gitlab.freedesktop.org/cairo/cairomm/-/blob/669e87a460bca3fa8d57cdaeac70bff183636354/NEWS

contrib/cairomm1.0: update to 1.14.5

---

contrib/qt6ct/template.py

https://github.com/trialuser02/qt6ct/releases/tag/0.9

contrib/qt6ct: update to 0.9

---

main/rust-bindgen/template.py

https://github.com/rust-lang/rust-bindgen/blob/4f8709f8653b54c481653e5fbff213cae0dde53f/CHANGELOG.md#0681

main/rust-bindgen: update to 0.68.1

---

contrib/alacritty/template.py

https://github.com/alacritty/alacritty/releases/tag/v0.12.3

contrib/alacritty: update to 0.12.3

---

contrib/gamescope/template.py
contrib/mesa-demos/template.py
contrib/pcsx2/template.py
contrib/qt6-qtbase/template.py
contrib/wine/template.py
contrib/wlroots/template.py
main/ffmpeg/template.py
main/gst-plugins-bad/template.py
main/gtk4/template.py
main/libplacebo/template.py
main/mesa/template.py
main/mpv/template.py
main/sdl/template.py
main/vulkan-headers/template.py
main/vulkan-loader-devel
main/vulkan-loader/template.py
main/vulkan-tools/template.py

also separates the vulkan-loader .pc and cmake files

main/vulkan: update to 1.3.265

---

main/python-fonttools/template.py

https://github.com/fonttools/fonttools/releases/tag/4.43.0

main/python-fonttools: update to 4.43.0

---

main/openssl/template.py

https://www.openssl.org/news/openssl-3.1-notes.html

main/openssl: update to 3.1.3

---

main/xxhash/template.py

also fix the check while at it

main/xxhash: add runtime dispatch on x86_64

---

contrib/virglrenderer/template.py

https://gitlab.freedesktop.org/virgl/virglrenderer/-/releases/1.0.0

contrib/virglrenderer: update to 1.0.0

---

main/libx11/template.py
main/libxpm/template.py

https://lists.x.org/archives/xorg-announce/2023-October/003425.html  
https://lists.x.org/archives/xorg-announce/2023-October/003426.html  
https://lists.x.org/archives/xorg-announce/2023-October/003424.html

main/libx11,libxpm: update

---

main/python-platformdirs/template.py

https://github.com/platformdirs/platformdirs/releases/tag/3.11.0

main/python-platformdirs: update to 3.11.0

---

main/python-setproctitle/template.py

https://github.com/dvarrazzo/py-setproctitle/compare/version-1.3.2...version-1.3.3

main/python-setproctitle: update to 1.3.3

---

main/python-packaging/template.py

https://github.com/pypa/packaging/releases/tag/23.2

main/python-packaging: update to 23.2

---

main/python-babel/template.py

https://github.com/python-babel/babel/releases/tag/v2.13.0

main/python-babel: update to 2.13.0

---

main/nss/template.py

https://firefox-source-docs.mozilla.org/security/nss/releases/nss_3_94.html

main/nss: update to 3.94

---

main/btrfs-progs/template.py

https://github.com/kdave/btrfs-progs/releases/tag/v6.5.2

main/btrfs-progs: update to 6.5.2

---

main/dav1d/template.py

https://code.videolan.org/videolan/dav1d/-/blob/48035599cdd4e4415732e408c407e0c1cd1c7444/NEWS

main/dav1d: update to 1.3.0

---

main/libcbor-devel
main/libcbor/template.py
main/libfido2-devel
main/libfido2-progs
main/libfido2/template.py
main/openssh/patches/defaults.patch
main/openssh/template.py

also includes drop-in conf files  
https://lists.mindrot.org/pipermail/openssh-unix-announce/2023-October/000154.html

main/openssh: update to 9.5p1

---

contrib/thinkfan/files/thinkfan
contrib/thinkfan/template.py
contrib/yaml-cpp-devel
contrib/yaml-cpp/template.py

My first packages :wave: 
https://github.com/vmatare/thinkfan and its dependency https://github.com/jbeder/yaml-cpp

contrib/thinkfan: new package (1.3.1) ← dep: contrib/yaml-cpp: new package (0.8.0)

---

contrib/power-profiles-daemon/files/power-profiles-daemon
contrib/power-profiles-daemon/template.py

contrib/power-profiles-daemon: new package (0.13)

---

main/bc-gh/template.py

https://github.com/gavinhoward/bc/releases/tag/6.7.0

main/bc-gh: update to 6.7.0

---

main/kmod/template.py

https://lore.kernel.org/linux-modules/lnbkvt5hhvgksgjqko7t6niw6uzr5ewjp32wyy2s26rzwdgh2y@l775iv6f6tkz/T/#u

main/kmod: update to 31

---

main/libtirpc/template.py

https://sourceforge.net/p/libtirpc/mailman/message/42287471/

main/libtirpc: update to 1.3.4

---

main/python-markdown/template.py

https://github.com/Python-Markdown/markdown/blob/4f0b91abe1a954a72ab3c99c3e2b880ab36631fa/docs/changelog.md

main/python-markdown: update to 3.5

---

main/python-fonttools/template.py

https://github.com/fonttools/fonttools/releases/tag/4.43.1

main/python-fonttools: update to 4.43.1

---

main/c-ares/template.py

https://c-ares.org/changelog.html#1_20_1

main/c-ares: update to 1.20.1

---

main/libxrandr/template.py

https://lists.x.org/archives/xorg-announce/2023-October/003427.html

main/libxrandr: update to 1.5.4

---

main/libxkbcommon/template.py

https://lists.freedesktop.org/archives/wayland-devel/2023-October/043121.html

main/libxkbcommon: update to 1.6.0

---

main/xkeyboard-config/patches/fix-test.patch
main/xkeyboard-config/template.py

https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/5ff20c6a2f905a4d2af714e7394d2b93551b9b17/NEWS

main/xkeyboard-config: update to 2.40

---

contrib/python-zope.interface/template.py

https://github.com/zopefoundation/zope.interface/blob/202d9dce881b75d89d02d3bf2bf446df988c92f8/CHANGES.rst

contrib/python-zope.interface: update to 6.1

---

main/imagemagick/template.py

https://github.com/ImageMagick/ImageMagick/compare/7.1.1-19...7.1.1-20

main/imagemagick: update to 7.1.1.20

---

contrib/eartag/template.py

contrib/eartag: update to 0.5.0

---

main/samba/template.py

https://www.samba.org/samba/history/samba-4.19.1.html

main/samba: update to 4.19.1

---

main/dhcpcd/template.py

https://github.com/NetworkConfiguration/dhcpcd/releases/tag/v10.0.3

main/dhcpcd: update to 10.0.3

---

main/nghttp2/template.py

https://github.com/nghttp2/nghttp2/releases/tag/v1.57.0

main/nghttp2: update to 1.57.0

---

contrib/yt-dlp/template.py

https://github.com/yt-dlp/yt-dlp/releases/tag/2023.10.07

contrib/yt-dlp: update to 2023.10.07

---

main/fuse/template.py

https://github.com/libfuse/libfuse/compare/fuse-3.16.1...fuse-3.16.2

main/fuse: update to 3.16.2

---

main/desktop-file-utils/template.py

https://gitlab.freedesktop.org/xdg/desktop-file-utils/-/blob/2470d73f93d02b354ecbee7c2f02a83efaae84d8/NEWS

main/desktop-file-utils: update to 0.27

---

main/libgusb/template.py

https://github.com/hughsie/libgusb/releases/tag/0.4.7

main/libgusb: update to 0.4.7

---

contrib/7zip/patches/7-zip-flags.patch
contrib/7zip/patches/7-zip-musl.patch
contrib/7zip/template.py
contrib/7zip/update.py

very spicy, get a cucumber soda first

contrib/7zip: new package

---

main/xfsprogs/template.py

https://kernel.googlesource.com/pub/scm/fs/xfs/xfsprogs-dev/+/91d9bdb83deffa675d0d2323433de0748effb581/doc/CHANGES

main/xfsprogs: update to 6.5.0

---

contrib/exfatprogs/patches/signed-overflow.patch
contrib/exfatprogs/template.py

UB patch submitted: https://github.com/exfatprogs/exfatprogs/pull/235

contrib/exfatprogs: new package (1.2.1)

---

main/libcue/template.py

https://github.com/lipnitsk/libcue/releases/tag/v2.3.0

main/libcue: update to 2.3.0

---

main/libblockdev/template.py

https://github.com/storaged-project/libblockdev/blob/67f5b1d89dc17bae48ed2057ccd0d14170373d45/NEWS.rst

main/libblockdev: update to 3.0.4

---

contrib/yt-dlp/template.py

https://github.com/yt-dlp/yt-dlp/releases/tag/2023.10.13

contrib/yt-dlp: update to 2023.10.13

---

main/python-pycodestyle/template.py

https://github.com/PyCQA/pycodestyle/blob/cefd59cf8e8a199a978da491e75a37fe4d37de82/CHANGES.txt

main/python-pycodestyle: update to 2.11.1

---

contrib/oniguruma/template.py

https://github.com/kkos/oniguruma/releases/tag/v6.9.9

contrib/oniguruma: update to 6.9.9

---

main/libical/template.py

https://github.com/libical/libical/releases/tag/v3.0.17

main/libical: update to 3.0.17

---

main/libmysofa/template.py

https://github.com/hoene/libmysofa/releases/tag/v1.3.2

main/libmysofa: update to 1.3.2

---

main/libmbim/template.py
main/libqmi/template.py

these moved off fdo sources to just gitlab tags some time ago

main/libqmi,libmbim: update

---

main/python-pip/template.py

https://pip.pypa.io/en/stable/news/#v23-3

main/python-pip: update to 23.3

---

main/python-pillow/template.py

https://github.com/python-pillow/Pillow/releases/tag/10.1.0

main/python-pillow: update to 10.1.0

---

contrib/python-psutil/template.py

https://github.com/giampaolo/psutil/blob/8eb2930539e8030bae94255040a6254889c0fb05/HISTORY.rst

contrib/python-psutil: update to 5.9.6

---

main/libplacebo/template.py

https://github.com/haasn/libplacebo/releases/tag/v6.338.1

main/libplacebo: update to 6.338.1

---

contrib/qemu-user/template.py
contrib/qemu/template.py

https://lists.nongnu.org/archive/html/qemu-stable/2023-10/msg00102.html

contrib/qemu-user: update to 8.1.2

---

main/man-pages/template.py

main/man-pages: restore manpages that aren't duplicates

---

contrib/nodejs/template.py

https://github.com/nodejs/node/releases/tag/v21.0.0

contrib/nodejs: update to 21.0.0

---

contrib/mold/template.py

https://github.com/rui314/mold/releases/tag/v2.3.0

contrib/mold: update to 2.3.0

---

main/harfbuzz/template.py

https://github.com/harfbuzz/harfbuzz/releases/tag/8.2.2  
dndebug fixed for tests in https://github.com/harfbuzz/harfbuzz/pull/4413

main/harfbuzz: update to 8.2.2

---

main/python-urllib3/template.py

https://github.com/urllib3/urllib3/releases/tag/2.0.7

main/python-urllib3: update to 2.0.7

---

contrib/xfconf/template.py

https://mail.xfce.org/pipermail/xfce-announce/2023-October/001339.html

contrib/xfconf: update to 4.18.2

---

main/texinfo/template.py

https://lists.gnu.org/archive/html/info-gnu/2023-10/msg00003.html

main/texinfo: update to 7.1

---

contrib/foot/template.py

https://codeberg.org/dnkl/foot/releases/tag/1.16.2

contrib/foot: update to 1.16.2

---

main/libbytesize/template.py

https://github.com/storaged-project/libbytesize/blob/6e83cc6f6dff4f126fc79284e0c3c1c50123380d/NEWS.rst

main/libbytesize: update to 2.10

---

main/xcb-util-cursor/template.py

https://lists.x.org/archives/xorg-announce/2023-October/003428.html

main/xcb-util-cursor: update to 0.1.5

---

main/libdrm/template.py

https://lists.x.org/archives/xorg-announce/2023-October/003429.html

main/libdrm: update to 2.4.117

---

contrib/mold/template.py

https://github.com/rui314/mold/releases/tag/v2.3.1

contrib/mold: update to 2.3.1

---

main/meson/template.py

https://github.com/mesonbuild/meson/compare/1.2.2...1.2.3

main/meson: update to 1.2.3

---

main/c-ares/template.py

https://c-ares.org/changelog.html#1_21_0

main/c-ares: update to 1.21.0

---

main/python-pytest/template.py

https://github.com/pytest-dev/pytest/releases/tag/v7.4.3

main/python-pytest: update to 7.4.3

---

main/python-pip/template.py

https://pip.pypa.io/en/stable/news/#v23-3-1

main/python-pip: update to 23.3.1

---

main/python-black/template.py

https://github.com/psf/black/releases/tag/23.10.1

main/python-black: update to 23.10.1

---

main/python-cairo/template.py

https://pycairo.readthedocs.io/en/latest/changelog.html#v1-25-1

main/python-cairo: update to 1.25.1

---

main/usbutils/template.py

https://github.com/gregkh/usbutils/blob/23077bf82534baad8adfe33ce4c02b5fb087eb86/NEWS

main/usbutils: update to 017

---

contrib/mold/template.py

https://github.com/rui314/mold/releases/tag/v2.3.2

contrib/mold: update to 2.3.2

---

main/btrfs-progs/template.py

https://github.com/kdave/btrfs-progs/releases/tag/v6.6

main/btrfs-progs: update to 6.6

---

main/sqlite/template.py

https://www.sqlite.org/releaselog/3_44_0.html

main/sqlite: update to 3.44.0

---

main/iproute2/template.py

https://lore.kernel.org/netdev/20231106090325.07092c87@hermes.local/T/#u

main/iproute2: update to 6.6.0

---

main/xz/template.py

https://git.tukaani.org/?p=xz.git;a=blob;f=NEWS;h=824f58537ea8708f94c7601372c22bcbc61b41ef;hb=5fe1450603dc625340b8b7866fb4a83ff748ad06

main/xz: update to 5.4.5

---

contrib/wine/patches/mabi.patch
contrib/wine/template.py

contrib/wine: update to 8.20

---

main/libxml2/template.py

These are not currently present.

main/libxml2: add libxml2-devel-static

---

contrib/worker/template.py

Template created and formatted.

contrib/worker: new package (<4.12.1>)

---

main/git/template.py

https://marc.info/?l=git&m=170049971430566&w=2

main/git: update to 2.43.0

---

contrib/libspectrum-devel
contrib/libspectrum/template.py

Library necessary for ZX Spectrum emulators.

contrib/libspectrum: new package (1.5.0)

---

main/libxml2/template.py

https://discourse.gnome.org/t/libxml2-2-12-1-released/18159/1

main/libxml2: update to 2.12.1

---

main/pkgconf/template.py

https://github.com/pkgconf/pkgconf/commit/31512b210bb4b3dbcd1d52ca4f5da186d13a618f

main/pkgconf: update to 2.1.0

---

main/meson/template.py

https://mesonbuild.com/Release-notes-for-1-3-0.html

main/meson: update to 1.3.0

---

main/sqlite/template.py

https://sqlite.org/releaselog/3_44_1.html

main/sqlite: update to 3.44.1

---

main/gnutls/template.py

https://lists.gnupg.org/pipermail/gnutls-help/2023-November/004837.html

main/gnutls: update to 3.8.2

---

main/libavif/template.py

https://github.com/AOMediaCodec/libavif/releases/tag/v1.0.2

main/libavif: update to 1.0.2

---

contrib/mold/template.py

https://github.com/rui314/mold/releases/tag/v2.3.3

contrib/mold: update to 2.3.3

---

main/xdg-desktop-portal/template.py

https://github.com/flatpak/xdg-desktop-portal/releases/tag/1.18.2

main/xdg-desktop-portal: update to 1.18.2

---

main/libde265/template.py

https://github.com/strukturag/libde265/releases/tag/v1.0.14  
https://github.com/strukturag/libde265/releases/tag/v1.0.13

main/libde265: update to 1.0.14

---

main/iwd/template.py

https://git.kernel.org/pub/scm/network/wireless/iwd.git/commit/ChangeLog?id=400782b6e4d87ed714b2133e88298c278801a453

main/iwd: update to 2.9

---

main/firmware-sof/template.py

https://github.com/thesofproject/sof-bin/releases/tag/v2023.09.2

main/firmware-sof: update to 2023.09.2

---

main/openssl/template.py

https://www.openssl.org/news/openssl-3.2-notes.html

main/openssl: update to 3.2.0

---

contrib/bat/template.py

Not sure whether this is worth the rebuild or not, but it removes some bits left over from when there was a patch.

contrib/bat: clean up template

---

contrib/fonts-noto-extra
contrib/fonts-noto-extra-otf
contrib/fonts-noto-extra-ttf
contrib/fonts-noto-otf
contrib/fonts-noto-ttf
contrib/fonts-noto/files/46-noto-mono.conf
contrib/fonts-noto/files/46-noto-sans.conf
contrib/fonts-noto/files/46-noto-serif.conf
contrib/fonts-noto/files/66-noto-mono.conf
contrib/fonts-noto/files/66-noto-sans.conf
contrib/fonts-noto/files/66-noto-serif.conf
contrib/fonts-noto/template.py
contrib/fonts-noto/update.py

Not sure about the subpackage, I followed Void's but alpine seems to split it into much smaller ones
fontconfig from Arch

contrib/fonts-noto: new package (23.12.1)

---

main/libspelling-devel
main/libspelling/template.py
main/libspelling/update.py

Not sure if this should be in main instead

main/libspelling: new package (0.2.0)

---

contrib/i2c-tools-devel
contrib/i2c-tools/patches/py-smbus-fix-install.patch
contrib/i2c-tools/template.py
contrib/python-smbus

Umm.. is the commit message OK?
I mean... we are also adding the `python-smbus` package in this same commit.. but how should I mention it in the commit msg?

contrib/i2c-tools: new package (4.3)

---

main/gpgme/template.py

https://github.com/gpg/gpgme/blob/6baccdc0c35d93253975e672bbf608750f97ab2a/NEWS

main/gpgme: update to 1.23.2

---

main/libksba/template.py

https://github.com/gpg/libksba/blob/aea6f0ee144aab48dffa58bdf10f7411a548a159/NEWS

main/libksba: update to 1.6.5

---

main/chrony/template.py

https://gitlab.com/chrony/chrony/-/blob/120dfb8b36b942c31ddfc0220ca1475159ac5031/NEWS

main/chrony: update to 4.5

---

contrib/pcsc-lite/template.py

https://salsa.debian.org/rousseau/PCSC/-/blob/0575a26c371584092326c94450cb38f611e41c9c/ChangeLog

contrib/pcsc-lite: update to 2.0.1

---

contrib/weechat/template.py

https://github.com/weechat/weechat/releases/tag/v4.1.2

contrib/weechat: update to 4.1.2

---

contrib/mold/template.py

https://github.com/rui314/mold/releases/tag/v2.4.0

contrib/mold: update to 2.4.0

---

main/curl/template.py

https://curl.se/changes.html#8_5_0

main/curl: update to 8.5.0

---

contrib/containers-common/patches/settings.patch
contrib/containers-common/template.py
contrib/podman/template.py

https://github.com/containers/podman/releases/tag/v4.8.0  
https://github.com/containers/podman/releases/tag/v4.8.1

contrib/podman: update to 4.8.1

---

main/wireplumber/template.py

https://gitlab.freedesktop.org/pipewire/wireplumber/-/releases/0.4.17

main/wireplumber: update to 0.4.17

---

contrib/nodejs/template.py

https://github.com/nodejs/node/releases/tag/v21.3.0  
https://github.com/nodejs/node/releases/tag/v21.4.0

contrib/nodejs: update to 21.4.0

---

main/openssh/template.py

https://lists.mindrot.org/pipermail/openssh-unix-announce/2023-December/000155.html

main/openssh: update to 9.6p1

---

main/gstreamer-libcamera
main/libcamera-devel
main/libcamera/patches/00-meson_build.patch
main/libcamera/patches/01-ipu3_basename.patch
main/libcamera/template.py
main/pipewire/template.py

IPA module signing has been patched out... because I couldn't decide whether keep it or patch it out :sweat_smile: 
Tested on x86_64... seems to be working (i.e. flatpak camera app works)..

main/libcamera: new package (0.1.0)

---

contrib/libftdi1/template.py

Fix description: this is libftdi not yajl.

contrib/libftdi1: Fix pkgspec

---

main/fontconfig/template.py

https://gitlab.freedesktop.org/fontconfig/fontconfig/-/blob/72b9a48f57de6204d99ce1c217b5609ee92ece9b/NEWS

main/fontconfig: update to 2.15.0

---

contrib/gopls/template.py
contrib/gopls/update.py

Credit goes to jimbassfisher on IRC for providing the initial template.

contrib/gopls: new package (0.14.2)

---

contrib/git-branchless/template.py

One test fails. It seems innocuous, but I need to investigate some more.

contrib/git-branchless: new package (0.8.0)

---

contrib/catatonit/template.py
contrib/docker-compose/template.py
contrib/podman/patches/basename.patch
contrib/podman/template.py

contrib/docker-compose: new package (2.23.3)

---

README.md

I recommend adding links in README for faster file navigation.

readme: link to other documents

---

contrib/python-maturin/template.py

contrib/python-maturin: new package (1.4.0)

---

contrib/nload/template.py

Package: http://www.roland-riegel.de/nload

contrib/nload: new package (0.7.4)

---

contrib/python-filelock/template.py

Package: https://github.com/tox-dev/filelock

contrib/python-filelock: new package (3.13.1)

---

contrib/firewall-config
contrib/firewalld/files/firewalld
contrib/firewalld/patches/0001-don-t-build-tests.patch
contrib/firewalld/patches/0002-don-t-build-firewall-applet.patch
contrib/firewalld/patches/0004-the-year-is-2024.patch
contrib/firewalld/template.py

making this as a draft since i'm not sure it's good enough to get merged

contrib/firewalld: new package (2.1.0)

---

contrib/python-itsdangerous/template.py

Package: https://github.com/pallets/itsdangerous

contrib/python-itsdangerous: new package (2.1.2)

---

main/iw/template.py

main/iw: update to 6.7

---

contrib/python-sortedcontainers/template.py

https://github.com/grantjenks/python-sortedcontainers

contrib/python-sortedcontainers: new package (2.4.0)

---

user/rspamd/template.py

https://github.com/rspamd/rspamd/blob/3.8.0/ChangeLog

user/rspamd: update to 3.8.0

---

contrib/android-udev-rules/template.py

https://github.com/M0Rf30/android-udev-rules/compare/20231207...20240114

contrib/android-udev-rules: update to 20240114

---

contrib/python-flask/template.py

https://github.com/pallets/flask

contrib/python-flask: new package (3.0.1)

---

contrib/python-asgiref/template.py

https://github.com/django/asgiref

contrib/python-asgiref: new package (3.7.2)

---

contrib/firefox/patches/fix-fortify-system-wrappers.patch
contrib/firefox/patches/ppc64-webrtc.patch
contrib/firefox/patches/py312.patch
contrib/firefox/patches/sqlite-ppc.patch
contrib/firefox/template.py

would be nice to roll this with libvpx in the other mr but have to fix thunderbird, bleh  
dbus-glib was dropped in 120
[ci skip]

contrib/firefox: update to 122.0

---

contrib/nsd/patches/0001-fix-dname-compare-cfi.patch
contrib/nsd/template.py

Discovered a crash with CFI, this seems to fix it :)

contrib/nsd: fix issues with CFI

---

user/rspamd/template.py

https://github.com/rspamd/rspamd/releases/tag/3.8.1

user/rspamd: update to 3.8.1

---

contrib/btrbk/patches/fix_illegal_time_format.patch
contrib/btrbk/patches/fix_readlink_flags.patch
contrib/btrbk/template.py
contrib/mbuffer/template.py

also includes its dependencies contrib/mbuffer (20231216) and contrib/asciidoctor (2.0.20)

contrib/btrbk: new package (0.32.6)

---

.github/workflows/build.yml

https://github.com/actions/cache/releases/tag/v4.0.0

ci: update actions/cache to v4

---

main/sushi/template.py

Fixes broken spacebar preview in Nautilus.

main/sushi: add missing gtksourceview4 runtime dep

---

contrib/python-flask-login/template.py

https://github.com/maxcountryman/flask-login

contrib/python-flask-login: new package (0.6.3)

---

contrib/pkcs11-helper-devel
contrib/pkcs11-helper/template.py

Hi, I want to add openvpn package and this is one of the dependencies.

contrib/pkcs11-helper: new package (1.30.0)

---

contrib/firefox/template.py

contrib/firefox: update to 122.0.1

---

contrib/gnome-tweaks/template.py
main/gcr/template.py
main/gnome-control-center/template.py
main/gnome-initial-setup/template.py
main/gnome-shell/template.py
main/mutter/template.py

- contrib/gnome-tweaks: update to 45.1
- main/gnome-initial-setup: update to 45.4.1
- main/gnome-shell: update to 45.4
- main/gnome-control-center: update to 45.3
- main/gcr: update to 4.2.0

GNOME updates

---

user/rspamd/template.py

* https://github.com/rspamd/rspamd/releases/tag/3.8.2

user/rspamd: update to 3.8.2

---

main/musl/files/getent.1
main/musl/files/getent.c
main/musl/template.py

imported from alpine aports getent.c  
---
i rolled the manpage update myself, so i'm not sure if i named the fields right (and the sp_ stuff is an eyesore and overflows the line length.. not sure how to improve that) :)

main/musl: add ahosts/ahostsv4/ahostsv6/shadow to getent

---

main/zip/template.py

Did some tests and it seems to be working fine.

main/zip: enable int

---

main/libwpe/patches/poison.patch
main/libwpe/template.py

https://github.com/WebPlatformForEmbedded/libwpe/releases/tag/1.14.2

main/libwpe: update to 1.14.2

---

main/libtraceevent/patches/0001-libtraceevent-utest-Include-libgen.h-for-basename-wi.patch
main/libtraceevent/template.py
main/libtracefs/patches/0001-libtracefs-utest-Add-PATH_MAX-if-it-is-not-already-d.patch
main/libtracefs/patches/0002-libtracefs-utest-Define-_LARGEFILE64_SOURCE-for-lsee.patch
main/libtracefs/patches/0003-libtracefs-utest-Include-libgen.h-for-basename.patch
main/libtracefs/template.py

enable various tests that need cunit

---

contrib/android-udev-rules/template.py

https://github.com/M0Rf30/android-udev-rules/compare/20240114...20240221

contrib/android-udev-rules: update to 20240221

---

contrib/qt6-qt5compat/template.py

contrib/qt6-qt5compat: enable tests

---

user/rspamd/template.py

https://github.com/rspamd/rspamd/releases/tag/3.8.4

user/rspamd: update to 3.8.4

---

contrib/darktable/template.py
contrib/efl/template.py
contrib/libvips/template.py
contrib/swayimg/template.py
main/imagemagick/template.py
main/libjxl/template.py
main/sdl_image/template.py
main/webkitgtk/template.py
main/webkitgtk4/template.py

main/libjxl: update to 0.10.0

---

main/accountsservice/patches/autologin-segfault-on-non-recognized-dm.patch
main/accountsservice/patches/dm-detection-with-dinit.patch
main/accountsservice/template.py

Fixes https://github.com/chimera-linux/cports/issues/1366.

main/accountsservice: fix GDM autologin

---

contrib/bubblejail/template.py
contrib/python-tomli-w/template.py

This is blocking on runtime dependency: python-pyqt6

Bubblejail and build dependencies: python-tomli-w

---

contrib/chromium/template.py

contrib/chromium: update to 122.0.6261.94

---

contrib/android-tools/template.py
contrib/mosh/template.py
contrib/protobuf-c/template.py
contrib/protobuf/template.py

- **contrib/protobuf: update to 25.3**
- **contrib/android-tools: revbump for protobuf 25.3**
- **contrib/mosh: revbump for protobuf 25.3**
- **contrib/protobuf-c: revbump for 25.3**

contrib/protobuf: update to 25.3

---

contrib/firefox/patches/sandbox-sched_setscheduler.patch
contrib/firefox/template.py

[ci skip]  
https://www.mozilla.org/en-US/firefox/123.0.1/releasenotes/

contrib/firefox: update to 123.0.1

---

contrib/python-twisted/template.py

https://github.com/twisted/twisted/releases/tag/twisted-24.3.0

contrib/python-twisted: update to 24.3.0

---

contrib/chromium/template.py

contrib/chromium: update to 122.0.6261.111

---

contrib/chromium/template.py

contrib/chromium: update to 122.0.6261.128

---

contrib/capnproto-devel
contrib/capnproto/template.py
contrib/capnproto/update.py
contrib/sequoia-sq/patches/0001-replace-deprecated-chrono-function.patch
contrib/sequoia-sq/template.py

contrib/sequoia-sq: new package (0.34.0)

---

main/npth/patches/musl-fix-build.patch
main/npth/patches/pc-file-version.patch
main/npth/template.py

main/npth: update to 1.7

---

main/power-profiles-daemon/patches/readiness-dbus.patch
main/power-profiles-daemon/template.py

main/power-profiles-daemon: update to 0.20

---

user/btop/patches/nomisc.patch
user/btop/template.py

first contribution :3
cbuild is so nice to work with

user/btop: new package (1.3.2)

---

contrib/klystrack/template.py

as discussed in irc, this points to a fork of mine with an updated (and actually working) build script

contrib/klystrack: new package (1.7.8)

---

src/cbuild/core/template.py

cbuild: pass --remap-path-prefix for rustc

---

contrib/snibbetracker/patches/8483d24a61703bcbab114673fae11ca4c5f0ef28.patch
contrib/snibbetracker/template.py

turns out the rest of that commit was necessary!

contrib/snibbetracker: backport rest of linux fixes

---

contrib/android-tools/patches/ppc.patch
contrib/android-tools/template.py
contrib/mosh/template.py
contrib/protobuf-c/patches/protobuf-26.patch
contrib/protobuf-c/template.py
contrib/protobuf/template.py

Seems fine from a quick test
https://github.com/protocolbuffers/protobuf/releases/tag/v26.0

Protobuf 26

---

contrib/thunderbird/template.py

contrib/thunderbird: update to 115.9.0

---

contrib/firefox/patches/svg-r1.patch
contrib/firefox/patches/svg-r2.patch
contrib/firefox/template.py

contrib/firefox: update to 124.0.1

---

contrib/chromium/template.py

contrib/chromium: update to 123.0.6312.86

---

contrib/gtultra/files/gtultra.desktop
contrib/gtultra/patches/fix_makefile.patch
contrib/gtultra/patches/sprintf_format.patch
contrib/gtultra/template.py

note that this package conflicts with contrib/goattracker from https://github.com/chimera-linux/cports/pull/1581 by installing some binaries with the same names. unsure if i should/how to prevent that

contrib/gtultra: new package (1.5.5)

---

main/glib/template.py

Fix build by adding freetype-bootstrap to makedepends

main/glib: fix build

---

src/cbuild/core/template.py

https://github.com/chimera-linux/cports/commit/c311513f11cd7e3420d7464be6da7cd1aa522e0d broke this

cbuild: let install_shell install absolute links

---

main/power-profiles-daemon/patches/readiness-dbus.patch
main/power-profiles-daemon/template.py
main/python-shtab/patches/tests.patch
main/python-shtab/template.py

- **main/python-shtab: new package (1.7.1)**
- **main/power-profiles-daemon: update to 0.21**

main/power-profiles-daemon: update to 0.21

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/releases/tag/2.9.1

contrib/fastfetch: update to 2.9.1

---

contrib/chromium/template.py

contrib/chromium: update to 123.0.6312.105

---

contrib/nbfc-linux/files/nbfc
contrib/nbfc-linux/patches/fix_install.patch
contrib/nbfc-linux/template.py

Installed with `apk --allow-untrusted` on local machine and tested thoroughly, works as intended.

contrib/nbfc-linux-*: new package

---

contrib/glycin-loaders/patches/meson-cargo.patch
contrib/glycin-loaders/template.py
contrib/loupe/patches/meson-cargo.patch
contrib/loupe/template.py

- **contrib/glycin-loaders: new package (1.0.1)**
- **contrib/loupe: new package (46.2)**

contrib/{glycin-loaders,loupe}: new packages

---

contrib/firefox/template.py

contrib/firefox: update to 124.0.2

---

contrib/xapian-core/template.py
contrib/xapian-core/update.py

contrib/xapian-core: update to 1.4.25

---

main/flatpak/template.py

main/flatpak: update to 1.14.6

---

contrib/bind/template.py

one note: bind seems to depend on bind-devel, i think bc of weirdly versioned sos. is this something to be fixed?

contrib/bind: update to 9.18.26

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/releases/tag/2.10.1

contrib/fastfetch: update to 2.10.1

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/commit/8eabc49e12a3706dbd755da7b77b99de9b58d78e

contrib/fastfetch: update to 2.10.2

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/releases/tag/2.11.1

contrib/fastfetch: update to 2.11.1

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/releases/tag/2.11.2
https://github.com/fastfetch-cli/fastfetch/releases/tag/2.11.3

contrib/fastfetch: update to 2.11.3

---

contrib/certbot/files/tmpfiles.conf
contrib/certbot/template.py
contrib/python-configargparse/template.py
contrib/python-distro/template.py

and deps python-configargparse, python-distro

contrib/certbot: new package (2.10.0)

---

contrib/ayatana-ido-devel
contrib/ayatana-ido/patches/disable-Weverything.patch
contrib/ayatana-ido/template.py
contrib/libayatana-appindicator-devel
contrib/libayatana-appindicator/patches/sed.patch
contrib/libayatana-appindicator/template.py
contrib/libayatana-indicator-devel
contrib/libayatana-indicator/template.py
contrib/network-manager-applet/template.py
main/libnma/template.py

- **contrib/ayatana-ido: new package (0.10.2)**
- **contrib/libayatana-indicator: new package (0.9.4)**
- **contrib/libayatana-appindicator: new package (0.5.93)**
- **contrib/network-manager-applet: new package (1.36.0)**
- **main/libnma: remove file conflicting with contrib/network-manager-applet**

contrib/network-manager-applet: new package (1.36.0)

---

contrib/libsixel-devel
contrib/libsixel-progs
contrib/libsixel/patches/remove-unitsd-include.patch
contrib/libsixel/template.py

tmux can be built with sixel support, but I wanted to check if this should go in contrib and if we even wanted tmux to have sixel support enabled

contrib/libsixel: new package (1.10.3)

---

contrib/thunderbird/patches/libcxx18.patch
contrib/thunderbird/patches/llvm18-bindgen.patch
contrib/thunderbird/patches/llvm18.patch
contrib/thunderbird/patches/pred.patch
contrib/thunderbird/template.py
contrib/thunderbird/update.py

contrib/thunderbird: update to 115.10.0

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/blob/dev/CHANGELOG.md

contrib/fastfetch: update to 2.12.0

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/releases/tag/2.13.0

contrib/fastfetch: update to 2.13.0

---

contrib/parole/template.py
contrib/ristretto/template.py
contrib/xfce4-panel/template.py
contrib/xfce4-screensaver/template.py
contrib/xfce4-screenshooter/template.py
contrib/xfdesktop/template.py

- **contrib/parole: fix check**
- **contrib/xfdesktop: fix check**
- **contrib/xfce4-screenshooter: fix check**
- **contrib/xfce4-panel: fix check**
- **contrib/ristretto: fix check**
- **contrib/xfce4-screensaver: fix check**

Fix check stage of various xfce packages

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/blob/2.14.0/CHANGELOG.md

contrib/fastfetch: update to 2.14.0

---

contrib/python-distutils-extra/patches/skip-icons-test.patch
contrib/python-distutils-extra/template.py
contrib/python-distutils-extra/update.py
contrib/python-httplib2/patches/remove-pytest-cov-dep.patch
contrib/python-httplib2/patches/use-system-certificates.patch
contrib/python-httplib2/template.py

- **contrib/python-httplib2: new package (0.22.0)**
- **contrib/python-distutils-extra: update to 3.0**

contrib/python-distutils-extra: update to 3.0

---

contrib/blueman/template.py
contrib/dolphin/template.py
contrib/emacs-console/template.py
contrib/emacs-gtk3/template.py
contrib/emacs-pgtk/template.py
contrib/kactivitymanagerd/template.py
contrib/kded/template.py
contrib/kglobalacceld/template.py
contrib/kscreen/template.py
contrib/ksystemstats/template.py
contrib/kwin/template.py
contrib/libkscreen/template.py
contrib/nvme-cli/template.py
contrib/plasma-workspace/template.py
contrib/spectacle/template.py
contrib/xdg-desktop-portal-kde/template.py
main/dconf/template.py
main/evince/template.py
src/cbuild/hooks/pre_pkg/098_lint.py

- **cbuild: forbid installation to usr/lib/systemd/{system,user}**
- ***/*: don't install systemd services**

cbuild: forbid installation to usr/lib/systemd/{system,user}

---

user/blink/patches/install_to_destdir.patch
user/blink/template.py

this cant actually run chimera-native executables, so mostly here as a curiosity

user/blink: new package (1.1.0)

---

contrib/attica/template.py
contrib/knewstuff/template.py

- **contrib/attica: !cfi**
- **contrib/knewstuff: !cfi**

Fix "Get New Plugins..." button crashing Plasma system settings

---

main/iproute2/template.py

main/iproute2: remove header file

---

contrib/xfdashboard/template.py

contrib/xfdashboard: use better url

---

contrib/beets/patches/nocov.patch
contrib/beets/patches/typing.patch
contrib/beets/template.py
contrib/python-confuse/template.py
contrib/python-coverage/template.py
contrib/python-jellyfish/template.py
contrib/python-mediafile/template.py
contrib/python-munkres/template.py
contrib/python-musicbrainzngs/template.py
contrib/python-unidecode/template.py
contrib/python-unidecode/update.py

Hi cports enthusiasts,
I've juste packaged beets (CLI media manager) and all deps.
Checks are disabled for some packages where it lacks dependencies.
Hope you enjoy it.
Built and tested on arm64 (rpi400).

contrib/beets: new package (2.0.0) + depends

---

contrib/firefox/patches/backport-D210814.patch
contrib/firefox/template.py

https://phabricator.services.mozilla.com/D210814
closes #2133

contrib/firefox: backport fix for segfaults on loading XML

---

main/linux-headers/template.py
main/llvm/template.py
main/openssl/template.py
src/cbuild/util/cmake.py
src/cbuild/util/meson.py

i dont seem to be getting the static zlib cross issues anymore

armhf/armv7 support for base-cbuild

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/releases/tag/2.15.0

contrib/fastfetch: update to 2.15.0

---

contrib/sbctl/template.py

https://github.com/Foxboron/sbctl/releases/tag/0.14

contrib/sbctl: update to 0.14

---

main/gnome-text-editor/template.py

also remove unused/redundant deps

main/gnome-text-editor: set bugreport url to our issue tracker

---

main/enchant/template.py
main/unittest-cpp/patches/0001-CMakeLists-set-version.patch
main/unittest-cpp/patches/0001-CMakeLists.txt-fix-PACKAGE_VERSION-substitution-in-..patch
main/unittest-cpp/template.py

main/enchant: enable tests

---

contrib/python-websockets/template.py
contrib/yt-dlp/template.py
main/brotli/template.py
main/python-brotli/template.py

contrib/yt-dlp: enable tests

---

contrib/weechat/patches/0001-src-plugins-weechat-plugin-fix-muloveflow-in-weechat.patch
contrib/weechat/template.py

as annotated in the template, the tests seem sorta broken (immediately complains about a memory leak *in the tests* for instance)

contrib/weechat: enable building of docs and man pages

---

contrib/embree/template.py

also removed some unnecessary deps i left in somehow. tee hee

contrib/embree: update to 4.3.2

---

contrib/neovim/template.py
contrib/tree-sitter-bash-devel
contrib/tree-sitter-bash/template.py
contrib/tree-sitter-bash/update.py
contrib/tree-sitter-c-devel
contrib/tree-sitter-c/template.py
contrib/tree-sitter-c/update.py
contrib/tree-sitter-lua/template.py
contrib/tree-sitter-lua/update.py
contrib/tree-sitter-markdown-devel
contrib/tree-sitter-markdown/patches/install.patch
contrib/tree-sitter-markdown/patches/makefile.patch
contrib/tree-sitter-markdown/template.py
contrib/tree-sitter-markdown/update.py
contrib/tree-sitter-python-devel
contrib/tree-sitter-python/patches/install.patch
contrib/tree-sitter-python/template.py
contrib/tree-sitter-python/update.py
contrib/tree-sitter-query/template.py
contrib/tree-sitter-query/update.py
contrib/tree-sitter-vimdoc/template.py
contrib/tree-sitter-vimdoc/update.py

v0.10.0 added requirement of markdown treesitter parser.

neovim: add missing dependency

---

contrib/nbfc-linux/patches/install.patch
contrib/nbfc-linux/template.py

contrib/nbfc-linux: update to 0.2.7

---

contrib/miniupnpd/template.py

As suggested by miniupnpd developer, make pkgdesc more accurate.  No
functional changes intended.

contrib/miniupnpd: adjust pkgdesc

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/releases/tag/2.16.0

contrib/fastfetch: update to 2.16.0

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/releases/tag/2.17.0

contrib/fastfetch: update to 2.17.0

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/releases/tag/2.17.1

contrib/fastfetch: update to 2.17.1

---

contrib/libdbusmenu-lxqt-devel
contrib/libdbusmenu-lxqt/template.py
contrib/liblxqt-devel
contrib/liblxqt/template.py
contrib/libqtxdg-devel
contrib/libqtxdg/template.py
contrib/lxqt-config/patches/add-explict-constructor.patch
contrib/lxqt-config/template.py
contrib/lxqt-globalkeys-devel
contrib/lxqt-globalkeys/template.py
contrib/lxqt-menu-data/template.py
contrib/lxqt-panel/template.py
contrib/lxqt-runner/template.py
contrib/lxqt-session/template.py
contrib/lxqt-themes/template.py
contrib/muparser-devel
contrib/muparser/template.py
contrib/qtxdg-tools/template.py

Someone has reported issues with lxqt-panel and lxqt-runner under river and I think I need to run them under a debugger to figure out what's going on. Unfortunately these packages don't work yet and seem to require further LXQt components in order to function. I guess I'll keep packaging LXQt stuff until I get them running properly or get bored.

Assorted LXQt components

---

main/mpv/template.py

i don't have the time to look into this further now, but i'll take another look at it later

main/mpv: disable int for now

---

Packaging.md

packaging: list armhf, armv7 as untiered targets

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/releases/tag/2.17.2

contrib/fastfetc: update to 2.17.2

---

main/llvm-bootstrap/template.py

main/llvm-bootstrap: fix parsing for broken archs

---

contrib/go/template.py

tested on x86_64, should be tested on other archs as well

contrib/go: run tests

---

main/gvfs/template.py
main/msgraph-devel
main/msgraph/template.py

- **main/msgraph: new package (0.2.3)**
- **main/gvfs: add onedrive support**

main/gvfs: add onedrive support

---

main/modemmanager/files/modemmanager
main/modemmanager/template.py

still learning to write services, complain if something isn't right

main/modemmanager: add service file

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/blob/2.18.0/CHANGELOG.md

contrib/fastfetch: update to 2.18.0

---

user/rspamd/patches/tests.patch
user/rspamd/template.py

* https://github.com/rspamd/rspamd/releases/tag/3.9.0

user/rspamd: update to 3.9.0

---

contrib/hugo/template.py

https://github.com/gohugoio/hugo#build-from-source

contrib/hugo: switch to extended build

---

user/plan9port/update.py

user/plan9port: add update check

---

main/libx11/template.py

main/libx11: remove !cross

---

contrib/clang-mingw-w64-aarch64
contrib/clang-mingw-w64-armv7
contrib/clang-mingw-w64-i686
contrib/clang-mingw-w64-x86_64
contrib/clang-mingw-w64/template.py

contrib/clang-mingw-w64: new package (0.1)

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/blob/2.20.0/CHANGELOG.md

contrib/fastfetch: update to 2.20.0

---

contrib/fossil/update.py

see https://fossil-scm.org/forum/forumpost/689637b992b97e83

contrib/fossil: fix update check

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/releases/tag/2.21.0

contrib/fastfetch: update to 2.21.0

---

main/less/template.py

submitting as a pr because of this line that comes from running the tests:
```
sh: lessecho: not found
```
the tests still pass, but i'm not sure where this error is coming from

main/less: reenable tests

---

user/tarsnap/patches/tarsnap-1.0.40-strict-aliasing-fix.patch
user/tarsnap/template.py

Not sure it's proper to put the sample config in /etc.

user/tarsnap: new package

---

contrib/autofs/files/automount
contrib/autofs/patches/0001-auto.master-change-paths-in-etc.patch
contrib/autofs/patches/autofs-5.1.9-Fix-incompatible-function-pointer-types-in-cyrus-sasl-module.patch
contrib/autofs/patches/musl.patch
contrib/autofs/patches/portable-install.patch
contrib/autofs/template.py

contrib/autofs: new package (5.1.9)

---

contrib/openjdk17/template.py
contrib/openjdk21/template.py

contrib/openjdk*: use custom targets for bootstrap

---

user/halibut/template.py
user/puzzles/template.py
user/puzzles/update.py

New packages:
* user/halibut (1.3)
* user/puzzles (20240802)

user/puzzles: new package (20240802)

---

contrib/debian-archive-keyring/template.py
contrib/debootstrap/template.py

 contrib/debootstrap: new package (1.0.137)

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/blob/2.21.3/CHANGELOG.md

contrib/fastfetch: update to 2.21.3

---

main/btrfs-progs/template.py
main/libpwquality/template.py
main/python-cython/template.py
main/python-lxml/template.py
main/python-setuptools/patches/cross_overrides.patch
main/python-setuptools/template.py
src/cbuild/build_style/python_pep517.py

hopefully this isn't too sketch

 main/python-setuptools: add sysconfig overrides for build_ext 

---

contrib/ansible-core/patches/01-skip-failing-test.patch
contrib/ansible-core/template.py
contrib/ansible/template.py
contrib/python-commentjson/template.py
contrib/python-resolvelib/template.py
contrib/sshpass/template.py

contrib/ansible: new package

---

contrib/zellij/template.py
user/zellij/template.py

Zellij is a modern terminal multiplexer written in rust. Would be nice to have in cports.
https://zellij.dev/about/

user/zellij: new package

---

user/pulsemixer/template.py

user/pulsemixer: new package

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/releases/tag/2.22.0

contrib/fastfetch: update to 2.22.0

---

contrib/rrdtool/files/rrdcached
contrib/rrdtool/template.py

Add an initial service file for rrdcached.

contrib/rrdtool: add rrdcached service

---

main/asciidoctor/template.py
main/ccache/template.py
main/ndctl/template.py

why is it so hard to come up with a good title for this pr

Build manpages with asciidoctor

---

user/g4music/template.py

I really wanted to use this music player as my default in my setup, so heres the package! Apparently everything seems to install properly, the binary and the desktop files :p

user/g4music: new package

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/releases/tag/2.23.0

contrib/fastfetch: update to 2.23.0

---

user/gnome-podcasts/patches/meson-cargo.patch
user/gnome-podcasts/template.py
user/gnome-podcasts/update.py

Checks are busted right now but this should be pretty much good to go

user/gnome-podcasts: new package (0.7.1)

---

user/libgbinder-devel
user/libgbinder/template.py
user/libglibutil-devel
user/libglibutil/template.py
user/python-gbinder/patches/cython.patch
user/python-gbinder/template.py
user/waydroid/files/51_waydroid.nft
user/waydroid/files/modules-load.conf
user/waydroid/files/waydroid-container
user/waydroid/patches/apparmor-config.patch
user/waydroid/patches/nft-install.patch
user/waydroid/patches/sed-chimera.patch
user/waydroid/template.py

This library + its dev variant is required for libgbinder to be built

user/waydroid: new package

---

user/waydroid/patches/sed-chimera.patch
user/waydroid/template.py

This PR should fix a weird sed -i bug that waydroid has when using chimerautils, as me and @q66  talked about in https://github.com/chimera-linux/cports/pull/2866#discussion_r1749347399 - in this case it just fixes a misunderstanding i had when trying to fix it

user/waydroid: fix backup arg in sed

---

contrib/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/releases/tag/2.24.0

contrib/fastfetch: update to 2.24.0

---

user/static-web-server/patches/0001-remove-jemalloc.patch
user/static-web-server/patches/0002-feat-support-for-generating-man-pages-and-completion.patch
user/static-web-server/template.py

Still missing a dinit service, but I'd like to add that later. Just using it for local testing at the moment.

contrib/static-web-server: new package (2.32.2)

---

main/xcb-util-keysyms/template.py

while here, add autotools dependencies and remove empty configure_gen

main/xcb-util-keysyms: install license file

---

user/gtk4-layer-shell-devel
user/gtk4-layer-shell/template.py

[It's like main/gtk-layer-shell but gtk4](https://github.com/wmww/gtk4-layer-shell).

user/gtk4-layer-shell: new package

---

user/protontricks/patches/ff2381ad379a612e73f0d4604f1c9c3a012b3355.patch
user/protontricks/template.py

blocked on https://github.com/Matoking/protontricks/issues/346

user/protontricks: update to 1.12.0

---

user/nxengine-evo/patches/newer-deps.patch
user/nxengine-evo/template.py

just had to get the data/ directory from the windows release cuz the source code does not contain the necessary assets to actually boot up the game

user/nxengine-evo: new package

---

user/curtail/template.py
user/oxipng/template.py

honestly kinda funny to see that this tool uses shelling out to actually compress stuff. but well, it is quite useful!

user/curtail: new package

---

main/bambootracker/template.py

main/bambootracker: sort these lists

---

user/rspamd/patches/unbundle-hiredis.patch
user/rspamd/template.py

rspamd bundled version has been update and no longer modified https://github.com/rspamd/rspamd/pull/5167

user/rspamd: use system hiredis

---

main/mbuffer/template.py

main/mbuffer: update to 20241007

---

user/rspamd/template.py

* https://github.com/rspamd/rspamd/releases/tag/3.10.1

user/rspamd: update to 3.10.1

---

user/rspamd/template.py

* https://github.com/rspamd/rspamd/releases/tag/3.10.2

user/rspamd: update to 3.10.2

---

main/fastfetch/template.py

https://github.com/fastfetch-cli/fastfetch/releases/tag/2.28.0

main/fastfetch: update to 2.28.0

---

user/feh/template.py
user/perl-test-command/template.py
user/perl-test-command/update.py

Now correct commits, originally #3052

user/feh: new package

---

user/opentofu/template.py

Hi, my first contribution adding a new package.
https://opentofu.org/

user/opentofu: new package

---

main/python-boto3/template.py
main/python-botocore/template.py

- **main/python-botocore: update to 1.35.63**
- **main/python-boto3: update to 1.35.63**

main/python-boto*: update to 1.35.63

---

main/sbctl/template.py

Tested: signing and generating UKI bundles.

main/sbctl: update to 0.16

---

user/incus/files/envfile
user/incus/files/incus
user/incus/files/tmpfiles.conf
user/incus/template.py

This adds a file for environment variables, /etc/default/incus
resolves https://github.com/chimera-linux/cports/issues/3206

user/incus: Add /etc/default/incus file for environment variables

---

user/zed/template.py

user/zed: update to 0.163.2

---

main/python-boto3/template.py
main/python-botocore/template.py

- **main/python-botocore: update to 1.35.71**
- **main/python-boto3: update to 1.35.71**

main/python-boto*: update to 1.35.71

---

user/maven/template.py
user/maven/update.py

Couldn't get the update string to match other versions one directory down (for when a new major version is release). Everything else should be fine

user/maven: new package

---

user/decibels/template.py
user/decibels/update.py
user/typescript/template.py

Depends on TSC, so packaged typescript with it

user/decibels: new package

---

user/zed/template.py

main/zed: update to 0.164.2

---

main/libmaxminddb-devel
main/libmaxminddb/template.py
main/suricata-devel
main/suricata/files/suricata
main/suricata/files/tmpfiles.conf
main/suricata/template.py

- **main/libmaxminddb: new package (1.11.0)**
- **main/suricata: new package (7.0.7)**

main/suricata: new package (7.0.7)

---

main/girara/template.py
main/zathura/template.py

- **main/girara: update to 0.4.5**
- **main/zathura: update to 0.5.9**

main/zathura: update to 0.5.9

---

main/pdfjs/template.py
main/qutebrowser/template.py

- **main/qutebrowser: update to 3.4.0**
- **main/pdfjs: switch to legacy distribution**

main/qutebrowser: update to 3.4.0

---

main/tinymist/template.py

main/tinymist: update to 0.12.12

---

main/zathura/template.py

main/zathura: update to 0.5.11

---

main/suricata/template.py

main/suricata: update to 7.0.8

---

user/monolith/template.py

user/monolith: new package

---

user/love/template.py

user/LÖVE: new package

---

main/docker-cli-buildx/template.py

main/docker-cli-buildx: update to 0.19.3

---

main/kakoune-lsp/template.py

main/kakoune-lsp: update to 18.1.1

---

user/delve/template.py

user/delve: move from main, update to 1.24.0

---

user/rspamd/template.py

https://github.com/rspamd/rspamd/releases/tag/3.11.0

user/rspamd: update to 3.11.0

---

main/lua5.4-luasystem/template.py

main/lua5.4-luasystem: update to 0.4.5

---

main/waycheck/template.py

main/waycheck: update to 1.5.0

---

user/neocmakelsp/template.py

user/neocmakelsp: update to 0.8.14

---

main/python-boto3/template.py
main/python-botocore/template.py

- **main/python-botocore: update to 1.35.86**
- **main/python-boto3: update to 1.35.86**

main/boto*: update to 1.35.86

---

user/rbw/template.py

user/rbw: new package

---

main/bubblejail/patches/skip.patch
main/bubblejail/template.py

also skips completion test that will always fail in cbuild env due to a lack of
completion support for /bin/sh.

main/bubblejail: update to 0.9.4

---

main/weechat/template.py

main/weechat: update to 4.5.1

---

main/satty/template.py

main/satty: update to 0.15.0

---

user/openboard/template.py

user/openboard: update to 1.7.3

---

main/yt-dlp/template.py

main/yt-dlp: update to 2024.12.23

---

main/regreet/template.py

main/regreet: update to 0.1.3

---

main/atuin/patches/0001-Use-openssl.patch
main/atuin/template.py

> for trivial package updates you may remove this
that's referring to the whole template, right?

main/atuin: update to 18.4.0

---

main/broot/template.py

main/broot: update to 1.44.3

---

main/sfeed/template.py

main/sfeed: update to 2.1

---

main/newsraft/template.py

main/newsraft: update to 0.28

---

user/rbw/template.py

user/rbw: update to 1.13.1

---

main/onefetch/patches/zlib.patch
main/onefetch/template.py

main/onefetch: update to 2.23.1

---

main/pdfjs/template.py

main/pdfjs: update to 4.10.38

---

user/tiny/template.py

user/tiny: update to 0.13.0

---

user/moar/template.py

update moar package to 1.30.1 version.

user/moar: update to 1.30.1

---

main/satty/template.py

main/satty: update to 0.16.0

---

main/prosody/template.py

main/prosody: update to 0.12.5

---

user/mu/template.py

user/mu: update to 1.12.8

---

user/gping/template.py
user/gping/update.py

Packaging https://github.com/orf/gping.

user/gping: new package (1.19.0)

---

user/sq/template.py

user/sq: new package

---

main/broot/template.py

main/broot: update to 1.44.5

---

user/pods/patches/meson-cargo.patch
user/pods/patches/no-clippy.patch
user/pods/template.py

this package adds pods, a gtk (libadwaita) app that allows easy management of podman containers
https://github.com/marhkb/pods

user/pods: new package

---

user/got/template.py

user/got: switch libexecdir

---

main/emacs-console/template.py
main/emacs-gtk3/template.py
main/emacs-pgtk/template.py
main/neovim/template.py
main/tree-sitter-cli/template.py
main/tree-sitter/template.py

Works fine in my testing, fixes an annoying bug with tinymist

main/neovim: update to 0.10.3

---

main/fcft/template.py
main/foot/template.py

- **main/fcft: update to 3.1.10**
- **main/foot: update to 1.20.1**

main/foot: update to 1.20.1

---

main/fzf/template.py

main/fzf: update to 0.57.0

---

main/gumbo-parser/template.py
main/newsraft/template.py

- **main/gumbo-parser: update to 0.13.0**
- **main/newsraft: rebuild for gumbo-parser**

main/gumbo-parser: update to 0.13.0

---

main/eza/template.py

main/eza: update to 0.20.15, adopt

---

main/ibus-chewing/template.py

main/ibus-chewing: update to 2.1.3

---

user/kind/template.py

Update kind to 0.26.0. I use kind and I could take maintainership. 

user/kind: update to 0.26.0

---

main/tinymist/template.py

main/tinymist: update to 0.12.16

---

user/nuclei/template.py

user/nuclei: update to 3.3.7

---

main/jaq/template.py

main/jaq: update to 2.0.1

---

main/just/template.py

main/just: update to 1.38.0

---

user/lego/template.py

user/lego: update to 4.21.0

---

user/got/template.py

user/got: update to 0.107

---

main/qpwgraph/template.py

main/qpwgraph: update to 0.8.1, adopt

---

user/jj/template.py

user/jj: update to 0.25.0, adopt

---

main/spdlog/patches/276ee5f5c0eb13626bd367b006ace5eae9526d8a.patch
main/spdlog/patches/7f8060d5b280eac9786f92ac74d263cc8359c5ed.patch
main/spdlog/template.py

noticed breakage while trying to build j4-desktop-menu

main/spdlog: unbreak with fmt 1.1.1

---

main/stress-ng/template.py

main/stress-ng: update to 0.18.09

---

user/zvm/template.py

user/zvm: update to 0.8.4

---

main/doxygen/template.py

main/doxygen: update to 1.13.2

---

main/regreet/files/regreet.conf
main/regreet/template.py

Also changes the state directory to /var/lib/regreet/ as per the new recommendation.
see: https://github.com/rharish101/ReGreet/releases/tag/0.2.0

main/regreet: update to 0.2.0

---

user/neocmakelsp/template.py

user/neocmakelsp: update to 0.8.16

---

user/tessen/template.py

Add template for `tessen`, an interactive menu for `password-store`.

user/tessen: new package

---

user/television/template.py

Add template for television / `tv`, a fuzzy finder that includes a preview window.

user/television: new package

---

user/dnscontrol/template.py

user/dnscontrol: new package

---

user/spotify-player/template.py

A Spotify player in the terminal with full feature parity

user/spotify-player: new package at 0.20.4

---

main/python-boto3/template.py
main/python-botocore/template.py

- **main/python-botocore: update to 1.35.97**
- **main/python-boto3: update to 1.35.97**

main/python-boto*: update to 1.35.97

---

main/rofi/template.py

main/rofi: update to 1.7.7_p1

---

main/starship/template.py

main/starship: update to 1.22.1

---

main/yq/template.py

main/yq: update to 4.45.1

---

main/gtk-vnc/template.py

main/gtk-vnc: update to 1.4.0

---

user/refine/template.py

_Refine_ is a tool to tweak various aspect of GNOME. _Refine_ is not a fork of _GNOME Tweaks_, and provides GUI access to a raft of advanced and experimental settings which _GNOME Tweaks_ does not.

user/refine: new package

---

user/moreutils/template.py
user/moreutils/update.py
user/perl-ipc-run/template.py
user/perl-ipc-run/update.py

user/moreutils: new package

---

user/trippy/template.py

trippy is a network diagnostic tool that combines the functionality of traceroute and ping

user/trippy: new package

---

main/haproxy/files/haproxy
main/haproxy/patches/readiness.patch
main/haproxy/template.py

main/haproxy: update to 3.1.2

---

main/uv/template.py

main/uv: update to 0.5.18

---

main/aerc/patches/libexec.patch
main/aerc/template.py

main/aerc: update to 0.19.0, adopt

---

main/mercurial/template.py

main/mercurial: update to 6.9.1

---

main/openimagedenoise/template.py

main/openimagedenoise: update to 2.3.2

---

user/udiskie/template.py

deleted #3458  on accident somehow

user/udiskie: new package

---

user/lazygit/template.py

Update `user/lazygit` to 0.45.2.

user/lazygit: update to 0.45.2

---

user/dnscontrol/template.py

user/dnscontrol: update to 4.15.4

---

main/qtractor/template.py

main/qtractor: update to 1.5.2

---

main/python-numpy/template.py

main/python-numpy: update to 2.2.2

---

user/xsimd/patches/ci.patch
user/xsimd/patches/failed-tests.patch
user/xsimd/template.py

add the xsimd package
- [X ] I have read [CONTRIBUTING.md](https://github.com/chimera-linux/cports/blob/master/CONTRIBUTING.md)
- [ X] I have read [Packaging.md](https://github.com/chimera-linux/cports/blob/master/Packaging.md#quality_requirements)
- [X ] I have built and tested my changes on my machine
- [X ] I will take responsibility for my template and keep it up to date

user/xsimd: new package

---

user/go-task/template.py

user/go-task: update to 3.41.0

---

main/python-boto3/template.py
main/python-botocore/template.py
main/python-s3transfer/template.py

- **main/python-s3transfer: update to 0.11.1**
- **main/python-botocore: update to 1.36.2**
- **main/python-boto3: update to 1.36.2**

main/python-boto3: update to 1.36.3

---

user/wayvnc/template.py

user/wayvnc: fix maintainer name

---

main/rofi/template.py

main/rofi: update to 1.7.8_p1

---

main/python-tomli-w/template.py

main/python-tomli-w: update to 1.2.0

---

main/docker-cli-buildx/template.py

main/docker-cli-buildx: update to 0.20.0

---

main/uv/patches/no-jemalloc.patch
main/uv/template.py

main/uv: update to 0.5.21

---

main/libmaxminddb/template.py

Update main/libmaxminddb to 1.12.2

main/libmaxminddb: update to 1.12.2

---

main/swayimg/template.py

main/swayimg: update to 3.7

---

user/dnscontrol/template.py

user/dnscontrol: update to 4.15.5

---

main/docker-cli-buildx/template.py

main/docker-cli-buildx: update to 0.20.1

---

user/kakoune-lsp/template.py

user/kakoune-lsp: update to 18.1.2

---

user/eza/template.py

user/eza: update to 0.20.18

---

user/got/template.py

user/got: update to 0.108
